// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package images

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/image/v2/images"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[Image]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

const AddOp = upstream.AddOp

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult

const FilterEQ = upstream.FilterEQ
const FilterGT = upstream.FilterGT
const FilterGTE = upstream.FilterGTE
const FilterLT = upstream.FilterLT
const FilterLTE = upstream.FilterLTE
const FilterNEQ = upstream.FilterNEQ

type GetResult = upstream.GetResult
type Image = upstream.Image
type ImageDateFilter = upstream.ImageDateFilter
type ImageDateQuery = upstream.ImageDateQuery
type ImageMemberStatus = upstream.ImageMemberStatus

const ImageMemberStatusAccepted = upstream.ImageMemberStatusAccepted
const ImageMemberStatusAll = upstream.ImageMemberStatusAll
const ImageMemberStatusPending = upstream.ImageMemberStatusPending
const ImageMemberStatusRejected = upstream.ImageMemberStatusRejected

type ImagePage = upstream.ImagePage
type ImageStatus = upstream.ImageStatus

const ImageStatusActive = upstream.ImageStatusActive
const ImageStatusDeactivated = upstream.ImageStatusDeactivated
const ImageStatusDeleted = upstream.ImageStatusDeleted
const ImageStatusImporting = upstream.ImageStatusImporting
const ImageStatusKilled = upstream.ImageStatusKilled
const ImageStatusPendingDelete = upstream.ImageStatusPendingDelete
const ImageStatusQueued = upstream.ImageStatusQueued
const ImageStatusSaving = upstream.ImageStatusSaving
const ImageStatusUploading = upstream.ImageStatusUploading

type ImageVisibility = upstream.ImageVisibility

const ImageVisibilityCommunity = upstream.ImageVisibilityCommunity
const ImageVisibilityPrivate = upstream.ImageVisibilityPrivate
const ImageVisibilityPublic = upstream.ImageVisibilityPublic
const ImageVisibilityShared = upstream.ImageVisibilityShared

type ListOpts = upstream.ListOpts
type Patch = upstream.Patch

const RemoveOp = upstream.RemoveOp

type ReplaceImageChecksum = upstream.ReplaceImageChecksum
type ReplaceImageHidden = upstream.ReplaceImageHidden
type ReplaceImageMinDisk = upstream.ReplaceImageMinDisk
type ReplaceImageMinRam = upstream.ReplaceImageMinRam
type ReplaceImageName = upstream.ReplaceImageName
type ReplaceImageProtected = upstream.ReplaceImageProtected
type ReplaceImageTags = upstream.ReplaceImageTags

const ReplaceOp = upstream.ReplaceOp

type UpdateImageProperty = upstream.UpdateImageProperty
type UpdateOp = upstream.UpdateOp
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type UpdateVisibility = upstream.UpdateVisibility
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToImageCreateMap() (map[string]any, error) {
	value0, err := b.base.ToImageCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Image, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "images", err)
		var zero0 *Image
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "images", err)
		var zero0 *Image
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "images", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "images", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Image, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "images", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToImageListQuery() (string, error) {
	value0, err := b.base.ToImageListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Image, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "images", err)
		return func(yield func(*Image, error) bool) { var zero *Image; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "images", err)
		return func(yield func(*Image, error) bool) { var zero *Image; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Image, error) {
		values, err := upstream.ExtractImages(page)
		return []Image(values), err
	})
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToImageUpdateMap() ([]any, error) {
	return b.base.ToImageUpdateMap()
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Image, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "images", err)
		var zero0 *Image
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, false, false); err != nil {
		err = request.Wrap("Update", "images", err)
		var zero0 *Image
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "images", err)
	return value0, err
}
