// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package volumes

import (
	context "context"
	fmt "fmt"
	nativefind "github.com/JSYoo5B/gophercloudsdk/internal/nativefind"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/volumes"
	iter "iter"
	maps "maps"
	url "net/url"
	strings "strings"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Volume] {
	return resource.NewCollection(resource.Adapter[Volume]{
		Kind:         "volumes",
		IdentityFind: true,
		GetIdentityQuery: func(ctx context.Context, id string, q url.Values) (*Volume, error) {
			var result upstream.GetResult
			result.Header, result.Err = nativefind.Get(ctx, a.RawClient(), []string{"volumes", id}, q, []int{200}, &result.Body)
			return result.Extract()
		},
		IdentityAllProjectsQuery: "all_tenants",
		IterateIdentity: func(ctx context.Context, q url.Values, details bool) iter.Seq2[*Volume, error] {
			return nativefind.IterateVolumes(ctx, a.RawClient(), q, details)
		},
		Get:       func(ctx context.Context, id string) (*Volume, error) { return a.Get(ctx, string(id)) },
		ID:        func(v *Volume) string { return fmt.Sprint(v.ID) },
		Name:      func(v *Volume) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Status:    func(v *Volume) string { return fmt.Sprint(v.Status) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Volume, error] {
			q = maps.Clone(q)
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Volume, error) {
	return a.Resources.Find(ctx, ref, options...)
}

// FindIdentity tries an ID request before exact ID/name fallback within this collection.
func (a *API) FindIdentity(ctx context.Context, identity string, options ...resource.IdentityFindOption) (*Volume, error) {
	return a.Resources.FindIdentity(ctx, identity, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Volume, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Volume, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
