// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package flavors

import (
	context "context"
	fmt "fmt"
	nativefind "github.com/JSYoo5B/gophercloudsdk/internal/nativefind"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/compute/v2/flavors"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Flavor] {
	return resource.NewCollection(resource.Adapter[Flavor]{
		Kind:         "flavors",
		IdentityFind: true,
		GetIdentityQuery: func(ctx context.Context, id string, q url.Values) (*Flavor, error) {
			var result upstream.GetResult
			result.Header, result.Err = nativefind.Get(ctx, a.RawClient(), []string{"flavors", id}, q, []int{200}, &result.Body)
			return result.Extract()
		},
		IdentityListQueryDefaults: url.Values{"is_public": {"None"}},
		IdentityExtraSpecs: func(ctx context.Context, value *Flavor) (*Flavor, error) {
			return nativefind.FlavorExtraSpecs(ctx, a.RawClient(), value)
		},
		Get:    func(ctx context.Context, id string) (*Flavor, error) { return a.Get(ctx, string(id)) },
		ID:     func(v *Flavor) string { return fmt.Sprint(v.ID) },
		Name:   func(v *Flavor) string { return fmt.Sprint(v.Name) },
		Delete: func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Flavor, error] {
			q = maps.Clone(q)
			options := []ListDetailOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listDetailWithControl(ctx, control, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Flavor, error) {
	return a.Resources.Find(ctx, ref, options...)
}

// FindIdentity tries an ID request before exact ID/name fallback within this collection.
func (a *API) FindIdentity(ctx context.Context, identity string, options ...resource.IdentityFindOption) (*Flavor, error) {
	return a.Resources.FindIdentity(ctx, identity, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Flavor, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Flavor, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
