// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package objects

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/objectstorage/v1/objects"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	io "io"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type BulkDeleteResponse = upstream.BulkDeleteResponse
type BulkDeleteResult = upstream.BulkDeleteResult
type CopyHeader = upstream.CopyHeader
type CopyOpts = upstream.CopyOpts
type CopyResult = upstream.CopyResult
type CreateHeader = upstream.CreateHeader
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type CreateTempURLOpts = upstream.CreateTempURLOpts
type DeleteHeader = upstream.DeleteHeader
type DeleteOpts = upstream.DeleteOpts
type DeleteResult = upstream.DeleteResult
type DownloadHeader = upstream.DownloadHeader
type DownloadOpts = upstream.DownloadOpts
type DownloadResult = upstream.DownloadResult
type ErrTempURLDigestNotValid = upstream.ErrTempURLDigestNotValid
type ErrTempURLKeyNotFound = upstream.ErrTempURLKeyNotFound
type GetHeader = upstream.GetHeader
type GetOpts = upstream.GetOpts
type GetResult = upstream.GetResult
type HTTPMethod = upstream.HTTPMethod
type ListOpts = upstream.ListOpts
type Object = upstream.Object
type ObjectPage = upstream.ObjectPage
type UpdateHeader = upstream.UpdateHeader
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult

// BulkDelete invokes the upstream API with library-owned builders and result handling.
func (a *API) BulkDelete(ctx context.Context, container string, objects []string) (*BulkDeleteResponse, error) {
	result := upstream.BulkDelete(ctx, a.client, container, objects)
	value0, err := result.Extract()
	err = request.Wrap("BulkDelete", "objects", err)
	return value0, err
}

type CopyOption = request.Option[CopyOpts]

func WithCopyOptions(value CopyOpts) CopyOption   { return request.WithOptions(value) }
func WithCopyQuery(key, value string) CopyOption  { return request.WithQuery[CopyOpts](key, value) }
func WithCopyHeader(key, value string) CopyOption { return request.WithHeader[CopyOpts](key, value) }

type copyOptsBuilder struct {
	base   CopyOpts
	config request.Config[CopyOpts]
}

func (b copyOptsBuilder) ToObjectCopyMap() (map[string]string, error) {
	value0, err := b.base.ToObjectCopyMap()
	if err != nil {
		var zero0 map[string]string
		return zero0, err
	}
	value0, err = request.MergeHeadersFor(value0, b.config.Headers, b.base)
	if err != nil {
		var zero0 map[string]string
		return zero0, err
	}
	return value0, nil
}
func (b copyOptsBuilder) ToObjectCopyQuery() (string, error) {
	value0, err := b.base.ToObjectCopyQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// Copy invokes the upstream API with library-owned builders and result handling.
func (a *API) Copy(ctx context.Context, containerName string, objectName string, opts CopyOpts, options ...CopyOption) (*CopyHeader, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Copy", "objects", err)
		var zero0 *CopyHeader
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, true); err != nil {
		err = request.Wrap("Copy", "objects", err)
		var zero0 *CopyHeader
		return zero0, err
	}
	_opts := copyOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Copy(ctx, a.client, containerName, objectName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Copy", "objects", err)
	return value0, err
}

type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateQuery(key, value string) CreateOption {
	return request.WithQuery[CreateOpts](key, value)
}
func WithCreateHeader(key, value string) CreateOption {
	return request.WithHeader[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToObjectCreateParams() (io.Reader, map[string]string, string, error) {
	value0, value1, value2, err := b.base.ToObjectCreateParams()
	if err != nil {
		var zero0 io.Reader
		var zero1 map[string]string
		var zero2 string
		return zero0, zero1, zero2, err
	}
	value1, err = request.MergeHeadersFor(value1, b.config.Headers, b.base)
	if err != nil {
		var zero0 io.Reader
		var zero1 map[string]string
		var zero2 string
		return zero0, zero1, zero2, err
	}
	value2, err = request.ExtendQuery(value2, b.config.Query)
	if err != nil {
		var zero0 io.Reader
		var zero1 map[string]string
		var zero2 string
		return zero0, zero1, zero2, err
	}
	return value0, value1, value2, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, containerName string, objectName string, opts CreateOpts, options ...CreateOption) (*CreateHeader, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "objects", err)
		var zero0 *CreateHeader
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, true); err != nil {
		err = request.Wrap("Create", "objects", err)
		var zero0 *CreateHeader
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, containerName, objectName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "objects", err)
	return value0, err
}

type CreateTempURLOption = request.Option[CreateTempURLOpts]

func WithCreateTempURLOptions(value CreateTempURLOpts) CreateTempURLOption {
	return request.WithOptions(value)
}

// CreateTempURL invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateTempURL(ctx context.Context, containerName string, objectName string, opts CreateTempURLOpts, options ...CreateTempURLOption) (string, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateTempURL", "objects", err)
		var zero0 string
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, false, false); err != nil {
		err = request.Wrap("CreateTempURL", "objects", err)
		var zero0 string
		return zero0, err
	}
	return upstream.CreateTempURL(ctx, a.client, containerName, objectName, cfg.Options)
}

type DeleteOption = request.Option[DeleteOpts]

func WithDeleteOptions(value DeleteOpts) DeleteOption { return request.WithOptions(value) }
func WithDeleteQuery(key, value string) DeleteOption {
	return request.WithQuery[DeleteOpts](key, value)
}

type deleteOptsBuilder struct {
	base   DeleteOpts
	config request.Config[DeleteOpts]
}

func (b deleteOptsBuilder) ToObjectDeleteQuery() (string, error) {
	value0, err := b.base.ToObjectDeleteQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, containerName string, objectName string, options ...DeleteOption) (*DeleteHeader, error) {
	var opts DeleteOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Delete", "objects", err)
		var zero0 *DeleteHeader
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("Delete", "objects", err)
		var zero0 *DeleteHeader
		return zero0, err
	}
	_opts := deleteOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Delete(ctx, a.client, containerName, objectName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Delete", "objects", err)
	return value0, err
}

type DownloadOption = request.Option[DownloadOpts]

func WithDownloadOptions(value DownloadOpts) DownloadOption { return request.WithOptions(value) }
func WithDownloadQuery(key, value string) DownloadOption {
	return request.WithQuery[DownloadOpts](key, value)
}
func WithDownloadHeader(key, value string) DownloadOption {
	return request.WithHeader[DownloadOpts](key, value)
}

type downloadOptsBuilder struct {
	base   DownloadOpts
	config request.Config[DownloadOpts]
}

func (b downloadOptsBuilder) ToObjectDownloadParams() (map[string]string, string, error) {
	value0, value1, err := b.base.ToObjectDownloadParams()
	if err != nil {
		var zero0 map[string]string
		var zero1 string
		return zero0, zero1, err
	}
	value0, err = request.MergeHeadersFor(value0, b.config.Headers, b.base)
	if err != nil {
		var zero0 map[string]string
		var zero1 string
		return zero0, zero1, err
	}
	value1, err = request.ExtendQuery(value1, b.config.Query)
	if err != nil {
		var zero0 map[string]string
		var zero1 string
		return zero0, zero1, err
	}
	return value0, value1, nil
}

// Download invokes the upstream API with library-owned builders and result handling.
func (a *API) Download(ctx context.Context, containerName string, objectName string, options ...DownloadOption) (*request.Download[*DownloadHeader], error) {
	var opts DownloadOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Download", "objects", err)
		return nil, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, true); err != nil {
		err = request.Wrap("Download", "objects", err)
		return nil, err
	}
	_opts := downloadOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Download(ctx, a.client, containerName, objectName, _opts)
	header, err := result.Extract()
	return request.OpenDownload(result.Body, header, request.Wrap("Download", "objects", err))
}

type GetOption = request.Option[GetOpts]

func WithGetOptions(value GetOpts) GetOption    { return request.WithOptions(value) }
func WithGetQuery(key, value string) GetOption  { return request.WithQuery[GetOpts](key, value) }
func WithGetHeader(key, value string) GetOption { return request.WithHeader[GetOpts](key, value) }

type getOptsBuilder struct {
	base   GetOpts
	config request.Config[GetOpts]
}

func (b getOptsBuilder) ToObjectGetParams() (map[string]string, string, error) {
	value0, value1, err := b.base.ToObjectGetParams()
	if err != nil {
		var zero0 map[string]string
		var zero1 string
		return zero0, zero1, err
	}
	value0, err = request.MergeHeadersFor(value0, b.config.Headers, b.base)
	if err != nil {
		var zero0 map[string]string
		var zero1 string
		return zero0, zero1, err
	}
	value1, err = request.ExtendQuery(value1, b.config.Query)
	if err != nil {
		var zero0 map[string]string
		var zero1 string
		return zero0, zero1, err
	}
	return value0, value1, nil
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, containerName string, objectName string, options ...GetOption) (*GetHeader, error) {
	var opts GetOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Get", "objects", err)
		var zero0 *GetHeader
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, true); err != nil {
		err = request.Wrap("Get", "objects", err)
		var zero0 *GetHeader
		return zero0, err
	}
	_opts := getOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Get(ctx, a.client, containerName, objectName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Get", "objects", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToObjectListParams() (string, error) {
	value0, err := b.base.ToObjectListParams()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, containerName string, options ...ListOption) iter.Seq2[*Object, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "objects", err)
		return func(yield func(*Object, error) bool) { var zero *Object; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "objects", err)
		return func(yield func(*Object, error) bool) { var zero *Object; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, containerName, _opts), func(page pagination.Page) ([]Object, error) {
		values, err := upstream.ExtractInfo(page)
		return []Object(values), err
	})
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateHeader(key, value string) UpdateOption {
	return request.WithHeader[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToObjectUpdateMap() (map[string]string, error) {
	value0, err := b.base.ToObjectUpdateMap()
	if err != nil {
		var zero0 map[string]string
		return zero0, err
	}
	value0, err = request.MergeHeadersFor(value0, b.config.Headers, b.base)
	if err != nil {
		var zero0 map[string]string
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, containerName string, objectName string, opts UpdateOpts, options ...UpdateOption) (*UpdateHeader, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "objects", err)
		var zero0 *UpdateHeader
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, false, true); err != nil {
		err = request.Wrap("Update", "objects", err)
		var zero0 *UpdateHeader
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, containerName, objectName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "objects", err)
	return value0, err
}
