// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package groups

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/groups"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type SecGroup = upstream.SecGroup
type SecGroupPage = upstream.SecGroupPage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToSecGroupCreateMap() (map[string]any, error) {
	body, err := b.base.ToSecGroupCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*SecGroup, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *SecGroup
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "groups", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "groups", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*SecGroup, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "groups", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption { return request.WithOptions(value) }

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*SecGroup, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*SecGroup, error) bool) { var zero *SecGroup; yield(zero, err) }
	}
	return resource.Stream(ctx, upstream.List(a.client, cfg.Options), func(page pagination.Page) ([]SecGroup, error) {
		values, err := upstream.ExtractGroups(page)
		return []SecGroup(values), err
	})
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToSecGroupUpdateMap() (map[string]any, error) {
	body, err := b.base.ToSecGroupUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*SecGroup, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *SecGroup
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "groups", err)
	return value0, err
}
