// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package claims

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/messaging/v2/claims"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type Claim = upstream.Claim
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type Messages = upstream.Messages
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}
func WithCreateQuery(key, value string) CreateOption {
	return request.WithQuery[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToClaimCreateRequest() (map[string]any, string, error) {
	value0, value1, err := b.base.ToClaimCreateRequest()
	if err != nil {
		var zero0 map[string]any
		var zero1 string
		return zero0, zero1, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		var zero1 string
		return zero0, zero1, err
	}
	value1, err = request.ExtendQuery(value1, b.config.Query)
	if err != nil {
		var zero0 map[string]any
		var zero1 string
		return zero0, zero1, err
	}
	return value0, value1, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, queueName string, opts CreateOpts, options ...CreateOption) ([]Messages, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "claims", err)
		var zero0 []Messages
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, true, false); err != nil {
		err = request.Wrap("Create", "claims", err)
		var zero0 []Messages
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, queueName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "claims", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, queueName string, claimID string) error {
	return request.Wrap("Delete", "claims", upstream.Delete(ctx, a.client, queueName, claimID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, queueName string, claimID string) (*Claim, error) {
	result := upstream.Get(ctx, a.client, queueName, claimID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "claims", err)
	return value0, err
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToClaimUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToClaimUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, queueName string, claimID string, opts UpdateOpts, options ...UpdateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "claims", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "claims", err)
		return err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Update", "claims", upstream.Update(ctx, a.client, queueName, claimID, _opts).ExtractErr())
}
