// Code generated by sdkgen; DO NOT EDIT.
package openstack

import (
	"context"
	service0 "github.com/JSYoo5B/go-openstacksdk/baremetal/v1"
	service1 "github.com/JSYoo5B/go-openstacksdk/baremetalintrospection/v1"
	service2 "github.com/JSYoo5B/go-openstacksdk/blockstorage/v2"
	service3 "github.com/JSYoo5B/go-openstacksdk/blockstorage/v3"
	service4 "github.com/JSYoo5B/go-openstacksdk/clustering/v1"
	service5 "github.com/JSYoo5B/go-openstacksdk/compute/v2"
	service6 "github.com/JSYoo5B/go-openstacksdk/container/v1"
	service7 "github.com/JSYoo5B/go-openstacksdk/containerinfra/v1"
	service8 "github.com/JSYoo5B/go-openstacksdk/db/v1"
	service9 "github.com/JSYoo5B/go-openstacksdk/dns/v2"
	service10 "github.com/JSYoo5B/go-openstacksdk/identity/v2"
	service11 "github.com/JSYoo5B/go-openstacksdk/identity/v3"
	service12 "github.com/JSYoo5B/go-openstacksdk/image/v2"
	service13 "github.com/JSYoo5B/go-openstacksdk/instanceha/v1"
	service14 "github.com/JSYoo5B/go-openstacksdk/keymanager/v1"
	service15 "github.com/JSYoo5B/go-openstacksdk/loadbalancer/v2"
	service16 "github.com/JSYoo5B/go-openstacksdk/messaging/v2"
	service17 "github.com/JSYoo5B/go-openstacksdk/metric/v1"
	service18 "github.com/JSYoo5B/go-openstacksdk/network/v2"
	service19 "github.com/JSYoo5B/go-openstacksdk/objectstorage/v1"
	service20 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1"
	service21 "github.com/JSYoo5B/go-openstacksdk/placement/v1"
	service22 "github.com/JSYoo5B/go-openstacksdk/reservation/v1"
	service23 "github.com/JSYoo5B/go-openstacksdk/sharedfilesystems/v2"
	service24 "github.com/JSYoo5B/go-openstacksdk/workflow/v2"
)

// BareMetalV1 returns a cached, authenticated baremetal/v1 API proxy.
func (c *Connection) BareMetalV1(ctx context.Context) (*service0.Service, error) {
	return cachedService(ctx, c, BareMetal, "v1", service0.New)
}
func (c *Connection) BareMetal(ctx context.Context) (*service0.Service, error) {
	return c.BareMetalV1(ctx)
}

// BareMetalIntrospectionV1 returns a cached, authenticated baremetalintrospection/v1 API proxy.
func (c *Connection) BareMetalIntrospectionV1(ctx context.Context) (*service1.Service, error) {
	return cachedService(ctx, c, BareMetalIntrospection, "v1", service1.New)
}
func (c *Connection) BareMetalIntrospection(ctx context.Context) (*service1.Service, error) {
	return c.BareMetalIntrospectionV1(ctx)
}

// BlockStorageV2 returns a cached, authenticated blockstorage/v2 API proxy.
func (c *Connection) BlockStorageV2(ctx context.Context) (*service2.Service, error) {
	return cachedService(ctx, c, BlockStorage, "v2", service2.New)
}

// BlockStorageV3 returns a cached, authenticated blockstorage/v3 API proxy.
func (c *Connection) BlockStorageV3(ctx context.Context) (*service3.Service, error) {
	return cachedService(ctx, c, BlockStorage, "v3", service3.New)
}

// ClusteringV1 returns a cached, authenticated clustering/v1 API proxy.
func (c *Connection) ClusteringV1(ctx context.Context) (*service4.Service, error) {
	return cachedService(ctx, c, Clustering, "v1", service4.New)
}
func (c *Connection) Clustering(ctx context.Context) (*service4.Service, error) {
	return c.ClusteringV1(ctx)
}

// ComputeV2 returns a cached, authenticated compute/v2 API proxy.
func (c *Connection) ComputeV2(ctx context.Context) (*service5.Service, error) {
	return cachedService(ctx, c, Compute, "v2", service5.New)
}

// ContainerV1 returns a cached, authenticated container/v1 API proxy.
func (c *Connection) ContainerV1(ctx context.Context) (*service6.Service, error) {
	return cachedService(ctx, c, Container, "v1", service6.New)
}
func (c *Connection) Container(ctx context.Context) (*service6.Service, error) {
	return c.ContainerV1(ctx)
}

// ContainerInfraV1 returns a cached, authenticated containerinfra/v1 API proxy.
func (c *Connection) ContainerInfraV1(ctx context.Context) (*service7.Service, error) {
	return cachedService(ctx, c, ContainerInfra, "v1", service7.New)
}
func (c *Connection) ContainerInfra(ctx context.Context) (*service7.Service, error) {
	return c.ContainerInfraV1(ctx)
}

// DatabaseV1 returns a cached, authenticated db/v1 API proxy.
func (c *Connection) DatabaseV1(ctx context.Context) (*service8.Service, error) {
	return cachedService(ctx, c, Database, "v1", service8.New)
}
func (c *Connection) Database(ctx context.Context) (*service8.Service, error) {
	return c.DatabaseV1(ctx)
}

// DNSV2 returns a cached, authenticated dns/v2 API proxy.
func (c *Connection) DNSV2(ctx context.Context) (*service9.Service, error) {
	return cachedService(ctx, c, DNS, "v2", service9.New)
}
func (c *Connection) DNS(ctx context.Context) (*service9.Service, error) { return c.DNSV2(ctx) }

// IdentityV2 returns a cached, authenticated identity/v2 API proxy.
func (c *Connection) IdentityV2(ctx context.Context) (*service10.Service, error) {
	return cachedService(ctx, c, Identity, "v2", service10.New)
}

// IdentityV3 returns a cached, authenticated identity/v3 API proxy.
func (c *Connection) IdentityV3(ctx context.Context) (*service11.Service, error) {
	return cachedService(ctx, c, Identity, "v3", service11.New)
}
func (c *Connection) Identity(ctx context.Context) (*service11.Service, error) {
	return c.IdentityV3(ctx)
}

// ImageV2 returns a cached, authenticated image/v2 API proxy.
func (c *Connection) ImageV2(ctx context.Context) (*service12.Service, error) {
	return cachedService(ctx, c, Image, "v2", service12.New)
}

// InstanceHAV1 returns a cached, authenticated instanceha/v1 API proxy.
func (c *Connection) InstanceHAV1(ctx context.Context) (*service13.Service, error) {
	return cachedService(ctx, c, InstanceHA, "v1", service13.New)
}
func (c *Connection) InstanceHA(ctx context.Context) (*service13.Service, error) {
	return c.InstanceHAV1(ctx)
}

// KeyManagerV1 returns a cached, authenticated keymanager/v1 API proxy.
func (c *Connection) KeyManagerV1(ctx context.Context) (*service14.Service, error) {
	return cachedService(ctx, c, KeyManager, "v1", service14.New)
}
func (c *Connection) KeyManager(ctx context.Context) (*service14.Service, error) {
	return c.KeyManagerV1(ctx)
}

// LoadBalancerV2 returns a cached, authenticated loadbalancer/v2 API proxy.
func (c *Connection) LoadBalancerV2(ctx context.Context) (*service15.Service, error) {
	return cachedService(ctx, c, LoadBalancer, "v2", service15.New)
}
func (c *Connection) LoadBalancer(ctx context.Context) (*service15.Service, error) {
	return c.LoadBalancerV2(ctx)
}

// MessagingV2 returns a cached, authenticated messaging/v2 API proxy.
func (c *Connection) MessagingV2(ctx context.Context) (*service16.Service, error) {
	return cachedService(ctx, c, Messaging, "v2", service16.New)
}
func (c *Connection) Messaging(ctx context.Context) (*service16.Service, error) {
	return c.MessagingV2(ctx)
}

// MetricV1 returns a cached, authenticated metric/v1 API proxy.
func (c *Connection) MetricV1(ctx context.Context) (*service17.Service, error) {
	return cachedService(ctx, c, Metric, "v1", service17.New)
}
func (c *Connection) Metric(ctx context.Context) (*service17.Service, error) { return c.MetricV1(ctx) }

// NetworkV2 returns a cached, authenticated network/v2 API proxy.
func (c *Connection) NetworkV2(ctx context.Context) (*service18.Service, error) {
	return cachedService(ctx, c, Network, "v2", service18.New)
}

// ObjectStorageV1 returns a cached, authenticated objectstorage/v1 API proxy.
func (c *Connection) ObjectStorageV1(ctx context.Context) (*service19.Service, error) {
	return cachedService(ctx, c, ObjectStorage, "v1", service19.New)
}
func (c *Connection) ObjectStorage(ctx context.Context) (*service19.Service, error) {
	return c.ObjectStorageV1(ctx)
}

// OrchestrationV1 returns a cached, authenticated orchestration/v1 API proxy.
func (c *Connection) OrchestrationV1(ctx context.Context) (*service20.Service, error) {
	return cachedService(ctx, c, Orchestration, "v1", service20.New)
}
func (c *Connection) Orchestration(ctx context.Context) (*service20.Service, error) {
	return c.OrchestrationV1(ctx)
}

// PlacementV1 returns a cached, authenticated placement/v1 API proxy.
func (c *Connection) PlacementV1(ctx context.Context) (*service21.Service, error) {
	return cachedService(ctx, c, Placement, "v1", service21.New)
}
func (c *Connection) Placement(ctx context.Context) (*service21.Service, error) {
	return c.PlacementV1(ctx)
}

// ReservationV1 returns a cached, authenticated reservation/v1 API proxy.
func (c *Connection) ReservationV1(ctx context.Context) (*service22.Service, error) {
	return cachedService(ctx, c, Reservation, "v1", service22.New)
}
func (c *Connection) Reservation(ctx context.Context) (*service22.Service, error) {
	return c.ReservationV1(ctx)
}

// SharedFileSystemV2 returns a cached, authenticated sharedfilesystems/v2 API proxy.
func (c *Connection) SharedFileSystemV2(ctx context.Context) (*service23.Service, error) {
	return cachedService(ctx, c, SharedFileSystem, "v2", service23.New)
}
func (c *Connection) SharedFileSystem(ctx context.Context) (*service23.Service, error) {
	return c.SharedFileSystemV2(ctx)
}

// WorkflowV2 returns a cached, authenticated workflow/v2 API proxy.
func (c *Connection) WorkflowV2(ctx context.Context) (*service24.Service, error) {
	return cachedService(ctx, c, Workflow, "v2", service24.New)
}
func (c *Connection) Workflow(ctx context.Context) (*service24.Service, error) {
	return c.WorkflowV2(ctx)
}
