// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package qos

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/qos"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[QoS]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AssociateOpts = upstream.AssociateOpts
type AssociateResult = upstream.AssociateResult
type AssociationPage = upstream.AssociationPage

const ConsumerBack = upstream.ConsumerBack
const ConsumerBoth = upstream.ConsumerBoth
const ConsumerFront = upstream.ConsumerFront

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteKeysOpts = upstream.DeleteKeysOpts
type DeleteOpts = upstream.DeleteOpts
type DeleteResult = upstream.DeleteResult
type DisassociateAllResult = upstream.DisassociateAllResult
type DisassociateOpts = upstream.DisassociateOpts
type DisassociateResult = upstream.DisassociateResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type QoS = upstream.QoS
type QoSConsumer = upstream.QoSConsumer
type QoSPage = upstream.QoSPage
type QosAssociation = upstream.QosAssociation
type UpdateOpts = upstream.UpdateOpts
type AssociateOption = request.Option[AssociateOpts]

func WithAssociateOptions(value AssociateOpts) AssociateOption { return request.WithOptions(value) }
func WithAssociateQuery(key, value string) AssociateOption {
	return request.WithQuery[AssociateOpts](key, value)
}

type associateOptsBuilder struct {
	base   AssociateOpts
	config request.Config[AssociateOpts]
}

func (b associateOptsBuilder) ToQosAssociateQuery() (string, error) {
	query, err := b.base.ToQosAssociateQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// Associate invokes the upstream API with library-owned builders and result handling.
func (a *API) Associate(ctx context.Context, qosID string, opts AssociateOpts, options ...AssociateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := associateOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Associate", "qos", upstream.Associate(ctx, a.client, qosID, _opts).ExtractErr())
}

type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToQoSCreateMap() (map[string]any, error) {
	body, err := b.base.ToQoSCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*QoS, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *QoS
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "qos", err)
	return value0, err
}

type DeleteOption = request.Option[DeleteOpts]

func WithDeleteOptions(value DeleteOpts) DeleteOption { return request.WithOptions(value) }
func WithDeleteQuery(key, value string) DeleteOption {
	return request.WithQuery[DeleteOpts](key, value)
}

type deleteOptsBuilder struct {
	base   DeleteOpts
	config request.Config[DeleteOpts]
}

func (b deleteOptsBuilder) ToQoSDeleteQuery() (string, error) {
	query, err := b.base.ToQoSDeleteQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string, options ...DeleteOption) error {
	var opts DeleteOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := deleteOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Delete", "qos", upstream.Delete(ctx, a.client, id, _opts).ExtractErr())
}

type DeleteKeysOption = request.Option[DeleteKeysOpts]

func WithDeleteKeysOptions(value DeleteKeysOpts) DeleteKeysOption { return request.WithOptions(value) }
func WithDeleteKeysField(key string, value any) DeleteKeysOption {
	return request.WithField[DeleteKeysOpts](key, value)
}

type deleteKeysOptsBuilder struct {
	base   DeleteKeysOpts
	config request.Config[DeleteKeysOpts]
}

func (b deleteKeysOptsBuilder) ToDeleteKeysCreateMap() (map[string]any, error) {
	body, err := b.base.ToDeleteKeysCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// DeleteKeys invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteKeys(ctx context.Context, qosID string, options ...DeleteKeysOption) error {
	var opts DeleteKeysOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := deleteKeysOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("DeleteKeys", "qos", upstream.DeleteKeys(ctx, a.client, qosID, _opts).ExtractErr())
}

type DisassociateOption = request.Option[DisassociateOpts]

func WithDisassociateOptions(value DisassociateOpts) DisassociateOption {
	return request.WithOptions(value)
}
func WithDisassociateQuery(key, value string) DisassociateOption {
	return request.WithQuery[DisassociateOpts](key, value)
}

type disassociateOptsBuilder struct {
	base   DisassociateOpts
	config request.Config[DisassociateOpts]
}

func (b disassociateOptsBuilder) ToQosDisassociateQuery() (string, error) {
	query, err := b.base.ToQosDisassociateQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// Disassociate invokes the upstream API with library-owned builders and result handling.
func (a *API) Disassociate(ctx context.Context, qosID string, opts DisassociateOpts, options ...DisassociateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := disassociateOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Disassociate", "qos", upstream.Disassociate(ctx, a.client, qosID, _opts).ExtractErr())
}

// DisassociateAll invokes the upstream API with library-owned builders and result handling.
func (a *API) DisassociateAll(ctx context.Context, qosID string) error {
	return request.Wrap("DisassociateAll", "qos", upstream.DisassociateAll(ctx, a.client, qosID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*QoS, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "qos", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToQoSListQuery() (string, error) {
	query, err := b.base.ToQoSListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*QoS, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*QoS, error) bool) { var zero *QoS; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]QoS, error) {
		values, err := upstream.ExtractQoS(page)
		return []QoS(values), err
	})
}

// ListAssociations invokes the upstream API with library-owned builders and result handling.
func (a *API) ListAssociations(ctx context.Context, qosID string) iter.Seq2[*QosAssociation, error] {
	return resource.Stream(ctx, upstream.ListAssociations(a.client, qosID), func(page pagination.Page) ([]QosAssociation, error) {
		values, err := upstream.ExtractAssociations(page)
		return []QosAssociation(values), err
	})
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToQoSUpdateMap() (map[string]any, error) {
	body, err := b.base.ToQoSUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (map[string]string, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 map[string]string
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "qos", err)
	return value0, err
}
