// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package subnets

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/subnets"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[Subnet]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AllocationPool = upstream.AllocationPool
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type HostRoute = upstream.HostRoute
type ListOpts = upstream.ListOpts
type Subnet = upstream.Subnet
type SubnetPage = upstream.SubnetPage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToSubnetCreateMap() (map[string]any, error) {
	value0, err := b.base.ToSubnetCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Subnet, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "subnets", err)
		var zero0 *Subnet
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "subnets", err)
		var zero0 *Subnet
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "subnets", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "subnets", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Subnet, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "subnets", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToSubnetListQuery() (string, error) {
	value0, err := b.base.ToSubnetListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Subnet, error] {
	return a.listWithControl(ctx, resource.ListControl{}, options...)
}

func (a *API) listWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*Subnet, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "subnets", err)
		return func(yield func(*Subnet, error) bool) { var zero *Subnet; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "subnets", err)
		return func(yield func(*Subnet, error) bool) { var zero *Subnet; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.StreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Subnet, error) {
		values, err := upstream.ExtractSubnets(page)
		return []Subnet(values), err
	}, control)
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base           UpdateOpts
	config         request.Config[UpdateOpts]
	RevisionNumber *int "json:\"-\" h:\"If-Match\""
}

func (b updateOptsBuilder) ToSubnetUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToSubnetUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Subnet, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "subnets", err)
		var zero0 *Subnet
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "subnets", err)
		var zero0 *Subnet
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg, RevisionNumber: cfg.Options.RevisionNumber}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "subnets", err)
	return value0, err
}
