// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package subnets

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/subnets"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	nativefind "gophercloudsdk/internal/nativefind"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Subnet] {
	return resource.NewCollection(resource.Adapter[Subnet]{
		Kind:             "subnets",
		BodyFilterFields: map[string]string{"allocation_pools": "allocation_pools", "created_at": "created_at", "dns_nameservers": "dns_nameservers", "host_routes": "host_routes", "prefixlen": "prefixlen", "prefix_length": "prefixlen", "revision_number": "revision_number", "service_types": "service_types", "tenant_id": "tenant_id", "updated_at": "updated_at"},
		BodyFilterRecordValue: func(record *resource.BodyRecord[Subnet], key string) (json.RawMessage, error) {
			if record == nil {
				return nil, fmt.Errorf("%w: nil body filter record", resource.ErrInvalidOption)
			}
			switch key {
			case "revision_number":
				return resource.BodyRecordField(record.Fields, key, resource.BodyFieldInteger)
			case "allocation_pools", "created_at", "dns_nameservers", "host_routes", "prefixlen", "service_types", "tenant_id", "updated_at":
				return resource.BodyRecordField(record.Fields, key, resource.BodyFieldJSON)
			default:
				return nil, fmt.Errorf("%w: unsupported body filter field %q", resource.ErrInvalidOption, key)
			}
		},
		IterateBodyControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*resource.BodyRecord[Subnet], error] {
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listBodyWithControl(ctx, control, options...)
		},
		FilterDescriptor: &resource.FilterDescriptor{Query: map[string]string{"any_tags": "tags-any", "cidr": "cidr", "description": "description", "dns_publish_fixed_ip": "dns_publish_fixed_ip", "fields": "fields", "gateway_ip": "gateway_ip", "id": "id", "ip_version": "ip_version", "ipv6_address_mode": "ipv6_address_mode", "ipv6_ra_mode": "ipv6_ra_mode", "is_dhcp_enabled": "enable_dhcp", "limit": "limit", "marker": "marker", "name": "name", "network_id": "network_id", "not_any_tags": "not-tags-any", "not_tags": "not-tags", "project_id": "project_id", "segment_id": "segment_id", "sort_dir": "sort_dir", "sort_key": "sort_key", "subnet_pool_id": "subnetpool_id", "tags": "tags", "use_default_subnet_pool": "use_default_subnetpool"}, Body: map[string]string{"allocation_pools": "allocation_pools", "created_at": "created_at", "dns_nameservers": "dns_nameservers", "host_routes": "host_routes", "prefix_length": "prefixlen", "revision_number": "revision_number", "service_types": "service_types", "tenant_id": "tenant_id", "updated_at": "updated_at"}, Reserved: []string{"allow_unknown_params", "base_path", "headers", "jmespath_filters", "max_items", "microversion", "paginated", "resource_type", "session"}},
		IdentityFind:     true,
		GetIdentityQuery: func(ctx context.Context, id string, q url.Values) (*Subnet, error) {
			var result upstream.GetResult
			result.Header, result.Err = nativefind.Get(ctx, a.RawClient(), []string{"subnets", id}, q, []int{200}, &result.Body)
			return result.Extract()
		},
		Get:       func(ctx context.Context, id string) (*Subnet, error) { return a.Get(ctx, string(id)) },
		ID:        func(v *Subnet) string { return fmt.Sprint(v.ID) },
		Name:      func(v *Subnet) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Delete:    func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Subnet, error] {
			q = maps.Clone(q)
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) listBodyWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*resource.BodyRecord[Subnet], error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err == nil {
		err = request.ValidateCapabilities(cfg, false, true, false)
	}
	if err != nil {
		err = request.Wrap("List", "subnets", err)
		return func(yield func(*resource.BodyRecord[Subnet], error) bool) { yield(nil, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.BodyStreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Subnet, error) {
		values, err := upstream.ExtractSubnets(page)
		return []Subnet(values), err
	}, "subnets", control)
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Subnet, error) {
	return a.Resources.Find(ctx, ref, options...)
}

// FindIdentity tries an ID request before exact ID/name fallback within this collection.
func (a *API) FindIdentity(ctx context.Context, identity string, options ...resource.IdentityFindOption) (*Subnet, error) {
	return a.Resources.FindIdentity(ctx, identity, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Subnet, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Subnet, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
