// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package nodes

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/baremetal/v1/nodes"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

const Active = upstream.Active
const AddOp = upstream.AddOp
const AdoptFail = upstream.AdoptFail
const Adopting = upstream.Adopting

type AttachVirtualMediaOpts = upstream.AttachVirtualMediaOpts

const Available = upstream.Available

type BIOSSetting = upstream.BIOSSetting
type BootDeviceOpts = upstream.BootDeviceOpts
type BootDeviceResult = upstream.BootDeviceResult
type CallVendorPassthruOpts = upstream.CallVendorPassthruOpts
type CallVendorPassthruResult = upstream.CallVendorPassthruResult
type ChangePowerStateResult = upstream.ChangePowerStateResult
type ChangeStateResult = upstream.ChangeStateResult

const CleanFail = upstream.CleanFail
const CleanHold = upstream.CleanHold

type CleanStep = upstream.CleanStep

const CleanWait = upstream.CleanWait
const Cleaning = upstream.Cleaning

type ConfigDrive = upstream.ConfigDrive
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type CreateSubscriptionMethod = upstream.CreateSubscriptionMethod
type CreateSubscriptionOpts = upstream.CreateSubscriptionOpts
type DeleteResult = upstream.DeleteResult
type DeleteSubscriptionMethod = upstream.DeleteSubscriptionMethod
type DeleteSubscriptionOpts = upstream.DeleteSubscriptionOpts
type DeleteSubscriptionVendorPassthruResult = upstream.DeleteSubscriptionVendorPassthruResult

const Deleted = upstream.Deleted
const Deleting = upstream.Deleting
const DeployDone = upstream.DeployDone
const DeployFail = upstream.DeployFail
const DeployHold = upstream.DeployHold

type DeployStep = upstream.DeployStep

const DeployWait = upstream.DeployWait
const Deploying = upstream.Deploying

type DetachVirtualMediaOpts = upstream.DetachVirtualMediaOpts
type DiskType = upstream.DiskType
type DriverValidation = upstream.DriverValidation

const Enroll = upstream.Enroll
const Error = upstream.Error

type FirmwareComponent = upstream.FirmwareComponent
type GetAllSubscriptionsMethod = upstream.GetAllSubscriptionsMethod
type GetAllSubscriptionsVendorPassthru = upstream.GetAllSubscriptionsVendorPassthru
type GetAllSubscriptionsVendorPassthruResult = upstream.GetAllSubscriptionsVendorPassthruResult
type GetBIOSSettingResult = upstream.GetBIOSSettingResult
type GetResult = upstream.GetResult
type GetSubscriptionMethod = upstream.GetSubscriptionMethod
type GetSubscriptionOpts = upstream.GetSubscriptionOpts

const HDD = upstream.HDD

type ImageDownloadSource = upstream.ImageDownloadSource

const ImageDownloadSourceHTTP = upstream.ImageDownloadSourceHTTP
const ImageDownloadSourceLocal = upstream.ImageDownloadSourceLocal
const ImageDownloadSourceSwift = upstream.ImageDownloadSourceSwift

type InjectNMIResult = upstream.InjectNMIResult

const InspectFail = upstream.InspectFail
const InspectWait = upstream.InspectWait
const Inspecting = upstream.Inspecting
const InterfaceBIOS = upstream.InterfaceBIOS
const InterfaceDeploy = upstream.InterfaceDeploy
const InterfaceFirmware = upstream.InterfaceFirmware
const InterfaceManagement = upstream.InterfaceManagement
const InterfacePower = upstream.InterfacePower
const InterfaceRAID = upstream.InterfaceRAID

type InterfaceType = upstream.InterfaceType
type InventoryData = upstream.InventoryData
type InventoryResult = upstream.InventoryResult

const JBOD = upstream.JBOD

type Link = upstream.Link
type ListBIOSSettingsOpts = upstream.ListBIOSSettingsOpts
type ListBIOSSettingsResult = upstream.ListBIOSSettingsResult
type ListFirmwareResult = upstream.ListFirmwareResult
type ListOpts = upstream.ListOpts
type ListVendorPassthruMethodsResult = upstream.ListVendorPassthruMethodsResult
type ListVirtualInterfacesResult = upstream.ListVirtualInterfacesResult
type LogicalDisk = upstream.LogicalDisk
type MaintenanceOpts = upstream.MaintenanceOpts

const Manageable = upstream.Manageable

type Node = upstream.Node
type NodePage = upstream.NodePage
type NodeValidation = upstream.NodeValidation
type Patch = upstream.Patch
type PluginData = upstream.PluginData

const PowerOff = upstream.PowerOff
const PowerOn = upstream.PowerOn

type PowerStateOpts = upstream.PowerStateOpts
type ProvisionState = upstream.ProvisionState
type ProvisionStateOpts = upstream.ProvisionStateOpts

const RAID0 = upstream.RAID0
const RAID1 = upstream.RAID1
const RAID10 = upstream.RAID10
const RAID2 = upstream.RAID2
const RAID5 = upstream.RAID5
const RAID50 = upstream.RAID50
const RAID6 = upstream.RAID6
const RAID60 = upstream.RAID60

type RAIDConfigOpts = upstream.RAIDConfigOpts
type RAIDLevel = upstream.RAIDLevel

const Rebooting = upstream.Rebooting
const Rebuild = upstream.Rebuild
const RemoveOp = upstream.RemoveOp
const ReplaceOp = upstream.ReplaceOp
const Rescue = upstream.Rescue
const RescueFail = upstream.RescueFail
const RescueWait = upstream.RescueWait
const Rescuing = upstream.Rescuing
const SAS = upstream.SAS
const SATA = upstream.SATA
const SCSI = upstream.SCSI
const SSD = upstream.SSD
const ServiceFail = upstream.ServiceFail
const ServiceHold = upstream.ServiceHold

type ServiceStep = upstream.ServiceStep

const ServiceWait = upstream.ServiceWait
const Servicing = upstream.Servicing

type SetBootDeviceResult = upstream.SetBootDeviceResult
type SetMaintenanceResult = upstream.SetMaintenanceResult
type SingleBIOSSetting = upstream.SingleBIOSSetting

const SoftPowerOff = upstream.SoftPowerOff
const SoftRebooting = upstream.SoftRebooting
const StepHold = upstream.StepHold

type StepInterface = upstream.StepInterface

const StepPowerOff = upstream.StepPowerOff
const StepPowerOn = upstream.StepPowerOn
const StepReboot = upstream.StepReboot
const StepWait = upstream.StepWait

type SubscriptionVendorPassthru = upstream.SubscriptionVendorPassthru
type SubscriptionVendorPassthruResult = upstream.SubscriptionVendorPassthruResult
type SupportedBootDeviceResult = upstream.SupportedBootDeviceResult

const TargetAbort = upstream.TargetAbort
const TargetActive = upstream.TargetActive
const TargetAdopt = upstream.TargetAdopt
const TargetClean = upstream.TargetClean
const TargetDeleted = upstream.TargetDeleted
const TargetInspect = upstream.TargetInspect
const TargetManage = upstream.TargetManage

type TargetPowerState = upstream.TargetPowerState

const TargetProvide = upstream.TargetProvide

type TargetProvisionState = upstream.TargetProvisionState

const TargetRebuild = upstream.TargetRebuild
const TargetRescue = upstream.TargetRescue
const TargetService = upstream.TargetService
const TargetUnhold = upstream.TargetUnhold
const TargetUnrescue = upstream.TargetUnrescue
const UnrescueFail = upstream.UnrescueFail
const Unrescuing = upstream.Unrescuing

type UpdateOp = upstream.UpdateOp
type UpdateOperation = upstream.UpdateOperation
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type VIF = upstream.VIF
type ValidateResult = upstream.ValidateResult
type VendorPassthruCallOpts = upstream.VendorPassthruCallOpts
type VendorPassthruMethod = upstream.VendorPassthruMethod
type VendorPassthruMethods = upstream.VendorPassthruMethods
type VendorPassthruMethodsResult = upstream.VendorPassthruMethodsResult

const Verifying = upstream.Verifying

type VirtualInterfaceAttachResult = upstream.VirtualInterfaceAttachResult
type VirtualInterfaceDetachResult = upstream.VirtualInterfaceDetachResult
type VirtualInterfaceOpts = upstream.VirtualInterfaceOpts
type VirtualMediaAttachResult = upstream.VirtualMediaAttachResult

const VirtualMediaCD = upstream.VirtualMediaCD

type VirtualMediaDetachResult = upstream.VirtualMediaDetachResult
type VirtualMediaDeviceType = upstream.VirtualMediaDeviceType

const VirtualMediaDisk = upstream.VirtualMediaDisk
const VirtualMediaFloppy = upstream.VirtualMediaFloppy

type VirtualMediaGetResult = upstream.VirtualMediaGetResult
type AttachVirtualInterfaceOption = request.Option[VirtualInterfaceOpts]

func WithAttachVirtualInterfaceOptions(value VirtualInterfaceOpts) AttachVirtualInterfaceOption {
	return request.WithOptions(value)
}
func WithAttachVirtualInterfaceField(key string, value any) AttachVirtualInterfaceOption {
	return request.WithField[VirtualInterfaceOpts](key, value)
}

type attachVirtualInterfaceOptsBuilder struct {
	base   VirtualInterfaceOpts
	config request.Config[VirtualInterfaceOpts]
}

func (b attachVirtualInterfaceOptsBuilder) ToVirtualInterfaceMap() (map[string]any, error) {
	body, err := b.base.ToVirtualInterfaceMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// AttachVirtualInterface invokes the upstream API with library-owned builders and result handling.
func (a *API) AttachVirtualInterface(ctx context.Context, id string, opts VirtualInterfaceOpts, options ...AttachVirtualInterfaceOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := attachVirtualInterfaceOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("AttachVirtualInterface", "nodes", upstream.AttachVirtualInterface(ctx, a.client, id, _opts).ExtractErr())
}

type AttachVirtualMediaOption = request.Option[AttachVirtualMediaOpts]

func WithAttachVirtualMediaOptions(value AttachVirtualMediaOpts) AttachVirtualMediaOption {
	return request.WithOptions(value)
}
func WithAttachVirtualMediaField(key string, value any) AttachVirtualMediaOption {
	return request.WithField[AttachVirtualMediaOpts](key, value)
}

type attachVirtualMediaOptsBuilder struct {
	base   AttachVirtualMediaOpts
	config request.Config[AttachVirtualMediaOpts]
}

func (b attachVirtualMediaOptsBuilder) ToAttachVirtualMediaMap() (map[string]any, error) {
	body, err := b.base.ToAttachVirtualMediaMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// AttachVirtualMedia invokes the upstream API with library-owned builders and result handling.
func (a *API) AttachVirtualMedia(ctx context.Context, id string, opts AttachVirtualMediaOpts, options ...AttachVirtualMediaOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := attachVirtualMediaOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("AttachVirtualMedia", "nodes", upstream.AttachVirtualMedia(ctx, a.client, id, _opts).ExtractErr())
}

type CallVendorPassthruOption = request.Option[VendorPassthruCallOpts]

func WithCallVendorPassthruOptions(value VendorPassthruCallOpts) CallVendorPassthruOption {
	return request.WithOptions(value)
}

// CallVendorPassthru invokes the upstream API with library-owned builders and result handling.
func (a *API) CallVendorPassthru(ctx context.Context, id string, httpMethod string, opts VendorPassthruCallOpts, options ...CallVendorPassthruOption) (map[string]any, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	result := upstream.CallVendorPassthru(ctx, a.client, id, httpMethod, cfg.Options)
	value0, err := result.Extract()
	err = request.Wrap("CallVendorPassthru", "nodes", err)
	return value0, err
}

type ChangePowerStateOption = request.Option[PowerStateOpts]

func WithChangePowerStateOptions(value PowerStateOpts) ChangePowerStateOption {
	return request.WithOptions(value)
}
func WithChangePowerStateField(key string, value any) ChangePowerStateOption {
	return request.WithField[PowerStateOpts](key, value)
}

type changePowerStateOptsBuilder struct {
	base   PowerStateOpts
	config request.Config[PowerStateOpts]
}

func (b changePowerStateOptsBuilder) ToPowerStateMap() (map[string]any, error) {
	body, err := b.base.ToPowerStateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// ChangePowerState invokes the upstream API with library-owned builders and result handling.
func (a *API) ChangePowerState(ctx context.Context, id string, opts PowerStateOpts, options ...ChangePowerStateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := changePowerStateOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("ChangePowerState", "nodes", upstream.ChangePowerState(ctx, a.client, id, _opts).ExtractErr())
}

type ChangeProvisionStateOption = request.Option[ProvisionStateOpts]

func WithChangeProvisionStateOptions(value ProvisionStateOpts) ChangeProvisionStateOption {
	return request.WithOptions(value)
}
func WithChangeProvisionStateField(key string, value any) ChangeProvisionStateOption {
	return request.WithField[ProvisionStateOpts](key, value)
}

type changeProvisionStateOptsBuilder struct {
	base   ProvisionStateOpts
	config request.Config[ProvisionStateOpts]
}

func (b changeProvisionStateOptsBuilder) ToProvisionStateMap() (map[string]any, error) {
	body, err := b.base.ToProvisionStateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// ChangeProvisionState invokes the upstream API with library-owned builders and result handling.
func (a *API) ChangeProvisionState(ctx context.Context, id string, opts ProvisionStateOpts, options ...ChangeProvisionStateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := changeProvisionStateOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("ChangeProvisionState", "nodes", upstream.ChangeProvisionState(ctx, a.client, id, _opts).ExtractErr())
}

type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToNodeCreateMap() (map[string]any, error) {
	body, err := b.base.ToNodeCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Node, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Node
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "nodes", err)
	return value0, err
}

type CreateSubscriptionOption = request.Option[CallVendorPassthruOpts]

func WithCreateSubscriptionOptions(value CallVendorPassthruOpts) CreateSubscriptionOption {
	return request.WithOptions(value)
}

// CreateSubscription invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateSubscription(ctx context.Context, id string, method CallVendorPassthruOpts, subscriptionOpts CreateSubscriptionOpts, options ...CreateSubscriptionOption) (*SubscriptionVendorPassthru, error) {
	cfg, err := request.Apply(method, options...)
	if err != nil {
		var zero0 *SubscriptionVendorPassthru
		return zero0, err
	}
	result := upstream.CreateSubscription(ctx, a.client, id, cfg.Options, subscriptionOpts)
	value0, err := result.Extract()
	err = request.Wrap("CreateSubscription", "nodes", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "nodes", upstream.Delete(ctx, a.client, id).ExtractErr())
}

type DeleteSubscriptionOption = request.Option[CallVendorPassthruOpts]

func WithDeleteSubscriptionOptions(value CallVendorPassthruOpts) DeleteSubscriptionOption {
	return request.WithOptions(value)
}

// DeleteSubscription invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteSubscription(ctx context.Context, id string, subscriptionOpts DeleteSubscriptionOpts, options ...DeleteSubscriptionOption) error {
	var method CallVendorPassthruOpts
	cfg, err := request.Apply(method, options...)
	if err != nil {
		return err
	}
	return request.Wrap("DeleteSubscription", "nodes", upstream.DeleteSubscription(ctx, a.client, id, cfg.Options, subscriptionOpts).ExtractErr())
}

// DetachVirtualInterface invokes the upstream API with library-owned builders and result handling.
func (a *API) DetachVirtualInterface(ctx context.Context, id string, vifID string) error {
	return request.Wrap("DetachVirtualInterface", "nodes", upstream.DetachVirtualInterface(ctx, a.client, id, vifID).ExtractErr())
}

type DetachVirtualMediaOption = request.Option[DetachVirtualMediaOpts]

func WithDetachVirtualMediaOptions(value DetachVirtualMediaOpts) DetachVirtualMediaOption {
	return request.WithOptions(value)
}
func WithDetachVirtualMediaQuery(key, value string) DetachVirtualMediaOption {
	return request.WithQuery[DetachVirtualMediaOpts](key, value)
}

type detachVirtualMediaOptsBuilder struct {
	base   DetachVirtualMediaOpts
	config request.Config[DetachVirtualMediaOpts]
}

func (b detachVirtualMediaOptsBuilder) ToDetachVirtualMediaOptsQuery() (string, error) {
	query, err := b.base.ToDetachVirtualMediaOptsQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// DetachVirtualMedia invokes the upstream API with library-owned builders and result handling.
func (a *API) DetachVirtualMedia(ctx context.Context, id string, opts DetachVirtualMediaOpts, options ...DetachVirtualMediaOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := detachVirtualMediaOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("DetachVirtualMedia", "nodes", upstream.DetachVirtualMedia(ctx, a.client, id, _opts).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Node, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "nodes", err)
	return value0, err
}

type GetAllSubscriptionsOption = request.Option[CallVendorPassthruOpts]

func WithGetAllSubscriptionsOptions(value CallVendorPassthruOpts) GetAllSubscriptionsOption {
	return request.WithOptions(value)
}

// GetAllSubscriptions invokes the upstream API with library-owned builders and result handling.
func (a *API) GetAllSubscriptions(ctx context.Context, id string, options ...GetAllSubscriptionsOption) (*GetAllSubscriptionsVendorPassthru, error) {
	var method CallVendorPassthruOpts
	cfg, err := request.Apply(method, options...)
	if err != nil {
		var zero0 *GetAllSubscriptionsVendorPassthru
		return zero0, err
	}
	result := upstream.GetAllSubscriptions(ctx, a.client, id, cfg.Options)
	value0, err := result.Extract()
	err = request.Wrap("GetAllSubscriptions", "nodes", err)
	return value0, err
}

// GetBIOSSetting invokes the upstream API with library-owned builders and result handling.
func (a *API) GetBIOSSetting(ctx context.Context, id string, setting string) (*BIOSSetting, error) {
	result := upstream.GetBIOSSetting(ctx, a.client, id, setting)
	value0, err := result.Extract()
	err = request.Wrap("GetBIOSSetting", "nodes", err)
	return value0, err
}

// GetBootDevice invokes the upstream API with library-owned builders and result handling.
func (a *API) GetBootDevice(ctx context.Context, id string) (*BootDeviceOpts, error) {
	result := upstream.GetBootDevice(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("GetBootDevice", "nodes", err)
	return value0, err
}

// GetInventory invokes the upstream API with library-owned builders and result handling.
func (a *API) GetInventory(ctx context.Context, id string) (*InventoryData, error) {
	result := upstream.GetInventory(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("GetInventory", "nodes", err)
	return value0, err
}

type GetSubscriptionOption = request.Option[CallVendorPassthruOpts]

func WithGetSubscriptionOptions(value CallVendorPassthruOpts) GetSubscriptionOption {
	return request.WithOptions(value)
}

// GetSubscription invokes the upstream API with library-owned builders and result handling.
func (a *API) GetSubscription(ctx context.Context, id string, subscriptionOpts GetSubscriptionOpts, options ...GetSubscriptionOption) (*SubscriptionVendorPassthru, error) {
	var method CallVendorPassthruOpts
	cfg, err := request.Apply(method, options...)
	if err != nil {
		var zero0 *SubscriptionVendorPassthru
		return zero0, err
	}
	result := upstream.GetSubscription(ctx, a.client, id, cfg.Options, subscriptionOpts)
	value0, err := result.Extract()
	err = request.Wrap("GetSubscription", "nodes", err)
	return value0, err
}

// GetSupportedBootDevices invokes the upstream API with library-owned builders and result handling.
func (a *API) GetSupportedBootDevices(ctx context.Context, id string) ([]string, error) {
	result := upstream.GetSupportedBootDevices(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("GetSupportedBootDevices", "nodes", err)
	return value0, err
}

// GetVendorPassthruMethods invokes the upstream API with library-owned builders and result handling.
func (a *API) GetVendorPassthruMethods(ctx context.Context, id string) (*VendorPassthruMethods, error) {
	result := upstream.GetVendorPassthruMethods(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("GetVendorPassthruMethods", "nodes", err)
	return value0, err
}

// GetVirtualMedia invokes the upstream API with library-owned builders and result handling.
func (a *API) GetVirtualMedia(ctx context.Context, id string) (VirtualMediaGetResult, error) {
	result := upstream.GetVirtualMedia(ctx, a.client, id)
	return result, request.Wrap("GetVirtualMedia", "nodes", result.Err)
}

// InjectNMI invokes the upstream API with library-owned builders and result handling.
func (a *API) InjectNMI(ctx context.Context, id string) error {
	return request.Wrap("InjectNMI", "nodes", upstream.InjectNMI(ctx, a.client, id).ExtractErr())
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToNodeListDetailQuery() (string, error) {
	query, err := b.base.ToNodeListDetailQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}
func (b listOptsBuilder) ToNodeListQuery() (string, error) {
	query, err := b.base.ToNodeListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Node, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*Node, error) bool) { var zero *Node; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Node, error) {
		values, err := upstream.ExtractNodes(page)
		return []Node(values), err
	})
}

type ListBIOSSettingsOption = request.Option[ListBIOSSettingsOpts]

func WithListBIOSSettingsOptions(value ListBIOSSettingsOpts) ListBIOSSettingsOption {
	return request.WithOptions(value)
}
func WithListBIOSSettingsQuery(key, value string) ListBIOSSettingsOption {
	return request.WithQuery[ListBIOSSettingsOpts](key, value)
}

type listBIOSSettingsOptsBuilder struct {
	base   ListBIOSSettingsOpts
	config request.Config[ListBIOSSettingsOpts]
}

func (b listBIOSSettingsOptsBuilder) ToListBIOSSettingsOptsQuery() (string, error) {
	query, err := b.base.ToListBIOSSettingsOptsQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// ListBIOSSettings invokes the upstream API with library-owned builders and result handling.
func (a *API) ListBIOSSettings(ctx context.Context, id string, options ...ListBIOSSettingsOption) ([]BIOSSetting, error) {
	var opts ListBIOSSettingsOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 []BIOSSetting
		return zero0, err
	}
	_opts := listBIOSSettingsOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.ListBIOSSettings(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("ListBIOSSettings", "nodes", err)
	return value0, err
}

type ListDetailOption = request.Option[ListOpts]

func WithListDetailOptions(value ListOpts) ListDetailOption { return request.WithOptions(value) }
func WithListDetailQuery(key, value string) ListDetailOption {
	return request.WithQuery[ListOpts](key, value)
}

type listDetailOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listDetailOptsBuilder) ToNodeListDetailQuery() (string, error) {
	query, err := b.base.ToNodeListDetailQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}
func (b listDetailOptsBuilder) ToNodeListQuery() (string, error) {
	query, err := b.base.ToNodeListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// ListDetail invokes the upstream API with library-owned builders and result handling.
func (a *API) ListDetail(ctx context.Context, options ...ListDetailOption) iter.Seq2[*Node, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*Node, error) bool) { var zero *Node; yield(zero, err) }
	}
	_opts := listDetailOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListDetail(a.client, _opts), func(page pagination.Page) ([]Node, error) {
		values, err := upstream.ExtractNodes(page)
		return []Node(values), err
	})
}

// ListFirmware invokes the upstream API with library-owned builders and result handling.
func (a *API) ListFirmware(ctx context.Context, id string) ([]FirmwareComponent, error) {
	result := upstream.ListFirmware(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("ListFirmware", "nodes", err)
	return value0, err
}

// ListVendorPassthruMethods invokes the upstream API with library-owned builders and result handling.
func (a *API) ListVendorPassthruMethods(ctx context.Context, id string) (map[string]VendorPassthruMethod, error) {
	result := upstream.ListVendorPassthruMethods(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("ListVendorPassthruMethods", "nodes", err)
	return value0, err
}

// ListVirtualInterfaces invokes the upstream API with library-owned builders and result handling.
func (a *API) ListVirtualInterfaces(ctx context.Context, id string) ([]VIF, error) {
	result := upstream.ListVirtualInterfaces(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("ListVirtualInterfaces", "nodes", err)
	return value0, err
}

type SetBootDeviceOption = request.Option[BootDeviceOpts]

func WithSetBootDeviceOptions(value BootDeviceOpts) SetBootDeviceOption {
	return request.WithOptions(value)
}
func WithSetBootDeviceField(key string, value any) SetBootDeviceOption {
	return request.WithField[BootDeviceOpts](key, value)
}

type setBootDeviceBootDeviceBuilder struct {
	base   BootDeviceOpts
	config request.Config[BootDeviceOpts]
}

func (b setBootDeviceBootDeviceBuilder) ToBootDeviceMap() (map[string]any, error) {
	body, err := b.base.ToBootDeviceMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// SetBootDevice invokes the upstream API with library-owned builders and result handling.
func (a *API) SetBootDevice(ctx context.Context, id string, bootDevice BootDeviceOpts, options ...SetBootDeviceOption) error {
	cfg, err := request.Apply(bootDevice, options...)
	if err != nil {
		return err
	}
	_bootDevice := setBootDeviceBootDeviceBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("SetBootDevice", "nodes", upstream.SetBootDevice(ctx, a.client, id, _bootDevice).ExtractErr())
}

type SetMaintenanceOption = request.Option[MaintenanceOpts]

func WithSetMaintenanceOptions(value MaintenanceOpts) SetMaintenanceOption {
	return request.WithOptions(value)
}
func WithSetMaintenanceField(key string, value any) SetMaintenanceOption {
	return request.WithField[MaintenanceOpts](key, value)
}

type setMaintenanceOptsBuilder struct {
	base   MaintenanceOpts
	config request.Config[MaintenanceOpts]
}

func (b setMaintenanceOptsBuilder) ToMaintenanceMap() (map[string]any, error) {
	body, err := b.base.ToMaintenanceMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// SetMaintenance invokes the upstream API with library-owned builders and result handling.
func (a *API) SetMaintenance(ctx context.Context, id string, opts MaintenanceOpts, options ...SetMaintenanceOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := setMaintenanceOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("SetMaintenance", "nodes", upstream.SetMaintenance(ctx, a.client, id, _opts).ExtractErr())
}

type SetRAIDConfigOption = request.Option[RAIDConfigOpts]

func WithSetRAIDConfigOptions(value RAIDConfigOpts) SetRAIDConfigOption {
	return request.WithOptions(value)
}
func WithSetRAIDConfigField(key string, value any) SetRAIDConfigOption {
	return request.WithField[RAIDConfigOpts](key, value)
}

type setRAIDConfigRaidConfigOptsBuilderBuilder struct {
	base   RAIDConfigOpts
	config request.Config[RAIDConfigOpts]
}

func (b setRAIDConfigRaidConfigOptsBuilderBuilder) ToRAIDConfigMap() (map[string]any, error) {
	body, err := b.base.ToRAIDConfigMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// SetRAIDConfig invokes the upstream API with library-owned builders and result handling.
func (a *API) SetRAIDConfig(ctx context.Context, id string, raidConfigOptsBuilder RAIDConfigOpts, options ...SetRAIDConfigOption) error {
	cfg, err := request.Apply(raidConfigOptsBuilder, options...)
	if err != nil {
		return err
	}
	_raidConfigOptsBuilder := setRAIDConfigRaidConfigOptsBuilderBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("SetRAIDConfig", "nodes", upstream.SetRAIDConfig(ctx, a.client, id, _raidConfigOptsBuilder).ExtractErr())
}

// UnsetMaintenance invokes the upstream API with library-owned builders and result handling.
func (a *API) UnsetMaintenance(ctx context.Context, id string) error {
	return request.Wrap("UnsetMaintenance", "nodes", upstream.UnsetMaintenance(ctx, a.client, id).ExtractErr())
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Node, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Node
		return zero0, err
	}
	result := upstream.Update(ctx, a.client, id, cfg.Options)
	value0, err := result.Extract()
	err = request.Wrap("Update", "nodes", err)
	return value0, err
}

// Validate invokes the upstream API with library-owned builders and result handling.
func (a *API) Validate(ctx context.Context, id string) (*NodeValidation, error) {
	result := upstream.Validate(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Validate", "nodes", err)
	return value0, err
}

// WaitForProvisionState invokes the upstream API with library-owned builders and result handling.
func (a *API) WaitForProvisionState(ctx context.Context, id string, state ProvisionState) error {
	return request.Wrap("WaitForProvisionState", "nodes", upstream.WaitForProvisionState(ctx, a.client, id, state))
}
