// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package nodes

import (
	context "context"
	fmt "fmt"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	strings "strings"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Node] {
	return resource.NewCollection(resource.Adapter[Node]{
		Kind:   "nodes",
		Get:    func(ctx context.Context, id string) (*Node, error) { return a.Get(ctx, string(id)) },
		ID:     func(v *Node) string { return fmt.Sprint(v.UUID) },
		Name:   func(v *Node) string { return fmt.Sprint(v.Name) },
		Status: func(v *Node) string { return fmt.Sprint(v.ProvisionState) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Node, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := make([]ListDetailOption, 0, len(q))
			for key, values := range q {
				for _, value := range values {
					options = append(options, WithListDetailQuery(key, value))
				}
			}
			return a.listDetailWithControl(ctx, control, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Node, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Node, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Node, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
