// Code generated by sdkgen; DO NOT EDIT.
package v1

import (
	resource0 "github.com/JSYoo5B/go-openstacksdk/reservation/v1/hosts"
	gophercloud "github.com/gophercloud/gophercloud/v2"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client *gophercloud.ServiceClient
	Hosts  *resource0.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		Hosts: resource0.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
