// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package members

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/image/v2/members"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type DetailsResult = upstream.DetailsResult
type Member = upstream.Member
type MemberPage = upstream.MemberPage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, id string, member string) (*Member, error) {
	result := upstream.Create(ctx, a.client, id, member)
	value0, err := result.Extract()
	err = request.Wrap("Create", "members", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, imageID string, memberID string) error {
	return request.Wrap("Delete", "members", upstream.Delete(ctx, a.client, imageID, memberID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, imageID string, memberID string) (*Member, error) {
	result := upstream.Get(ctx, a.client, imageID, memberID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "members", err)
	return value0, err
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, id string) iter.Seq2[*Member, error] {
	return a.listWithControl(ctx, id, resource.ListControl{})
}

func (a *API) listWithControl(ctx context.Context, id string, control resource.ListControl) iter.Seq2[*Member, error] {
	return resource.StreamWithControl(ctx, upstream.List(a.client, id), func(page pagination.Page) ([]Member, error) {
		values, err := upstream.ExtractMembers(page)
		return []Member(values), err
	}, control)
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToImageMemberUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToImageMemberUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, imageID string, memberID string, opts UpdateOpts, options ...UpdateOption) (*Member, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "members", err)
		var zero0 *Member
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "members", err)
		var zero0 *Member
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, imageID, memberID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "members", err)
	return value0, err
}
