// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package members

import (
	context "context"
	fmt "fmt"
	images "gophercloudsdk/image/v2/images"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	strings "strings"
)

// MemberScope fixes the parent of its resources, sharing the SDK's lookup and wait policies.
type MemberScope struct {
	*resource.Collection[Member]
	api      *API
	parentID string
}

// InImage resolves the parent once; explicit IDs require no lookup request.
func (a *API) InImage(ctx context.Context, parent resource.Ref) (*MemberScope, error) {
	id, err := images.New(a.client).Resources.ResolveID(ctx, parent)
	if err != nil {
		return nil, err
	}
	scope := &MemberScope{api: a, parentID: id}
	scope.Collection = scope.newResources()
	return scope, nil
}
func (s *MemberScope) newResources() *resource.Collection[Member] {
	return resource.NewCollection(resource.Adapter[Member]{
		Kind:   "members",
		Get:    func(ctx context.Context, id string) (*Member, error) { return s.api.Get(ctx, s.parentID, string(id)) },
		ID:     func(v *Member) string { return fmt.Sprint(v.MemberID) },
		Status: func(v *Member) string { return fmt.Sprint(v.Status) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return s.api.Delete(ctx, s.parentID, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Member, error] {
			q = maps.Clone(q)
			q.Del("status")
			if len(q) != 0 {
				return func(yield func(*Member, error) bool) { yield(nil, resource.ErrUnsupported) }
			}
			return s.api.listWithControl(ctx, s.parentID, control)
		}})
}

// Create applies Create within the fixed parent.
func (s *MemberScope) Create(ctx context.Context, member string) (*Member, error) {
	return s.api.Create(ctx, s.parentID, member)
}

// Update applies Update within the fixed parent.
func (s *MemberScope) Update(ctx context.Context, ref resource.Ref, opts UpdateOpts, options ...UpdateOption) (*Member, error) {
	id, err := s.Collection.ResolveID(ctx, ref)
	if err != nil {
		var zero0 *Member
		return zero0, err
	}
	return s.api.Update(ctx, s.parentID, id, opts, options...)
}
