// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package recordsets

import (
	context "context"
	fmt "fmt"
	zones "gophercloudsdk/dns/v2/zones"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	strings "strings"
)

// RecordSetScope fixes the parent of its resources, sharing the SDK's lookup and wait policies.
type RecordSetScope struct {
	*resource.Collection[RecordSet]
	api      *API
	parentID string
}

// InZone resolves the parent once; explicit IDs require no lookup request.
func (a *API) InZone(ctx context.Context, parent resource.Ref) (*RecordSetScope, error) {
	id, err := zones.New(a.client).Resources.ResolveID(ctx, parent)
	if err != nil {
		return nil, err
	}
	scope := &RecordSetScope{api: a, parentID: id}
	scope.Collection = scope.newResources()
	return scope, nil
}
func (s *RecordSetScope) newResources() *resource.Collection[RecordSet] {
	return resource.NewCollection(resource.Adapter[RecordSet]{
		Kind: "recordsets",
		Get: func(ctx context.Context, id string) (*RecordSet, error) {
			return s.api.Get(ctx, s.parentID, string(id))
		},
		ID:        func(v *RecordSet) string { return fmt.Sprint(v.ID) },
		Name:      func(v *RecordSet) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Status:    func(v *RecordSet) string { return fmt.Sprint(v.Status) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return s.api.Delete(ctx, s.parentID, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*RecordSet, error] {
			q = maps.Clone(q)
			options := make([]ListByZoneOption, 0, len(q))
			for key, values := range q {
				for _, value := range values {
					options = append(options, WithListByZoneQuery(key, value))
				}
			}
			return s.api.listByZoneWithControl(ctx, s.parentID, control, options...)
		}})
}

// Create applies Create within the fixed parent.
func (s *RecordSetScope) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*RecordSet, error) {
	return s.api.Create(ctx, s.parentID, opts, options...)
}

// Update applies Update within the fixed parent.
func (s *RecordSetScope) Update(ctx context.Context, ref resource.Ref, opts UpdateOpts, options ...UpdateOption) (*RecordSet, error) {
	id, err := s.Collection.ResolveID(ctx, ref)
	if err != nil {
		var zero0 *RecordSet
		return zero0, err
	}
	return s.api.Update(ctx, s.parentID, id, opts, options...)
}
