// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package osinherit

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/osinherit"
	request "gophercloudsdk/request"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AssignOpts = upstream.AssignOpts
type AssignmentResult = upstream.AssignmentResult
type UnassignOpts = upstream.UnassignOpts
type UnassignmentResult = upstream.UnassignmentResult
type ValidateOpts = upstream.ValidateOpts
type ValidateResult = upstream.ValidateResult
type AssignOption = request.Option[AssignOpts]

func WithAssignOptions(value AssignOpts) AssignOption { return request.WithOptions(value) }

// Assign invokes the upstream API with library-owned builders and result handling.
func (a *API) Assign(ctx context.Context, roleID string, opts AssignOpts, options ...AssignOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	return request.Wrap("Assign", "osinherit", upstream.Assign(ctx, a.client, roleID, cfg.Options).ExtractErr())
}

type UnassignOption = request.Option[UnassignOpts]

func WithUnassignOptions(value UnassignOpts) UnassignOption { return request.WithOptions(value) }

// Unassign invokes the upstream API with library-owned builders and result handling.
func (a *API) Unassign(ctx context.Context, roleID string, opts UnassignOpts, options ...UnassignOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	return request.Wrap("Unassign", "osinherit", upstream.Unassign(ctx, a.client, roleID, cfg.Options).ExtractErr())
}

type ValidateOption = request.Option[ValidateOpts]

func WithValidateOptions(value ValidateOpts) ValidateOption { return request.WithOptions(value) }

// Validate invokes the upstream API with library-owned builders and result handling.
func (a *API) Validate(ctx context.Context, roleID string, opts ValidateOpts, options ...ValidateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	return request.Wrap("Validate", "osinherit", upstream.Validate(ctx, a.client, roleID, cfg.Options).ExtractErr())
}
