// Code generated by sdkgen; DO NOT EDIT.
package v2

import (
	resource0 "github.com/JSYoo5B/go-openstacksdk/dns/v2/quotas"
	resource1 "github.com/JSYoo5B/go-openstacksdk/dns/v2/recordsets"
	resource2 "github.com/JSYoo5B/go-openstacksdk/dns/v2/transfer/accept"
	resource3 "github.com/JSYoo5B/go-openstacksdk/dns/v2/transfer/request"
	resource4 "github.com/JSYoo5B/go-openstacksdk/dns/v2/tsigkeys"
	resource5 "github.com/JSYoo5B/go-openstacksdk/dns/v2/zones"
	gophercloud "github.com/gophercloud/gophercloud/v2"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client          *gophercloud.ServiceClient
	Quotas          *resource0.API
	RecordSets      *resource1.API
	TransferAccept  *resource2.API
	TransferRequest *resource3.API
	TSIGKeys        *resource4.API
	Zones           *resource5.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		Quotas:          resource0.New(client),
		RecordSets:      resource1.New(client),
		TransferAccept:  resource2.New(client),
		TransferRequest: resource3.New(client),
		TSIGKeys:        resource4.New(client),
		Zones:           resource5.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
