// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package quotasets

import (
	context "context"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/quotasets"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type GetUsageResult = upstream.GetUsageResult
type QuotaSet = upstream.QuotaSet
type QuotaSetPage = upstream.QuotaSetPage
type QuotaUsage = upstream.QuotaUsage
type QuotaUsageSet = upstream.QuotaUsageSet
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, projectID string) error {
	return request.Wrap("Delete", "quotasets", upstream.Delete(ctx, a.client, projectID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, projectID string) (*QuotaSet, error) {
	result := upstream.Get(ctx, a.client, projectID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "quotasets", err)
	return value0, err
}

// GetDefaults invokes the upstream API with library-owned builders and result handling.
func (a *API) GetDefaults(ctx context.Context, projectID string) (*QuotaSet, error) {
	result := upstream.GetDefaults(ctx, a.client, projectID)
	value0, err := result.Extract()
	err = request.Wrap("GetDefaults", "quotasets", err)
	return value0, err
}

// GetUsage invokes the upstream API with library-owned builders and result handling.
func (a *API) GetUsage(ctx context.Context, projectID string) (QuotaUsageSet, error) {
	result := upstream.GetUsage(ctx, a.client, projectID)
	value0, err := result.Extract()
	err = request.Wrap("GetUsage", "quotasets", err)
	return value0, err
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToBlockStorageQuotaUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToBlockStorageQuotaUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, projectID string, opts UpdateOpts, options ...UpdateOption) (*QuotaSet, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "quotasets", err)
		var zero0 *QuotaSet
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "quotasets", err)
		var zero0 *QuotaSet
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, projectID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "quotasets", err)
	return value0, err
}
