// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package queues

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/messaging/v2/queues"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

const AddOp = upstream.AddOp

type BatchUpdateOpts = upstream.BatchUpdateOpts
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts

const MethodGet = upstream.MethodGet
const MethodPatch = upstream.MethodPatch
const MethodPost = upstream.MethodPost
const MethodPut = upstream.MethodPut
const PathClaims = upstream.PathClaims
const PathMessages = upstream.PathMessages
const PathSubscriptions = upstream.PathSubscriptions

type PurgeOpts = upstream.PurgeOpts
type PurgeResource = upstream.PurgeResource
type PurgeResult = upstream.PurgeResult
type Queue = upstream.Queue
type QueueDetails = upstream.QueueDetails
type QueuePage = upstream.QueuePage
type QueueShare = upstream.QueueShare

const RemoveOp = upstream.RemoveOp
const ReplaceOp = upstream.ReplaceOp
const ResourceMessages = upstream.ResourceMessages
const ResourceSubscriptions = upstream.ResourceSubscriptions

type ShareMethod = upstream.ShareMethod
type ShareOpts = upstream.ShareOpts
type SharePath = upstream.SharePath
type ShareResult = upstream.ShareResult
type StatResult = upstream.StatResult
type Stats = upstream.Stats
type UpdateOp = upstream.UpdateOp
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToQueueCreateMap() (map[string]any, error) {
	value0, err := b.base.ToQueueCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "queues", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "queues", err)
		return err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Create", "queues", upstream.Create(ctx, a.client, _opts).ExtractErr())
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, queueName string) error {
	return request.Wrap("Delete", "queues", upstream.Delete(ctx, a.client, queueName).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, queueName string) (QueueDetails, error) {
	result := upstream.Get(ctx, a.client, queueName)
	value0, err := result.Extract()
	err = request.Wrap("Get", "queues", err)
	return value0, err
}

// GetStats invokes the upstream API with library-owned builders and result handling.
func (a *API) GetStats(ctx context.Context, queueName string) (Stats, error) {
	result := upstream.GetStats(ctx, a.client, queueName)
	value0, err := result.Extract()
	err = request.Wrap("GetStats", "queues", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToQueueListQuery() (string, error) {
	value0, err := b.base.ToQueueListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Queue, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "queues", err)
		return func(yield func(*Queue, error) bool) { var zero *Queue; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "queues", err)
		return func(yield func(*Queue, error) bool) { var zero *Queue; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Queue, error) {
		values, err := upstream.ExtractQueues(page)
		return []Queue(values), err
	})
}

type PurgeOption = request.Option[PurgeOpts]

func WithPurgeOptions(value PurgeOpts) PurgeOption { return request.WithOptions(value) }
func WithPurgeField(key string, value any) PurgeOption {
	return request.WithField[PurgeOpts](key, value)
}

type purgeOptsBuilder struct {
	base   PurgeOpts
	config request.Config[PurgeOpts]
}

func (b purgeOptsBuilder) ToQueuePurgeMap() (map[string]any, error) {
	value0, err := b.base.ToQueuePurgeMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Purge invokes the upstream API with library-owned builders and result handling.
func (a *API) Purge(ctx context.Context, queueName string, opts PurgeOpts, options ...PurgeOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Purge", "queues", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Purge", "queues", err)
		return err
	}
	_opts := purgeOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Purge", "queues", upstream.Purge(ctx, a.client, queueName, _opts).ExtractErr())
}

type ShareOption = request.Option[ShareOpts]

func WithShareOptions(value ShareOpts) ShareOption { return request.WithOptions(value) }
func WithShareField(key string, value any) ShareOption {
	return request.WithField[ShareOpts](key, value)
}

type shareOptsBuilder struct {
	base   ShareOpts
	config request.Config[ShareOpts]
}

func (b shareOptsBuilder) ToQueueShareMap() (map[string]any, error) {
	value0, err := b.base.ToQueueShareMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Share invokes the upstream API with library-owned builders and result handling.
func (a *API) Share(ctx context.Context, queueName string, opts ShareOpts, options ...ShareOption) (QueueShare, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Share", "queues", err)
		var zero0 QueueShare
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Share", "queues", err)
		var zero0 QueueShare
		return zero0, err
	}
	_opts := shareOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Share(ctx, a.client, queueName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Share", "queues", err)
	return value0, err
}

type UpdateOption = request.Option[BatchUpdateOpts]

func WithUpdateOptions(value BatchUpdateOpts) UpdateOption { return request.WithOptions(value) }

type updateOptsBuilder struct {
	base   BatchUpdateOpts
	config request.Config[BatchUpdateOpts]
}

func (b updateOptsBuilder) ToQueueUpdateMap() ([]map[string]any, error) {
	return b.base.ToQueueUpdateMap()
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, queueName string, opts BatchUpdateOpts, options ...UpdateOption) (QueueDetails, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "queues", err)
		var zero0 QueueDetails
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, false, false); err != nil {
		err = request.Wrap("Update", "queues", err)
		var zero0 QueueDetails
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, queueName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "queues", err)
	return value0, err
}
