// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package messages

import (
	context "context"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/messaging/v2/messages"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type BatchCreateOpts = upstream.BatchCreateOpts
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteMessagesOpts = upstream.DeleteMessagesOpts
type DeleteOpts = upstream.DeleteOpts
type DeleteResult = upstream.DeleteResult
type GetMessagesOpts = upstream.GetMessagesOpts
type GetMessagesResult = upstream.GetMessagesResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type Message = upstream.Message
type MessagePage = upstream.MessagePage
type PopMessage = upstream.PopMessage
type PopMessagesOpts = upstream.PopMessagesOpts
type PopResult = upstream.PopResult
type ResourceList = upstream.ResourceList
type CreateOption = request.Option[BatchCreateOpts]

func WithCreateOptions(value BatchCreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[BatchCreateOpts](key, value)
}

type createOptsBuilder struct {
	base   BatchCreateOpts
	config request.Config[BatchCreateOpts]
}

func (b createOptsBuilder) ToMessageCreateMap() (map[string]any, error) {
	value0, err := b.base.ToMessageCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, queueName string, opts BatchCreateOpts, options ...CreateOption) (ResourceList, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "messages", err)
		var zero0 ResourceList
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "messages", err)
		var zero0 ResourceList
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, queueName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "messages", err)
	return value0, err
}

type DeleteOption = request.Option[DeleteOpts]

func WithDeleteOptions(value DeleteOpts) DeleteOption { return request.WithOptions(value) }
func WithDeleteQuery(key, value string) DeleteOption {
	return request.WithQuery[DeleteOpts](key, value)
}

type deleteOptsBuilder struct {
	base   DeleteOpts
	config request.Config[DeleteOpts]
}

func (b deleteOptsBuilder) ToMessageDeleteQuery() (string, error) {
	value0, err := b.base.ToMessageDeleteQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, queueName string, messageID string, options ...DeleteOption) error {
	var opts DeleteOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Delete", "messages", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("Delete", "messages", err)
		return err
	}
	_opts := deleteOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Delete", "messages", upstream.Delete(ctx, a.client, queueName, messageID, _opts).ExtractErr())
}

// DeleteMessageURL invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteMessageURL(ctx context.Context, queueName string, messageID string) string {
	return upstream.DeleteMessageURL(a.client, queueName, messageID)
}

type DeleteMessagesOption = request.Option[DeleteMessagesOpts]

func WithDeleteMessagesOptions(value DeleteMessagesOpts) DeleteMessagesOption {
	return request.WithOptions(value)
}
func WithDeleteMessagesQuery(key, value string) DeleteMessagesOption {
	return request.WithQuery[DeleteMessagesOpts](key, value)
}

type deleteMessagesOptsBuilder struct {
	base   DeleteMessagesOpts
	config request.Config[DeleteMessagesOpts]
}

func (b deleteMessagesOptsBuilder) ToMessagesDeleteQuery() (string, error) {
	value0, err := b.base.ToMessagesDeleteQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// DeleteMessages invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteMessages(ctx context.Context, queueName string, options ...DeleteMessagesOption) error {
	var opts DeleteMessagesOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("DeleteMessages", "messages", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("DeleteMessages", "messages", err)
		return err
	}
	_opts := deleteMessagesOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("DeleteMessages", "messages", upstream.DeleteMessages(ctx, a.client, queueName, _opts).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, queueName string, messageID string) (Message, error) {
	result := upstream.Get(ctx, a.client, queueName, messageID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "messages", err)
	return value0, err
}

type GetMessagesOption = request.Option[GetMessagesOpts]

func WithGetMessagesOptions(value GetMessagesOpts) GetMessagesOption {
	return request.WithOptions(value)
}
func WithGetMessagesQuery(key, value string) GetMessagesOption {
	return request.WithQuery[GetMessagesOpts](key, value)
}

type getMessagesOptsBuilder struct {
	base   GetMessagesOpts
	config request.Config[GetMessagesOpts]
}

func (b getMessagesOptsBuilder) ToGetMessagesListQuery() (string, error) {
	value0, err := b.base.ToGetMessagesListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// GetMessages invokes the upstream API with library-owned builders and result handling.
func (a *API) GetMessages(ctx context.Context, queueName string, options ...GetMessagesOption) ([]Message, error) {
	var opts GetMessagesOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("GetMessages", "messages", err)
		var zero0 []Message
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("GetMessages", "messages", err)
		var zero0 []Message
		return zero0, err
	}
	_opts := getMessagesOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.GetMessages(ctx, a.client, queueName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("GetMessages", "messages", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToMessageListQuery() (string, error) {
	value0, err := b.base.ToMessageListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, queueName string, options ...ListOption) iter.Seq2[*Message, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "messages", err)
		return func(yield func(*Message, error) bool) { var zero *Message; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "messages", err)
		return func(yield func(*Message, error) bool) { var zero *Message; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, queueName, _opts), func(page pagination.Page) ([]Message, error) {
		values, err := upstream.ExtractMessages(page)
		return []Message(values), err
	})
}

type PopMessagesOption = request.Option[PopMessagesOpts]

func WithPopMessagesOptions(value PopMessagesOpts) PopMessagesOption {
	return request.WithOptions(value)
}
func WithPopMessagesQuery(key, value string) PopMessagesOption {
	return request.WithQuery[PopMessagesOpts](key, value)
}

type popMessagesOptsBuilder struct {
	base   PopMessagesOpts
	config request.Config[PopMessagesOpts]
}

func (b popMessagesOptsBuilder) ToMessagesPopQuery() (string, error) {
	value0, err := b.base.ToMessagesPopQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// PopMessages invokes the upstream API with library-owned builders and result handling.
func (a *API) PopMessages(ctx context.Context, queueName string, opts PopMessagesOpts, options ...PopMessagesOption) ([]PopMessage, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("PopMessages", "messages", err)
		var zero0 []PopMessage
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("PopMessages", "messages", err)
		var zero0 []PopMessage
		return zero0, err
	}
	_opts := popMessagesOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.PopMessages(ctx, a.client, queueName, _opts)
	value0, err := result.Extract()
	err = request.Wrap("PopMessages", "messages", err)
	return value0, err
}
