// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package secgroups

import (
	context "context"
	fmt "fmt"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[SecurityGroup] {
	return resource.NewCollection(resource.Adapter[SecurityGroup]{
		Kind:   "secgroups",
		Get:    func(ctx context.Context, id string) (*SecurityGroup, error) { return a.Get(ctx, string(id)) },
		ID:     func(v *SecurityGroup) string { return fmt.Sprint(v.ID) },
		Name:   func(v *SecurityGroup) string { return fmt.Sprint(v.Name) },
		Delete: func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*SecurityGroup, error] {
			q = maps.Clone(q)
			q.Del("status")
			if len(q) != 0 {
				return func(yield func(*SecurityGroup, error) bool) { yield(nil, resource.ErrUnsupported) }
			}
			return a.listWithControl(ctx, control)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*SecurityGroup, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*SecurityGroup, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*SecurityGroup, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
