// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package messages

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/sharedfilesystems/v2/messages"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[Message]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type Message = upstream.Message
type MessagePage = upstream.MessagePage

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "messages", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Message, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "messages", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToMessageListQuery() (string, error) {
	value0, err := b.base.ToMessageListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Message, error] {
	return a.listWithControl(ctx, resource.ListControl{}, options...)
}

func (a *API) listWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*Message, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "messages", err)
		return func(yield func(*Message, error) bool) { var zero *Message; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "messages", err)
		return func(yield func(*Message, error) bool) { var zero *Message; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.StreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Message, error) {
		values, err := upstream.ExtractMessages(page)
		return []Message(values), err
	}, control)
}
