// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package accept

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/dns/v2/transfer/accept"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type TransferAccept = upstream.TransferAccept
type TransferAcceptPage = upstream.TransferAcceptPage
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToTransferAcceptCreateMap() (map[string]any, error) {
	body, err := b.base.ToTransferAcceptCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*TransferAccept, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *TransferAccept
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "accept", err)
	return value0, err
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, transferAcceptID string) (*TransferAccept, error) {
	result := upstream.Get(ctx, a.client, transferAcceptID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "accept", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToTransferAcceptListQuery() (string, error) {
	query, err := b.base.ToTransferAcceptListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*TransferAccept, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*TransferAccept, error) bool) { var zero *TransferAccept; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]TransferAccept, error) {
		values, err := upstream.ExtractTransferAccepts(page)
		return []TransferAccept(values), err
	})
}
