// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package conductors

import (
	context "context"
	fmt "fmt"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Conductor] {
	return resource.NewCollection(resource.Adapter[Conductor]{
		Kind: "conductors",
		Get:  func(ctx context.Context, id string) (*Conductor, error) { return a.Get(ctx, string(id)) },
		ID:   func(v *Conductor) string { return fmt.Sprint(v.Hostname) },
		Name: func(v *Conductor) string { return fmt.Sprint(v.Hostname) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Conductor, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := make([]ListOption, 0, len(q))
			for key, values := range q {
				for _, value := range values {
					options = append(options, WithListQuery(key, value))
				}
			}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Conductor, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Conductor, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Conductor, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
