// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package rules

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/qos/rules"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type BandwidthLimitRule = upstream.BandwidthLimitRule
type BandwidthLimitRulePage = upstream.BandwidthLimitRulePage
type BandwidthLimitRulesListOpts = upstream.BandwidthLimitRulesListOpts
type CreateBandwidthLimitRuleOpts = upstream.CreateBandwidthLimitRuleOpts
type CreateBandwidthLimitRuleResult = upstream.CreateBandwidthLimitRuleResult
type CreateDSCPMarkingRuleOpts = upstream.CreateDSCPMarkingRuleOpts
type CreateDSCPMarkingRuleResult = upstream.CreateDSCPMarkingRuleResult
type CreateMinimumBandwidthRuleOpts = upstream.CreateMinimumBandwidthRuleOpts
type CreateMinimumBandwidthRuleResult = upstream.CreateMinimumBandwidthRuleResult
type DSCPMarkingRule = upstream.DSCPMarkingRule
type DSCPMarkingRulePage = upstream.DSCPMarkingRulePage
type DSCPMarkingRulesListOpts = upstream.DSCPMarkingRulesListOpts
type DeleteBandwidthLimitRuleResult = upstream.DeleteBandwidthLimitRuleResult
type DeleteDSCPMarkingRuleResult = upstream.DeleteDSCPMarkingRuleResult
type DeleteMinimumBandwidthRuleResult = upstream.DeleteMinimumBandwidthRuleResult
type GetBandwidthLimitRuleResult = upstream.GetBandwidthLimitRuleResult
type GetDSCPMarkingRuleResult = upstream.GetDSCPMarkingRuleResult
type GetMinimumBandwidthRuleResult = upstream.GetMinimumBandwidthRuleResult
type MinimumBandwidthRule = upstream.MinimumBandwidthRule
type MinimumBandwidthRulePage = upstream.MinimumBandwidthRulePage
type MinimumBandwidthRulesListOpts = upstream.MinimumBandwidthRulesListOpts
type UpdateBandwidthLimitRuleOpts = upstream.UpdateBandwidthLimitRuleOpts
type UpdateBandwidthLimitRuleResult = upstream.UpdateBandwidthLimitRuleResult
type UpdateDSCPMarkingRuleOpts = upstream.UpdateDSCPMarkingRuleOpts
type UpdateDSCPMarkingRuleResult = upstream.UpdateDSCPMarkingRuleResult
type UpdateMinimumBandwidthRuleOpts = upstream.UpdateMinimumBandwidthRuleOpts
type UpdateMinimumBandwidthRuleResult = upstream.UpdateMinimumBandwidthRuleResult
type CreateBandwidthLimitRuleOption = request.Option[CreateBandwidthLimitRuleOpts]

func WithCreateBandwidthLimitRuleOptions(value CreateBandwidthLimitRuleOpts) CreateBandwidthLimitRuleOption {
	return request.WithOptions(value)
}
func WithCreateBandwidthLimitRuleField(key string, value any) CreateBandwidthLimitRuleOption {
	return request.WithField[CreateBandwidthLimitRuleOpts](key, value)
}

type createBandwidthLimitRuleOptsBuilder struct {
	base   CreateBandwidthLimitRuleOpts
	config request.Config[CreateBandwidthLimitRuleOpts]
}

func (b createBandwidthLimitRuleOptsBuilder) ToBandwidthLimitRuleCreateMap() (map[string]any, error) {
	value0, err := b.base.ToBandwidthLimitRuleCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// CreateBandwidthLimitRule invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateBandwidthLimitRule(ctx context.Context, policyID string, opts CreateBandwidthLimitRuleOpts, options ...CreateBandwidthLimitRuleOption) (CreateBandwidthLimitRuleResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateBandwidthLimitRule", "rules", err)
		var zero0 CreateBandwidthLimitRuleResult
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("CreateBandwidthLimitRule", "rules", err)
		var zero0 CreateBandwidthLimitRuleResult
		return zero0, err
	}
	_opts := createBandwidthLimitRuleOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateBandwidthLimitRule(ctx, a.client, policyID, _opts)
	return result, request.Wrap("CreateBandwidthLimitRule", "rules", result.Err)
}

type CreateDSCPMarkingRuleOption = request.Option[CreateDSCPMarkingRuleOpts]

func WithCreateDSCPMarkingRuleOptions(value CreateDSCPMarkingRuleOpts) CreateDSCPMarkingRuleOption {
	return request.WithOptions(value)
}
func WithCreateDSCPMarkingRuleField(key string, value any) CreateDSCPMarkingRuleOption {
	return request.WithField[CreateDSCPMarkingRuleOpts](key, value)
}

type createDSCPMarkingRuleOptsBuilder struct {
	base   CreateDSCPMarkingRuleOpts
	config request.Config[CreateDSCPMarkingRuleOpts]
}

func (b createDSCPMarkingRuleOptsBuilder) ToDSCPMarkingRuleCreateMap() (map[string]any, error) {
	value0, err := b.base.ToDSCPMarkingRuleCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// CreateDSCPMarkingRule invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateDSCPMarkingRule(ctx context.Context, policyID string, opts CreateDSCPMarkingRuleOpts, options ...CreateDSCPMarkingRuleOption) (CreateDSCPMarkingRuleResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateDSCPMarkingRule", "rules", err)
		var zero0 CreateDSCPMarkingRuleResult
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("CreateDSCPMarkingRule", "rules", err)
		var zero0 CreateDSCPMarkingRuleResult
		return zero0, err
	}
	_opts := createDSCPMarkingRuleOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateDSCPMarkingRule(ctx, a.client, policyID, _opts)
	return result, request.Wrap("CreateDSCPMarkingRule", "rules", result.Err)
}

type CreateMinimumBandwidthRuleOption = request.Option[CreateMinimumBandwidthRuleOpts]

func WithCreateMinimumBandwidthRuleOptions(value CreateMinimumBandwidthRuleOpts) CreateMinimumBandwidthRuleOption {
	return request.WithOptions(value)
}
func WithCreateMinimumBandwidthRuleField(key string, value any) CreateMinimumBandwidthRuleOption {
	return request.WithField[CreateMinimumBandwidthRuleOpts](key, value)
}

type createMinimumBandwidthRuleOptsBuilder struct {
	base   CreateMinimumBandwidthRuleOpts
	config request.Config[CreateMinimumBandwidthRuleOpts]
}

func (b createMinimumBandwidthRuleOptsBuilder) ToMinimumBandwidthRuleCreateMap() (map[string]any, error) {
	value0, err := b.base.ToMinimumBandwidthRuleCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// CreateMinimumBandwidthRule invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateMinimumBandwidthRule(ctx context.Context, policyID string, opts CreateMinimumBandwidthRuleOpts, options ...CreateMinimumBandwidthRuleOption) (CreateMinimumBandwidthRuleResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateMinimumBandwidthRule", "rules", err)
		var zero0 CreateMinimumBandwidthRuleResult
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("CreateMinimumBandwidthRule", "rules", err)
		var zero0 CreateMinimumBandwidthRuleResult
		return zero0, err
	}
	_opts := createMinimumBandwidthRuleOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateMinimumBandwidthRule(ctx, a.client, policyID, _opts)
	return result, request.Wrap("CreateMinimumBandwidthRule", "rules", result.Err)
}

// DeleteBandwidthLimitRule invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteBandwidthLimitRule(ctx context.Context, policyID string, ruleID string) error {
	return request.Wrap("DeleteBandwidthLimitRule", "rules", upstream.DeleteBandwidthLimitRule(ctx, a.client, policyID, ruleID).ExtractErr())
}

// DeleteDSCPMarkingRule invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteDSCPMarkingRule(ctx context.Context, policyID string, ruleID string) error {
	return request.Wrap("DeleteDSCPMarkingRule", "rules", upstream.DeleteDSCPMarkingRule(ctx, a.client, policyID, ruleID).ExtractErr())
}

// DeleteMinimumBandwidthRule invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteMinimumBandwidthRule(ctx context.Context, policyID string, ruleID string) error {
	return request.Wrap("DeleteMinimumBandwidthRule", "rules", upstream.DeleteMinimumBandwidthRule(ctx, a.client, policyID, ruleID).ExtractErr())
}

// GetBandwidthLimitRule invokes the upstream API with library-owned builders and result handling.
func (a *API) GetBandwidthLimitRule(ctx context.Context, policyID string, ruleID string) (GetBandwidthLimitRuleResult, error) {
	result := upstream.GetBandwidthLimitRule(ctx, a.client, policyID, ruleID)
	return result, request.Wrap("GetBandwidthLimitRule", "rules", result.Err)
}

// GetDSCPMarkingRule invokes the upstream API with library-owned builders and result handling.
func (a *API) GetDSCPMarkingRule(ctx context.Context, policyID string, ruleID string) (GetDSCPMarkingRuleResult, error) {
	result := upstream.GetDSCPMarkingRule(ctx, a.client, policyID, ruleID)
	return result, request.Wrap("GetDSCPMarkingRule", "rules", result.Err)
}

// GetMinimumBandwidthRule invokes the upstream API with library-owned builders and result handling.
func (a *API) GetMinimumBandwidthRule(ctx context.Context, policyID string, ruleID string) (GetMinimumBandwidthRuleResult, error) {
	result := upstream.GetMinimumBandwidthRule(ctx, a.client, policyID, ruleID)
	return result, request.Wrap("GetMinimumBandwidthRule", "rules", result.Err)
}

type ListBandwidthLimitRulesOption = request.Option[BandwidthLimitRulesListOpts]

func WithListBandwidthLimitRulesOptions(value BandwidthLimitRulesListOpts) ListBandwidthLimitRulesOption {
	return request.WithOptions(value)
}
func WithListBandwidthLimitRulesQuery(key, value string) ListBandwidthLimitRulesOption {
	return request.WithQuery[BandwidthLimitRulesListOpts](key, value)
}

type listBandwidthLimitRulesOptsBuilder struct {
	base   BandwidthLimitRulesListOpts
	config request.Config[BandwidthLimitRulesListOpts]
}

func (b listBandwidthLimitRulesOptsBuilder) ToBandwidthLimitRulesListQuery() (string, error) {
	value0, err := b.base.ToBandwidthLimitRulesListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// ListBandwidthLimitRules invokes the upstream API with library-owned builders and result handling.
func (a *API) ListBandwidthLimitRules(ctx context.Context, policyID string, options ...ListBandwidthLimitRulesOption) iter.Seq2[*BandwidthLimitRule, error] {
	var opts BandwidthLimitRulesListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ListBandwidthLimitRules", "rules", err)
		return func(yield func(*BandwidthLimitRule, error) bool) { var zero *BandwidthLimitRule; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("ListBandwidthLimitRules", "rules", err)
		return func(yield func(*BandwidthLimitRule, error) bool) { var zero *BandwidthLimitRule; yield(zero, err) }
	}
	_opts := listBandwidthLimitRulesOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListBandwidthLimitRules(a.client, policyID, _opts), func(page pagination.Page) ([]BandwidthLimitRule, error) {
		values, err := upstream.ExtractBandwidthLimitRules(page)
		return []BandwidthLimitRule(values), err
	})
}

type ListDSCPMarkingRulesOption = request.Option[DSCPMarkingRulesListOpts]

func WithListDSCPMarkingRulesOptions(value DSCPMarkingRulesListOpts) ListDSCPMarkingRulesOption {
	return request.WithOptions(value)
}
func WithListDSCPMarkingRulesQuery(key, value string) ListDSCPMarkingRulesOption {
	return request.WithQuery[DSCPMarkingRulesListOpts](key, value)
}

type listDSCPMarkingRulesOptsBuilder struct {
	base   DSCPMarkingRulesListOpts
	config request.Config[DSCPMarkingRulesListOpts]
}

func (b listDSCPMarkingRulesOptsBuilder) ToDSCPMarkingRulesListQuery() (string, error) {
	value0, err := b.base.ToDSCPMarkingRulesListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// ListDSCPMarkingRules invokes the upstream API with library-owned builders and result handling.
func (a *API) ListDSCPMarkingRules(ctx context.Context, policyID string, options ...ListDSCPMarkingRulesOption) iter.Seq2[*DSCPMarkingRule, error] {
	var opts DSCPMarkingRulesListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ListDSCPMarkingRules", "rules", err)
		return func(yield func(*DSCPMarkingRule, error) bool) { var zero *DSCPMarkingRule; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("ListDSCPMarkingRules", "rules", err)
		return func(yield func(*DSCPMarkingRule, error) bool) { var zero *DSCPMarkingRule; yield(zero, err) }
	}
	_opts := listDSCPMarkingRulesOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListDSCPMarkingRules(a.client, policyID, _opts), func(page pagination.Page) ([]DSCPMarkingRule, error) {
		values, err := upstream.ExtractDSCPMarkingRules(page)
		return []DSCPMarkingRule(values), err
	})
}

type ListMinimumBandwidthRulesOption = request.Option[MinimumBandwidthRulesListOpts]

func WithListMinimumBandwidthRulesOptions(value MinimumBandwidthRulesListOpts) ListMinimumBandwidthRulesOption {
	return request.WithOptions(value)
}
func WithListMinimumBandwidthRulesQuery(key, value string) ListMinimumBandwidthRulesOption {
	return request.WithQuery[MinimumBandwidthRulesListOpts](key, value)
}

type listMinimumBandwidthRulesOptsBuilder struct {
	base   MinimumBandwidthRulesListOpts
	config request.Config[MinimumBandwidthRulesListOpts]
}

func (b listMinimumBandwidthRulesOptsBuilder) ToMinimumBandwidthRulesListQuery() (string, error) {
	value0, err := b.base.ToMinimumBandwidthRulesListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// ListMinimumBandwidthRules invokes the upstream API with library-owned builders and result handling.
func (a *API) ListMinimumBandwidthRules(ctx context.Context, policyID string, options ...ListMinimumBandwidthRulesOption) iter.Seq2[*MinimumBandwidthRule, error] {
	var opts MinimumBandwidthRulesListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ListMinimumBandwidthRules", "rules", err)
		return func(yield func(*MinimumBandwidthRule, error) bool) { var zero *MinimumBandwidthRule; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("ListMinimumBandwidthRules", "rules", err)
		return func(yield func(*MinimumBandwidthRule, error) bool) { var zero *MinimumBandwidthRule; yield(zero, err) }
	}
	_opts := listMinimumBandwidthRulesOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListMinimumBandwidthRules(a.client, policyID, _opts), func(page pagination.Page) ([]MinimumBandwidthRule, error) {
		values, err := upstream.ExtractMinimumBandwidthRules(page)
		return []MinimumBandwidthRule(values), err
	})
}

type UpdateBandwidthLimitRuleOption = request.Option[UpdateBandwidthLimitRuleOpts]

func WithUpdateBandwidthLimitRuleOptions(value UpdateBandwidthLimitRuleOpts) UpdateBandwidthLimitRuleOption {
	return request.WithOptions(value)
}
func WithUpdateBandwidthLimitRuleField(key string, value any) UpdateBandwidthLimitRuleOption {
	return request.WithField[UpdateBandwidthLimitRuleOpts](key, value)
}

type updateBandwidthLimitRuleOptsBuilder struct {
	base   UpdateBandwidthLimitRuleOpts
	config request.Config[UpdateBandwidthLimitRuleOpts]
}

func (b updateBandwidthLimitRuleOptsBuilder) ToBandwidthLimitRuleUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToBandwidthLimitRuleUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// UpdateBandwidthLimitRule invokes the upstream API with library-owned builders and result handling.
func (a *API) UpdateBandwidthLimitRule(ctx context.Context, policyID string, ruleID string, opts UpdateBandwidthLimitRuleOpts, options ...UpdateBandwidthLimitRuleOption) (UpdateBandwidthLimitRuleResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("UpdateBandwidthLimitRule", "rules", err)
		var zero0 UpdateBandwidthLimitRuleResult
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("UpdateBandwidthLimitRule", "rules", err)
		var zero0 UpdateBandwidthLimitRuleResult
		return zero0, err
	}
	_opts := updateBandwidthLimitRuleOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.UpdateBandwidthLimitRule(ctx, a.client, policyID, ruleID, _opts)
	return result, request.Wrap("UpdateBandwidthLimitRule", "rules", result.Err)
}

type UpdateDSCPMarkingRuleOption = request.Option[UpdateDSCPMarkingRuleOpts]

func WithUpdateDSCPMarkingRuleOptions(value UpdateDSCPMarkingRuleOpts) UpdateDSCPMarkingRuleOption {
	return request.WithOptions(value)
}
func WithUpdateDSCPMarkingRuleField(key string, value any) UpdateDSCPMarkingRuleOption {
	return request.WithField[UpdateDSCPMarkingRuleOpts](key, value)
}

type updateDSCPMarkingRuleOptsBuilder struct {
	base   UpdateDSCPMarkingRuleOpts
	config request.Config[UpdateDSCPMarkingRuleOpts]
}

func (b updateDSCPMarkingRuleOptsBuilder) ToDSCPMarkingRuleUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToDSCPMarkingRuleUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// UpdateDSCPMarkingRule invokes the upstream API with library-owned builders and result handling.
func (a *API) UpdateDSCPMarkingRule(ctx context.Context, policyID string, ruleID string, opts UpdateDSCPMarkingRuleOpts, options ...UpdateDSCPMarkingRuleOption) (UpdateDSCPMarkingRuleResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("UpdateDSCPMarkingRule", "rules", err)
		var zero0 UpdateDSCPMarkingRuleResult
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("UpdateDSCPMarkingRule", "rules", err)
		var zero0 UpdateDSCPMarkingRuleResult
		return zero0, err
	}
	_opts := updateDSCPMarkingRuleOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.UpdateDSCPMarkingRule(ctx, a.client, policyID, ruleID, _opts)
	return result, request.Wrap("UpdateDSCPMarkingRule", "rules", result.Err)
}

type UpdateMinimumBandwidthRuleOption = request.Option[UpdateMinimumBandwidthRuleOpts]

func WithUpdateMinimumBandwidthRuleOptions(value UpdateMinimumBandwidthRuleOpts) UpdateMinimumBandwidthRuleOption {
	return request.WithOptions(value)
}
func WithUpdateMinimumBandwidthRuleField(key string, value any) UpdateMinimumBandwidthRuleOption {
	return request.WithField[UpdateMinimumBandwidthRuleOpts](key, value)
}

type updateMinimumBandwidthRuleOptsBuilder struct {
	base   UpdateMinimumBandwidthRuleOpts
	config request.Config[UpdateMinimumBandwidthRuleOpts]
}

func (b updateMinimumBandwidthRuleOptsBuilder) ToMinimumBandwidthRuleUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToMinimumBandwidthRuleUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// UpdateMinimumBandwidthRule invokes the upstream API with library-owned builders and result handling.
func (a *API) UpdateMinimumBandwidthRule(ctx context.Context, policyID string, ruleID string, opts UpdateMinimumBandwidthRuleOpts, options ...UpdateMinimumBandwidthRuleOption) (UpdateMinimumBandwidthRuleResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("UpdateMinimumBandwidthRule", "rules", err)
		var zero0 UpdateMinimumBandwidthRuleResult
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("UpdateMinimumBandwidthRule", "rules", err)
		var zero0 UpdateMinimumBandwidthRuleResult
		return zero0, err
	}
	_opts := updateMinimumBandwidthRuleOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.UpdateMinimumBandwidthRule(ctx, a.client, policyID, ruleID, _opts)
	return result, request.Wrap("UpdateMinimumBandwidthRule", "rules", result.Err)
}
