// Code generated by sdkgen; DO NOT EDIT.
package v1

import (
	resource0 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/apiversions"
	resource1 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/buildinfo"
	resource2 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/resourcetypes"
	resource3 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/stackevents"
	resource4 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/stackresources"
	resource5 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/stacks"
	resource6 "github.com/JSYoo5B/go-openstacksdk/orchestration/v1/stacktemplates"
	gophercloud "github.com/gophercloud/gophercloud/v2"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client         *gophercloud.ServiceClient
	APIVersions    *resource0.API
	BuildInfo      *resource1.API
	Resourcetypes  *resource2.API
	StackEvents    *resource3.API
	StackResources *resource4.API
	Stacks         *resource5.API
	StackTemplates *resource6.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		APIVersions:    resource0.New(client),
		BuildInfo:      resource1.New(client),
		Resourcetypes:  resource2.New(client),
		StackEvents:    resource3.New(client),
		StackResources: resource4.New(client),
		Stacks:         resource5.New(client),
		StackTemplates: resource6.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
