// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package limits

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/limits"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[Limit]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type BatchCreateOpts = upstream.BatchCreateOpts
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type EnforcementModel = upstream.EnforcementModel
type EnforcementModelResult = upstream.EnforcementModelResult
type GetResult = upstream.GetResult
type Limit = upstream.Limit
type LimitOutput = upstream.LimitOutput
type LimitPage = upstream.LimitPage
type LimitsOutput = upstream.LimitsOutput
type ListOpts = upstream.ListOpts
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type BatchCreateOption = request.Option[BatchCreateOpts]

func WithBatchCreateOptions(value BatchCreateOpts) BatchCreateOption {
	return request.WithOptions(value)
}
func WithBatchCreateField(key string, value any) BatchCreateOption {
	return request.WithField[BatchCreateOpts](key, value)
}

type batchCreateOptsBuilder struct {
	base   BatchCreateOpts
	config request.Config[BatchCreateOpts]
}

func (b batchCreateOptsBuilder) ToLimitsCreateMap() (map[string]any, error) {
	value0, err := b.base.ToLimitsCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// BatchCreate invokes the upstream API with library-owned builders and result handling.
func (a *API) BatchCreate(ctx context.Context, opts BatchCreateOpts, options ...BatchCreateOption) ([]Limit, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("BatchCreate", "limits", err)
		var zero0 []Limit
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("BatchCreate", "limits", err)
		var zero0 []Limit
		return zero0, err
	}
	_opts := batchCreateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.BatchCreate(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("BatchCreate", "limits", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, limitID string) error {
	return request.Wrap("Delete", "limits", upstream.Delete(ctx, a.client, limitID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, limitID string) (*Limit, error) {
	result := upstream.Get(ctx, a.client, limitID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "limits", err)
	return value0, err
}

// GetEnforcementModel invokes the upstream API with library-owned builders and result handling.
func (a *API) GetEnforcementModel(ctx context.Context) (*EnforcementModel, error) {
	result := upstream.GetEnforcementModel(ctx, a.client)
	value0, err := result.Extract()
	err = request.Wrap("GetEnforcementModel", "limits", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToLimitListQuery() (string, error) {
	value0, err := b.base.ToLimitListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Limit, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "limits", err)
		return func(yield func(*Limit, error) bool) { var zero *Limit; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "limits", err)
		return func(yield func(*Limit, error) bool) { var zero *Limit; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Limit, error) {
		values, err := upstream.ExtractLimits(page)
		return []Limit(values), err
	})
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToLimitUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToLimitUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Limit, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "limits", err)
		var zero0 *Limit
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "limits", err)
		var zero0 *Limit
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "limits", err)
	return value0, err
}
