// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package catalog

import (
	context "context"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/catalog"
	tokens "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/tokens"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type ServiceCatalogPage = upstream.ServiceCatalogPage

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context) iter.Seq2[*tokens.CatalogEntry, error] {
	return resource.Stream(ctx, upstream.List(a.client), func(page pagination.Page) ([]tokens.CatalogEntry, error) {
		values, err := upstream.ExtractServiceCatalog(page)
		return []tokens.CatalogEntry(values), err
	})
}
