package blockstorage

// Pinned Cinder v3 Volume Body attributes and wire aliases. source_replica is
// a native Go extension. Route and unknown Resource controls are excluded.
var createVolumeAttributeNames = map[string]string{
	"OS-SCH-HNT:scheduler_hints":            "OS-SCH-HNT:scheduler_hints",
	"attachments":                           "attachments",
	"availability_zone":                     "availability_zone",
	"backup_id":                             "backup_id",
	"bootable":                              "bootable",
	"cluster_name":                          "cluster_name",
	"consistency_group_id":                  "consistencygroup_id",
	"consistencygroup_id":                   "consistencygroup_id",
	"consumes_quota":                        "consumes_quota",
	"created_at":                            "created_at",
	"description":                           "description",
	"encrypted":                             "encrypted",
	"encryption_key_id":                     "encryption_key_id",
	"extended_replication_status":           "os-volume-replication:extended_status",
	"group_id":                              "group_id",
	"host":                                  "os-vol-host-attr:host",
	"id":                                    "id",
	"imageRef":                              "imageRef",
	"image_id":                              "imageRef",
	"is_bootable":                           "bootable",
	"is_encrypted":                          "encrypted",
	"is_multiattach":                        "multiattach",
	"metadata":                              "metadata",
	"migration_id":                          "os-vol-mig-status-attr:name_id",
	"migration_status":                      "os-vol-mig-status-attr:migstat",
	"multiattach":                           "multiattach",
	"name":                                  "name",
	"os-vol-host-attr:host":                 "os-vol-host-attr:host",
	"os-vol-mig-status-attr:migstat":        "os-vol-mig-status-attr:migstat",
	"os-vol-mig-status-attr:name_id":        "os-vol-mig-status-attr:name_id",
	"os-vol-tenant-attr:tenant_id":          "os-vol-tenant-attr:tenant_id",
	"os-volume-replication:driver_data":     "os-volume-replication:driver_data",
	"os-volume-replication:extended_status": "os-volume-replication:extended_status",
	"project_id":                            "os-vol-tenant-attr:tenant_id",
	"provider_id":                           "provider_id",
	"replication_driver_data":               "os-volume-replication:driver_data",
	"replication_status":                    "replication_status",
	"scheduler_hints":                       "OS-SCH-HNT:scheduler_hints",
	"service_uuid":                          "service_uuid",
	"shared_targets":                        "shared_targets",
	"size":                                  "size",
	"snapshot_id":                           "snapshot_id",
	"source_replica":                        "source_replica",
	"source_volid":                          "source_volid",
	"source_volume_id":                      "source_volid",
	"status":                                "status",
	"updated_at":                            "updated_at",
	"user_id":                               "user_id",
	"volume_image_metadata":                 "volume_image_metadata",
	"volume_type":                           "volume_type",
	"volume_type_id":                        "volume_type_id",
}
