// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package allocations

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/placement/v1/allocations"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type Allocations = upstream.Allocations
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type ManageOpts = upstream.ManageOpts
type ManageResult = upstream.ManageResult
type ProviderAllocations = upstream.ProviderAllocations
type ProviderAllocationsOpts = upstream.ProviderAllocationsOpts
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, consumerUUID string) error {
	return request.Wrap("Delete", "allocations", upstream.Delete(ctx, a.client, consumerUUID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, consumerUUID string) (*Allocations, error) {
	result := upstream.Get(ctx, a.client, consumerUUID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "allocations", err)
	return value0, err
}

type ManageOption = request.Option[ManageOpts]

func WithManageOptions(value ManageOpts) ManageOption { return request.WithOptions(value) }
func WithManageField(key string, value any) ManageOption {
	return request.WithField[ManageOpts](key, value)
}

type manageOptsBuilder struct {
	base   ManageOpts
	config request.Config[ManageOpts]
}

func (b manageOptsBuilder) ToAllocationManageMap() (map[string]any, error) {
	value0, err := b.base.ToAllocationManageMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Manage invokes the upstream API with library-owned builders and result handling.
func (a *API) Manage(ctx context.Context, opts ManageOpts, options ...ManageOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Manage", "allocations", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Manage", "allocations", err)
		return err
	}
	_opts := manageOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Manage", "allocations", upstream.Manage(ctx, a.client, _opts).ExtractErr())
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToAllocationUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToAllocationUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, consumerUUID string, opts UpdateOpts, options ...UpdateOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "allocations", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "allocations", err)
		return err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("Update", "allocations", upstream.Update(ctx, a.client, consumerUUID, _opts).ExtractErr())
}
