// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package trunks

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/trunks"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AddSubportsOpts = upstream.AddSubportsOpts
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type GetSubportsResult = upstream.GetSubportsResult
type ListOpts = upstream.ListOpts
type RemoveSubport = upstream.RemoveSubport
type RemoveSubportsOpts = upstream.RemoveSubportsOpts

const StatusActive = upstream.StatusActive
const StatusBuild = upstream.StatusBuild
const StatusDegraded = upstream.StatusDegraded
const StatusDown = upstream.StatusDown
const StatusError = upstream.StatusError

type Subport = upstream.Subport
type Trunk = upstream.Trunk
type TrunkPage = upstream.TrunkPage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type UpdateSubportsResult = upstream.UpdateSubportsResult
type AddSubportsOption = request.Option[AddSubportsOpts]

func WithAddSubportsOptions(value AddSubportsOpts) AddSubportsOption {
	return request.WithOptions(value)
}
func WithAddSubportsField(key string, value any) AddSubportsOption {
	return request.WithField[AddSubportsOpts](key, value)
}

type addSubportsOptsBuilder struct {
	base   AddSubportsOpts
	config request.Config[AddSubportsOpts]
}

func (b addSubportsOptsBuilder) ToTrunkAddSubportsMap() (map[string]any, error) {
	body, err := b.base.ToTrunkAddSubportsMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// AddSubports invokes the upstream API with library-owned builders and result handling.
func (a *API) AddSubports(ctx context.Context, id string, opts AddSubportsOpts, options ...AddSubportsOption) (*Trunk, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Trunk
		return zero0, err
	}
	_opts := addSubportsOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.AddSubports(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("AddSubports", "trunks", err)
	return value0, err
}

type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToTrunkCreateMap() (map[string]any, error) {
	body, err := b.base.ToTrunkCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Trunk, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Trunk
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "trunks", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "trunks", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Trunk, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "trunks", err)
	return value0, err
}

// GetSubports invokes the upstream API with library-owned builders and result handling.
func (a *API) GetSubports(ctx context.Context, id string) ([]Subport, error) {
	result := upstream.GetSubports(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("GetSubports", "trunks", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToTrunkListQuery() (string, error) {
	query, err := b.base.ToTrunkListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Trunk, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*Trunk, error) bool) { var zero *Trunk; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Trunk, error) {
		values, err := upstream.ExtractTrunks(page)
		return []Trunk(values), err
	})
}

type RemoveSubportsOption = request.Option[RemoveSubportsOpts]

func WithRemoveSubportsOptions(value RemoveSubportsOpts) RemoveSubportsOption {
	return request.WithOptions(value)
}
func WithRemoveSubportsField(key string, value any) RemoveSubportsOption {
	return request.WithField[RemoveSubportsOpts](key, value)
}

type removeSubportsOptsBuilder struct {
	base   RemoveSubportsOpts
	config request.Config[RemoveSubportsOpts]
}

func (b removeSubportsOptsBuilder) ToTrunkRemoveSubportsMap() (map[string]any, error) {
	body, err := b.base.ToTrunkRemoveSubportsMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// RemoveSubports invokes the upstream API with library-owned builders and result handling.
func (a *API) RemoveSubports(ctx context.Context, id string, opts RemoveSubportsOpts, options ...RemoveSubportsOption) (*Trunk, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Trunk
		return zero0, err
	}
	_opts := removeSubportsOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.RemoveSubports(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("RemoveSubports", "trunks", err)
	return value0, err
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToTrunkUpdateMap() (map[string]any, error) {
	body, err := b.base.ToTrunkUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Trunk, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Trunk
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "trunks", err)
	return value0, err
}
