// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package agents

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/agents"
	speakers "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/bgp/speakers"
	routers "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/layer3/routers"
	networks "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/networks"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type Agent = upstream.Agent
type AgentPage = upstream.AgentPage
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type ListBGPSpeakersResult = upstream.ListBGPSpeakersResult
type ListDHCPNetworksResult = upstream.ListDHCPNetworksResult
type ListL3RoutersResult = upstream.ListL3RoutersResult
type ListOpts = upstream.ListOpts
type RemoveBGPSpeakerResult = upstream.RemoveBGPSpeakerResult
type RemoveDHCPNetworkResult = upstream.RemoveDHCPNetworkResult
type RemoveL3RouterResult = upstream.RemoveL3RouterResult
type ScheduleBGPSpeakerOpts = upstream.ScheduleBGPSpeakerOpts
type ScheduleBGPSpeakerResult = upstream.ScheduleBGPSpeakerResult
type ScheduleDHCPNetworkOpts = upstream.ScheduleDHCPNetworkOpts
type ScheduleDHCPNetworkResult = upstream.ScheduleDHCPNetworkResult
type ScheduleL3RouterOpts = upstream.ScheduleL3RouterOpts
type ScheduleL3RouterResult = upstream.ScheduleL3RouterResult
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "agents", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Agent, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "agents", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToAgentListQuery() (string, error) {
	query, err := b.base.ToAgentListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Agent, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*Agent, error) bool) { var zero *Agent; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Agent, error) {
		values, err := upstream.ExtractAgents(page)
		return []Agent(values), err
	})
}

// ListBGPSpeakers invokes the upstream API with library-owned builders and result handling.
func (a *API) ListBGPSpeakers(ctx context.Context, agentID string) iter.Seq2[*speakers.BGPSpeaker, error] {
	return resource.Stream(ctx, upstream.ListBGPSpeakers(a.client, agentID), func(page pagination.Page) ([]speakers.BGPSpeaker, error) {
		values, err := upstream.ExtractBGPSpeakers(page)
		return []speakers.BGPSpeaker(values), err
	})
}

// ListDHCPNetworks invokes the upstream API with library-owned builders and result handling.
func (a *API) ListDHCPNetworks(ctx context.Context, id string) ([]networks.Network, error) {
	result := upstream.ListDHCPNetworks(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("ListDHCPNetworks", "agents", err)
	return value0, err
}

// ListDRAgentHostingBGPSpeakers invokes the upstream API with library-owned builders and result handling.
func (a *API) ListDRAgentHostingBGPSpeakers(ctx context.Context, bgpSpeakerID string) iter.Seq2[*Agent, error] {
	return resource.Stream(ctx, upstream.ListDRAgentHostingBGPSpeakers(a.client, bgpSpeakerID), func(page pagination.Page) ([]Agent, error) {
		values, err := upstream.ExtractAgents(page)
		return []Agent(values), err
	})
}

// ListL3Routers invokes the upstream API with library-owned builders and result handling.
func (a *API) ListL3Routers(ctx context.Context, id string) ([]routers.Router, error) {
	result := upstream.ListL3Routers(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("ListL3Routers", "agents", err)
	return value0, err
}

// RemoveBGPSpeaker invokes the upstream API with library-owned builders and result handling.
func (a *API) RemoveBGPSpeaker(ctx context.Context, agentID string, speakerID string) error {
	return request.Wrap("RemoveBGPSpeaker", "agents", upstream.RemoveBGPSpeaker(ctx, a.client, agentID, speakerID).ExtractErr())
}

// RemoveDHCPNetwork invokes the upstream API with library-owned builders and result handling.
func (a *API) RemoveDHCPNetwork(ctx context.Context, id string, networkID string) error {
	return request.Wrap("RemoveDHCPNetwork", "agents", upstream.RemoveDHCPNetwork(ctx, a.client, id, networkID).ExtractErr())
}

// RemoveL3Router invokes the upstream API with library-owned builders and result handling.
func (a *API) RemoveL3Router(ctx context.Context, id string, routerID string) error {
	return request.Wrap("RemoveL3Router", "agents", upstream.RemoveL3Router(ctx, a.client, id, routerID).ExtractErr())
}

type ScheduleBGPSpeakerOption = request.Option[ScheduleBGPSpeakerOpts]

func WithScheduleBGPSpeakerOptions(value ScheduleBGPSpeakerOpts) ScheduleBGPSpeakerOption {
	return request.WithOptions(value)
}
func WithScheduleBGPSpeakerField(key string, value any) ScheduleBGPSpeakerOption {
	return request.WithField[ScheduleBGPSpeakerOpts](key, value)
}

type scheduleBGPSpeakerOptsBuilder struct {
	base   ScheduleBGPSpeakerOpts
	config request.Config[ScheduleBGPSpeakerOpts]
}

func (b scheduleBGPSpeakerOptsBuilder) ToAgentScheduleBGPSpeakerMap() (map[string]any, error) {
	body, err := b.base.ToAgentScheduleBGPSpeakerMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// ScheduleBGPSpeaker invokes the upstream API with library-owned builders and result handling.
func (a *API) ScheduleBGPSpeaker(ctx context.Context, agentID string, opts ScheduleBGPSpeakerOpts, options ...ScheduleBGPSpeakerOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := scheduleBGPSpeakerOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("ScheduleBGPSpeaker", "agents", upstream.ScheduleBGPSpeaker(ctx, a.client, agentID, _opts).ExtractErr())
}

type ScheduleDHCPNetworkOption = request.Option[ScheduleDHCPNetworkOpts]

func WithScheduleDHCPNetworkOptions(value ScheduleDHCPNetworkOpts) ScheduleDHCPNetworkOption {
	return request.WithOptions(value)
}
func WithScheduleDHCPNetworkField(key string, value any) ScheduleDHCPNetworkOption {
	return request.WithField[ScheduleDHCPNetworkOpts](key, value)
}

type scheduleDHCPNetworkOptsBuilder struct {
	base   ScheduleDHCPNetworkOpts
	config request.Config[ScheduleDHCPNetworkOpts]
}

func (b scheduleDHCPNetworkOptsBuilder) ToAgentScheduleDHCPNetworkMap() (map[string]any, error) {
	body, err := b.base.ToAgentScheduleDHCPNetworkMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// ScheduleDHCPNetwork invokes the upstream API with library-owned builders and result handling.
func (a *API) ScheduleDHCPNetwork(ctx context.Context, id string, opts ScheduleDHCPNetworkOpts, options ...ScheduleDHCPNetworkOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := scheduleDHCPNetworkOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("ScheduleDHCPNetwork", "agents", upstream.ScheduleDHCPNetwork(ctx, a.client, id, _opts).ExtractErr())
}

type ScheduleL3RouterOption = request.Option[ScheduleL3RouterOpts]

func WithScheduleL3RouterOptions(value ScheduleL3RouterOpts) ScheduleL3RouterOption {
	return request.WithOptions(value)
}
func WithScheduleL3RouterField(key string, value any) ScheduleL3RouterOption {
	return request.WithField[ScheduleL3RouterOpts](key, value)
}

type scheduleL3RouterOptsBuilder struct {
	base   ScheduleL3RouterOpts
	config request.Config[ScheduleL3RouterOpts]
}

func (b scheduleL3RouterOptsBuilder) ToAgentScheduleL3RouterMap() (map[string]any, error) {
	body, err := b.base.ToAgentScheduleL3RouterMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// ScheduleL3Router invokes the upstream API with library-owned builders and result handling.
func (a *API) ScheduleL3Router(ctx context.Context, id string, opts ScheduleL3RouterOpts, options ...ScheduleL3RouterOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := scheduleL3RouterOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("ScheduleL3Router", "agents", upstream.ScheduleL3Router(ctx, a.client, id, _opts).ExtractErr())
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToAgentUpdateMap() (map[string]any, error) {
	body, err := b.base.ToAgentUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Agent, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Agent
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "agents", err)
	return value0, err
}
