// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package imagedata

import (
	context "context"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/image/v2/imagedata"
	io "io"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type DownloadResult = upstream.DownloadResult
type StageResult = upstream.StageResult
type UploadResult = upstream.UploadResult

// Download invokes the upstream API with library-owned builders and result handling.
func (a *API) Download(ctx context.Context, id string) (*request.Download[io.ReadCloser], error) {
	result := upstream.Download(ctx, a.client, id)
	header, err := result.Extract()
	return request.OpenDownload(result.Body, header, request.Wrap("Download", "imagedata", err))
}

// Stage invokes the upstream API with library-owned builders and result handling.
func (a *API) Stage(ctx context.Context, id string, data io.Reader) error {
	return request.Wrap("Stage", "imagedata", upstream.Stage(ctx, a.client, id, data).ExtractErr())
}

// Upload invokes the upstream API with library-owned builders and result handling.
func (a *API) Upload(ctx context.Context, id string, data io.Reader) error {
	return request.Wrap("Upload", "imagedata", upstream.Upload(ctx, a.client, id, data).ExtractErr())
}
