// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package peers

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/bgp/peers"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[BGPPeer]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type BGPPeer = upstream.BGPPeer
type BGPPeerPage = upstream.BGPPeerPage
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToPeerCreateMap() (map[string]any, error) {
	value0, err := b.base.ToPeerCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*BGPPeer, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "peers", err)
		var zero0 *BGPPeer
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "peers", err)
		var zero0 *BGPPeer
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "peers", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, bgpPeerID string) error {
	return request.Wrap("Delete", "peers", upstream.Delete(ctx, a.client, bgpPeerID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*BGPPeer, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "peers", err)
	return value0, err
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context) iter.Seq2[*BGPPeer, error] {
	return a.listWithControl(ctx, resource.ListControl{})
}

func (a *API) listWithControl(ctx context.Context, control resource.ListControl) iter.Seq2[*BGPPeer, error] {
	return resource.StreamWithControl(ctx, upstream.List(a.client), func(page pagination.Page) ([]BGPPeer, error) {
		values, err := upstream.ExtractBGPPeers(page)
		return []BGPPeer(values), err
	}, control)
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToPeerUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToPeerUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, bgpPeerID string, opts UpdateOpts, options ...UpdateOption) (*BGPPeer, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "peers", err)
		var zero0 *BGPPeer
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "peers", err)
		var zero0 *BGPPeer
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, bgpPeerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "peers", err)
	return value0, err
}
