// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package hypervisors

import (
	context "context"
	fmt "fmt"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	strings "strings"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Hypervisor] {
	return resource.NewCollection(resource.Adapter[Hypervisor]{
		Kind:   "hypervisors",
		Get:    func(ctx context.Context, id string) (*Hypervisor, error) { return a.Get(ctx, string(id)) },
		ID:     func(v *Hypervisor) string { return fmt.Sprint(v.ID) },
		Status: func(v *Hypervisor) string { return fmt.Sprint(v.Status) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Iterate: func(ctx context.Context, q url.Values) iter.Seq2[*Hypervisor, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := make([]ListOption, 0, len(q))
			for key, values := range q {
				for _, value := range values {
					options = append(options, WithListQuery(key, value))
				}
			}
			return a.List(ctx, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Hypervisor, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Hypervisor, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Hypervisor, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
