// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package speakers

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/bgp/speakers"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AddBGPPeerOpts = upstream.AddBGPPeerOpts
type AddBGPPeerResult = upstream.AddBGPPeerResult
type AddGatewayNetworkOpts = upstream.AddGatewayNetworkOpts
type AddGatewayNetworkResult = upstream.AddGatewayNetworkResult
type AdvertisedRoute = upstream.AdvertisedRoute
type AdvertisedRoutePage = upstream.AdvertisedRoutePage
type BGPSpeaker = upstream.BGPSpeaker
type BGPSpeakerPage = upstream.BGPSpeakerPage
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type RemoveBGPPeerOpts = upstream.RemoveBGPPeerOpts
type RemoveBGPPeerResult = upstream.RemoveBGPPeerResult
type RemoveGatewayNetworkOpts = upstream.RemoveGatewayNetworkOpts
type RemoveGatewayNetworkResult = upstream.RemoveGatewayNetworkResult
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type AddBGPPeerOption = request.Option[AddBGPPeerOpts]

func WithAddBGPPeerOptions(value AddBGPPeerOpts) AddBGPPeerOption { return request.WithOptions(value) }
func WithAddBGPPeerField(key string, value any) AddBGPPeerOption {
	return request.WithField[AddBGPPeerOpts](key, value)
}

type addBGPPeerOptsBuilder struct {
	base   AddBGPPeerOpts
	config request.Config[AddBGPPeerOpts]
}

func (b addBGPPeerOptsBuilder) ToBGPSpeakerAddBGPPeerMap() (map[string]any, error) {
	body, err := b.base.ToBGPSpeakerAddBGPPeerMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// AddBGPPeer invokes the upstream API with library-owned builders and result handling.
func (a *API) AddBGPPeer(ctx context.Context, bgpSpeakerID string, opts AddBGPPeerOpts, options ...AddBGPPeerOption) (*AddBGPPeerOpts, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *AddBGPPeerOpts
		return zero0, err
	}
	_opts := addBGPPeerOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.AddBGPPeer(ctx, a.client, bgpSpeakerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("AddBGPPeer", "speakers", err)
	return value0, err
}

type AddGatewayNetworkOption = request.Option[AddGatewayNetworkOpts]

func WithAddGatewayNetworkOptions(value AddGatewayNetworkOpts) AddGatewayNetworkOption {
	return request.WithOptions(value)
}
func WithAddGatewayNetworkField(key string, value any) AddGatewayNetworkOption {
	return request.WithField[AddGatewayNetworkOpts](key, value)
}

type addGatewayNetworkOptsBuilder struct {
	base   AddGatewayNetworkOpts
	config request.Config[AddGatewayNetworkOpts]
}

func (b addGatewayNetworkOptsBuilder) ToBGPSpeakerAddGatewayNetworkMap() (map[string]any, error) {
	body, err := b.base.ToBGPSpeakerAddGatewayNetworkMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// AddGatewayNetwork invokes the upstream API with library-owned builders and result handling.
func (a *API) AddGatewayNetwork(ctx context.Context, bgpSpeakerID string, opts AddGatewayNetworkOpts, options ...AddGatewayNetworkOption) (*AddGatewayNetworkOpts, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *AddGatewayNetworkOpts
		return zero0, err
	}
	_opts := addGatewayNetworkOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.AddGatewayNetwork(ctx, a.client, bgpSpeakerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("AddGatewayNetwork", "speakers", err)
	return value0, err
}

type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToSpeakerCreateMap() (map[string]any, error) {
	body, err := b.base.ToSpeakerCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*BGPSpeaker, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *BGPSpeaker
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "speakers", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, speakerID string) error {
	return request.Wrap("Delete", "speakers", upstream.Delete(ctx, a.client, speakerID).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*BGPSpeaker, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "speakers", err)
	return value0, err
}

// GetAdvertisedRoutes invokes the upstream API with library-owned builders and result handling.
func (a *API) GetAdvertisedRoutes(ctx context.Context, bgpSpeakerID string) iter.Seq2[*AdvertisedRoute, error] {
	return resource.Stream(ctx, upstream.GetAdvertisedRoutes(a.client, bgpSpeakerID), func(page pagination.Page) ([]AdvertisedRoute, error) {
		values, err := upstream.ExtractAdvertisedRoutes(page)
		return []AdvertisedRoute(values), err
	})
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context) iter.Seq2[*BGPSpeaker, error] {
	return resource.Stream(ctx, upstream.List(a.client), func(page pagination.Page) ([]BGPSpeaker, error) {
		values, err := upstream.ExtractBGPSpeakers(page)
		return []BGPSpeaker(values), err
	})
}

type RemoveBGPPeerOption = request.Option[RemoveBGPPeerOpts]

func WithRemoveBGPPeerOptions(value RemoveBGPPeerOpts) RemoveBGPPeerOption {
	return request.WithOptions(value)
}
func WithRemoveBGPPeerField(key string, value any) RemoveBGPPeerOption {
	return request.WithField[RemoveBGPPeerOpts](key, value)
}

type removeBGPPeerOptsBuilder struct {
	base   RemoveBGPPeerOpts
	config request.Config[RemoveBGPPeerOpts]
}

func (b removeBGPPeerOptsBuilder) ToBGPSpeakerRemoveBGPPeerMap() (map[string]any, error) {
	body, err := b.base.ToBGPSpeakerRemoveBGPPeerMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// RemoveBGPPeer invokes the upstream API with library-owned builders and result handling.
func (a *API) RemoveBGPPeer(ctx context.Context, bgpSpeakerID string, opts RemoveBGPPeerOpts, options ...RemoveBGPPeerOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := removeBGPPeerOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("RemoveBGPPeer", "speakers", upstream.RemoveBGPPeer(ctx, a.client, bgpSpeakerID, _opts).ExtractErr())
}

type RemoveGatewayNetworkOption = request.Option[RemoveGatewayNetworkOpts]

func WithRemoveGatewayNetworkOptions(value RemoveGatewayNetworkOpts) RemoveGatewayNetworkOption {
	return request.WithOptions(value)
}
func WithRemoveGatewayNetworkField(key string, value any) RemoveGatewayNetworkOption {
	return request.WithField[RemoveGatewayNetworkOpts](key, value)
}

type removeGatewayNetworkOptsBuilder struct {
	base   RemoveGatewayNetworkOpts
	config request.Config[RemoveGatewayNetworkOpts]
}

func (b removeGatewayNetworkOptsBuilder) ToBGPSpeakerRemoveGatewayNetworkMap() (map[string]any, error) {
	body, err := b.base.ToBGPSpeakerRemoveGatewayNetworkMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// RemoveGatewayNetwork invokes the upstream API with library-owned builders and result handling.
func (a *API) RemoveGatewayNetwork(ctx context.Context, bgpSpeakerID string, opts RemoveGatewayNetworkOpts, options ...RemoveGatewayNetworkOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return err
	}
	_opts := removeGatewayNetworkOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("RemoveGatewayNetwork", "speakers", upstream.RemoveGatewayNetwork(ctx, a.client, bgpSpeakerID, _opts).ExtractErr())
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToSpeakerUpdateMap() (map[string]any, error) {
	body, err := b.base.ToSpeakerUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, speakerID string, opts UpdateOpts, options ...UpdateOption) (*BGPSpeaker, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *BGPSpeaker
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, speakerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "speakers", err)
	return value0, err
}
