// Code generated by sdkgen; DO NOT EDIT.
package v1

import (
	gophercloud "github.com/gophercloud/gophercloud/v2"
	resource0 "gophercloudsdk/baremetal/v1/allocations"
	resource1 "gophercloudsdk/baremetal/v1/conductors"
	resource2 "gophercloudsdk/baremetal/v1/drivers"
	resource3 "gophercloudsdk/baremetal/v1/nodes"
	resource4 "gophercloudsdk/baremetal/v1/ports"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client      *gophercloud.ServiceClient
	Allocations *resource0.API
	Conductors  *resource1.API
	Drivers     *resource2.API
	Nodes       *resource3.API
	Ports       *resource4.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		Allocations: resource0.New(client),
		Conductors:  resource1.New(client),
		Drivers:     resource2.New(client),
		Nodes:       resource3.New(client),
		Ports:       resource4.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
