// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package backups

import (
	context "context"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/blockstorage/v3/backups"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
	maps "maps"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[Backup]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type Backup = upstream.Backup
type BackupPage = upstream.BackupPage
type BackupRecord = upstream.BackupRecord
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type ExportResult = upstream.ExportResult
type ForceDeleteResult = upstream.ForceDeleteResult
type GetResult = upstream.GetResult
type ImportBackup = upstream.ImportBackup
type ImportOpts = upstream.ImportOpts
type ImportResponse = upstream.ImportResponse
type ImportResult = upstream.ImportResult
type ListDetailOpts = upstream.ListDetailOpts
type ListOpts = upstream.ListOpts
type ResetStatusOpts = upstream.ResetStatusOpts
type ResetStatusResult = upstream.ResetStatusResult
type Restore = upstream.Restore
type RestoreOpts = upstream.RestoreOpts
type RestoreResult = upstream.RestoreResult
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToBackupCreateMap() (map[string]any, error) {
	value0, err := b.base.ToBackupCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Backup, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "backups", err)
		var zero0 *Backup
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "backups", err)
		var zero0 *Backup
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "backups", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "backups", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Export invokes the upstream API with library-owned builders and result handling.
func (a *API) Export(ctx context.Context, id string) (*BackupRecord, error) {
	result := upstream.Export(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Export", "backups", err)
	return value0, err
}

// ForceDelete invokes the upstream API with library-owned builders and result handling.
func (a *API) ForceDelete(ctx context.Context, id string) error {
	return request.Wrap("ForceDelete", "backups", upstream.ForceDelete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Backup, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "backups", err)
	return value0, err
}

type ImportOption = request.Option[ImportOpts]

func WithImportOptions(value ImportOpts) ImportOption { return request.WithOptions(value) }
func WithImportField(key string, value any) ImportOption {
	return request.WithField[ImportOpts](key, value)
}

type importOptsBuilder struct {
	base   ImportOpts
	config request.Config[ImportOpts]
}

func (b importOptsBuilder) ToBackupImportMap() (map[string]any, error) {
	value0, err := b.base.ToBackupImportMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Import invokes the upstream API with library-owned builders and result handling.
func (a *API) Import(ctx context.Context, opts ImportOpts, options ...ImportOption) (*ImportResponse, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Import", "backups", err)
		var zero0 *ImportResponse
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Import", "backups", err)
		var zero0 *ImportResponse
		return zero0, err
	}
	_opts := importOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Import(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Import", "backups", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToBackupListQuery() (string, error) {
	value0, err := b.base.ToBackupListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Backup, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "backups", err)
		return func(yield func(*Backup, error) bool) { var zero *Backup; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "backups", err)
		return func(yield func(*Backup, error) bool) { var zero *Backup; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Backup, error) {
		values, err := upstream.ExtractBackups(page)
		return []Backup(values), err
	})
}

type ListDetailOption = request.Option[ListDetailOpts]

func WithListDetailOptions(value ListDetailOpts) ListDetailOption { return request.WithOptions(value) }
func WithListDetailQuery(key, value string) ListDetailOption {
	return request.WithQuery[ListDetailOpts](key, value)
}

type listDetailOptsBuilder struct {
	base   ListDetailOpts
	config request.Config[ListDetailOpts]
}

func (b listDetailOptsBuilder) ToBackupListDetailQuery() (string, error) {
	value0, err := b.base.ToBackupListDetailQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// ListDetail invokes the upstream API with library-owned builders and result handling.
func (a *API) ListDetail(ctx context.Context, options ...ListDetailOption) iter.Seq2[*Backup, error] {
	return a.listDetailWithControl(ctx, resource.ListControl{}, options...)
}

func (a *API) listDetailWithControl(ctx context.Context, control resource.ListControl, options ...ListDetailOption) iter.Seq2[*Backup, error] {
	var opts ListDetailOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ListDetail", "backups", err)
		return func(yield func(*Backup, error) bool) { var zero *Backup; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("ListDetail", "backups", err)
		return func(yield func(*Backup, error) bool) { var zero *Backup; yield(zero, err) }
	}
	_opts := listDetailOptsBuilder{base: cfg.Options, config: cfg}
	return resource.StreamWithControl(ctx, upstream.ListDetail(a.client, _opts), func(page pagination.Page) ([]Backup, error) {
		values, err := upstream.ExtractBackups(page)
		return []Backup(values), err
	}, control)
}

type ResetStatusOption = request.Option[ResetStatusOpts]

func WithResetStatusOptions(value ResetStatusOpts) ResetStatusOption {
	return request.WithOptions(value)
}
func WithResetStatusField(key string, value any) ResetStatusOption {
	return request.WithField[ResetStatusOpts](key, value)
}

type resetStatusOptsBuilder struct {
	base   ResetStatusOpts
	config request.Config[ResetStatusOpts]
}

func (b resetStatusOptsBuilder) ToBackupResetStatusMap() (map[string]any, error) {
	value0, err := b.base.ToBackupResetStatusMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// ResetStatus invokes the upstream API with library-owned builders and result handling.
func (a *API) ResetStatus(ctx context.Context, id string, opts ResetStatusOpts, options ...ResetStatusOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ResetStatus", "backups", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("ResetStatus", "backups", err)
		return err
	}
	_opts := resetStatusOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("ResetStatus", "backups", upstream.ResetStatus(ctx, a.client, id, _opts).ExtractErr())
}

type RestoreFromBackupOption = request.Option[RestoreOpts]

func WithRestoreFromBackupOptions(value RestoreOpts) RestoreFromBackupOption {
	return request.WithOptions(value)
}
func WithRestoreFromBackupField(key string, value any) RestoreFromBackupOption {
	return request.WithField[RestoreOpts](key, value)
}

type restoreFromBackupOptsBuilder struct {
	base   RestoreOpts
	config request.Config[RestoreOpts]
}

func (b restoreFromBackupOptsBuilder) ToRestoreMap() (map[string]any, error) {
	value0, err := b.base.ToRestoreMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// RestoreFromBackup invokes the upstream API with library-owned builders and result handling.
func (a *API) RestoreFromBackup(ctx context.Context, id string, opts RestoreOpts, options ...RestoreFromBackupOption) (*Restore, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("RestoreFromBackup", "backups", err)
		var zero0 *Restore
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("RestoreFromBackup", "backups", err)
		var zero0 *Restore
		return zero0, err
	}
	_opts := restoreFromBackupOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.RestoreFromBackup(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("RestoreFromBackup", "backups", err)
	return value0, err
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToBackupUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToBackupUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	if b.base.Metadata != nil {
		value0["metadata"] = maps.Clone(b.base.Metadata)
	}
	value0 = map[string]any{"backup": value0}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*Backup, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "backups", err)
		var zero0 *Backup
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "backups", err)
		var zero0 *Backup
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "backups", err)
	return value0, err
}
