// Code generated by sdkgen; DO NOT EDIT.
package v1

import (
	resource0 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/actions"
	resource1 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/buildinfo"
	resource2 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/clusterattributes"
	resource3 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/clusterpolicies"
	resource4 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/clusters"
	resource5 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/events"
	resource6 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/nodes"
	resource7 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/policies"
	resource8 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/policytypes"
	resource9 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/profiles"
	resource10 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/profiletypes"
	resource11 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/receivers"
	resource12 "github.com/JSYoo5B/gophercloudsdk/clustering/v1/services"
	gophercloud "github.com/gophercloud/gophercloud/v2"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client            *gophercloud.ServiceClient
	Actions           *resource0.API
	BuildInfo         *resource1.API
	ClusterAttributes *resource2.API
	ClusterPolicies   *resource3.API
	Clusters          *resource4.API
	Events            *resource5.API
	Nodes             *resource6.API
	Policies          *resource7.API
	PolicyTypes       *resource8.API
	Profiles          *resource9.API
	ProfileTypes      *resource10.API
	Receivers         *resource11.API
	Services          *resource12.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		Actions:           resource0.New(client),
		BuildInfo:         resource1.New(client),
		ClusterAttributes: resource2.New(client),
		ClusterPolicies:   resource3.New(client),
		Clusters:          resource4.New(client),
		Events:            resource5.New(client),
		Nodes:             resource6.New(client),
		Policies:          resource7.New(client),
		PolicyTypes:       resource8.New(client),
		Profiles:          resource9.New(client),
		ProfileTypes:      resource10.New(client),
		Receivers:         resource11.New(client),
		Services:          resource12.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
