// Code generated by sdkgen; DO NOT EDIT.
package v1

import (
	gophercloud "github.com/gophercloud/gophercloud/v2"
	resource0 "gophercloudsdk/clustering/v1/actions"
	resource1 "gophercloudsdk/clustering/v1/buildinfo"
	resource2 "gophercloudsdk/clustering/v1/events"
	resource3 "gophercloudsdk/clustering/v1/policytypes"
	resource4 "gophercloudsdk/clustering/v1/profiletypes"
	resource5 "gophercloudsdk/clustering/v1/services"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client       *gophercloud.ServiceClient
	Actions      *resource0.API
	BuildInfo    *resource1.API
	Events       *resource2.API
	PolicyTypes  *resource3.API
	ProfileTypes *resource4.API
	Services     *resource5.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		Actions:      resource0.New(client),
		BuildInfo:    resource1.New(client),
		Events:       resource2.New(client),
		PolicyTypes:  resource3.New(client),
		ProfileTypes: resource4.New(client),
		Services:     resource5.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
