// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package crontriggers

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/workflow/v2/crontriggers"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[CronTrigger]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type CronTrigger = upstream.CronTrigger
type CronTriggerPage = upstream.CronTriggerPage
type DeleteResult = upstream.DeleteResult

const FilterEQ = upstream.FilterEQ
const FilterGT = upstream.FilterGT
const FilterGTE = upstream.FilterGTE
const FilterHas = upstream.FilterHas
const FilterIN = upstream.FilterIN
const FilterLT = upstream.FilterLT
const FilterLTE = upstream.FilterLTE
const FilterNEQ = upstream.FilterNEQ
const FilterNIN = upstream.FilterNIN

type FilterType = upstream.FilterType
type GetResult = upstream.GetResult
type ListDateFilter = upstream.ListDateFilter
type ListFilter = upstream.ListFilter
type ListIntFilter = upstream.ListIntFilter
type ListOpts = upstream.ListOpts
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToCronTriggerCreateMap() (map[string]any, error) {
	value0, err := b.base.ToCronTriggerCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*CronTrigger, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "crontriggers", err)
		var zero0 *CronTrigger
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "crontriggers", err)
		var zero0 *CronTrigger
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "crontriggers", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "crontriggers", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*CronTrigger, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "crontriggers", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToCronTriggerListQuery() (string, error) {
	value0, err := b.base.ToCronTriggerListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*CronTrigger, error] {
	return a.listWithControl(ctx, resource.ListControl{}, options...)
}

func (a *API) listWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*CronTrigger, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "crontriggers", err)
		return func(yield func(*CronTrigger, error) bool) { var zero *CronTrigger; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "crontriggers", err)
		return func(yield func(*CronTrigger, error) bool) { var zero *CronTrigger; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.StreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]CronTrigger, error) {
		values, err := upstream.ExtractCronTriggers(page)
		return []CronTrigger(values), err
	}, control)
}
