// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package attributestags

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/attributestags"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AddResult = upstream.AddResult
type ConfirmResult = upstream.ConfirmResult
type DeleteResult = upstream.DeleteResult
type ListResult = upstream.ListResult
type ReplaceAllOpts = upstream.ReplaceAllOpts
type ReplaceAllResult = upstream.ReplaceAllResult

// Add invokes the upstream API with library-owned builders and result handling.
func (a *API) Add(ctx context.Context, resourceType string, resourceID string, tag string) error {
	return request.Wrap("Add", "attributestags", upstream.Add(ctx, a.client, resourceType, resourceID, tag).ExtractErr())
}

// Confirm invokes the upstream API with library-owned builders and result handling.
func (a *API) Confirm(ctx context.Context, resourceType string, resourceID string, tag string) (bool, error) {
	result := upstream.Confirm(ctx, a.client, resourceType, resourceID, tag)
	value0, err := result.Extract()
	err = request.Wrap("Confirm", "attributestags", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, resourceType string, resourceID string, tag string) error {
	return request.Wrap("Delete", "attributestags", upstream.Delete(ctx, a.client, resourceType, resourceID, tag).ExtractErr())
}

// DeleteAll invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteAll(ctx context.Context, resourceType string, resourceID string) error {
	return request.Wrap("DeleteAll", "attributestags", upstream.DeleteAll(ctx, a.client, resourceType, resourceID).ExtractErr())
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, resourceType string, resourceID string) ([]string, error) {
	result := upstream.List(ctx, a.client, resourceType, resourceID)
	value0, err := result.Extract()
	err = request.Wrap("List", "attributestags", err)
	return value0, err
}

type ReplaceAllOption = request.Option[ReplaceAllOpts]

func WithReplaceAllOptions(value ReplaceAllOpts) ReplaceAllOption { return request.WithOptions(value) }
func WithReplaceAllField(key string, value any) ReplaceAllOption {
	return request.WithField[ReplaceAllOpts](key, value)
}

type replaceAllOptsBuilder struct {
	base   ReplaceAllOpts
	config request.Config[ReplaceAllOpts]
}

func (b replaceAllOptsBuilder) ToAttributeTagsReplaceAllMap() (map[string]any, error) {
	value0, err := b.base.ToAttributeTagsReplaceAllMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// ReplaceAll invokes the upstream API with library-owned builders and result handling.
func (a *API) ReplaceAll(ctx context.Context, resourceType string, resourceID string, opts ReplaceAllOpts, options ...ReplaceAllOption) ([]string, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ReplaceAll", "attributestags", err)
		var zero0 []string
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("ReplaceAll", "attributestags", err)
		var zero0 []string
		return zero0, err
	}
	_opts := replaceAllOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.ReplaceAll(ctx, a.client, resourceType, resourceID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("ReplaceAll", "attributestags", err)
	return value0, err
}
