// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package quotas

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/containerinfra/v1/quotas"
	request "gophercloudsdk/request"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type Quotas = upstream.Quotas
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToQuotaCreateMap() (map[string]any, error) {
	body, err := b.base.ToQuotaCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Quotas, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *Quotas
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "quotas", err)
	return value0, err
}
