// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package users

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/identity/v2/users"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[User]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CommonOpts = upstream.CommonOpts
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type Role = upstream.Role
type RolePage = upstream.RolePage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type User = upstream.User
type UserPage = upstream.UserPage
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToUserCreateMap() (map[string]any, error) {
	body, err := b.base.ToUserCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*User, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *User
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "users", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) (*User, error) {
	result := upstream.Delete(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Delete", "users", err)
	return value0, err
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*User, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "users", err)
	return value0, err
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context) iter.Seq2[*User, error] {
	return resource.Stream(ctx, upstream.List(a.client), func(page pagination.Page) ([]User, error) {
		values, err := upstream.ExtractUsers(page)
		return []User(values), err
	})
}

// ListRoles invokes the upstream API with library-owned builders and result handling.
func (a *API) ListRoles(ctx context.Context, tenantID string, userID string) iter.Seq2[*Role, error] {
	return resource.Stream(ctx, upstream.ListRoles(a.client, tenantID, userID), func(page pagination.Page) ([]Role, error) {
		values, err := upstream.ExtractRoles(page)
		return []Role(values), err
	})
}

// ResourceURL invokes the upstream API with library-owned builders and result handling.
func (a *API) ResourceURL(ctx context.Context, id string) string {
	return upstream.ResourceURL(a.client, id)
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToUserUpdateMap() (map[string]any, error) {
	body, err := b.base.ToUserUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*User, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *User
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "users", err)
	return value0, err
}
