// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package bgpvpns

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/bgpvpns"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type BGPVPN = upstream.BGPVPN
type BGPVPNPage = upstream.BGPVPNPage
type CreateNetworkAssociationOpts = upstream.CreateNetworkAssociationOpts
type CreateNetworkAssociationResult = upstream.CreateNetworkAssociationResult
type CreateOpts = upstream.CreateOpts
type CreatePortAssociationOpts = upstream.CreatePortAssociationOpts
type CreatePortAssociationResult = upstream.CreatePortAssociationResult
type CreateResult = upstream.CreateResult
type CreateRouterAssociationOpts = upstream.CreateRouterAssociationOpts
type CreateRouterAssociationResult = upstream.CreateRouterAssociationResult
type DeleteNetworkAssociationResult = upstream.DeleteNetworkAssociationResult
type DeletePortAssociationResult = upstream.DeletePortAssociationResult
type DeleteResult = upstream.DeleteResult
type DeleteRouterAssociationResult = upstream.DeleteRouterAssociationResult
type GetNetworkAssociationResult = upstream.GetNetworkAssociationResult
type GetPortAssociationResult = upstream.GetPortAssociationResult
type GetResult = upstream.GetResult
type GetRouterAssociationResult = upstream.GetRouterAssociationResult
type ListNetworkAssociationsOpts = upstream.ListNetworkAssociationsOpts
type ListOpts = upstream.ListOpts
type ListPortAssociationsOpts = upstream.ListPortAssociationsOpts
type ListRouterAssociationsOpts = upstream.ListRouterAssociationsOpts
type NetworkAssociation = upstream.NetworkAssociation
type NetworkAssociationPage = upstream.NetworkAssociationPage
type PortAssociation = upstream.PortAssociation
type PortAssociationPage = upstream.PortAssociationPage
type PortRoutes = upstream.PortRoutes
type RouterAssociation = upstream.RouterAssociation
type RouterAssociationPage = upstream.RouterAssociationPage
type UpdateOpts = upstream.UpdateOpts
type UpdatePortAssociationOpts = upstream.UpdatePortAssociationOpts
type UpdatePortAssociationResult = upstream.UpdatePortAssociationResult
type UpdateResult = upstream.UpdateResult
type UpdateRouterAssociationOpts = upstream.UpdateRouterAssociationOpts
type UpdateRouterAssociationResult = upstream.UpdateRouterAssociationResult
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToBGPVPNCreateMap() (map[string]any, error) {
	body, err := b.base.ToBGPVPNCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*BGPVPN, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *BGPVPN
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "bgpvpns", err)
	return value0, err
}

type CreateNetworkAssociationOption = request.Option[CreateNetworkAssociationOpts]

func WithCreateNetworkAssociationOptions(value CreateNetworkAssociationOpts) CreateNetworkAssociationOption {
	return request.WithOptions(value)
}
func WithCreateNetworkAssociationField(key string, value any) CreateNetworkAssociationOption {
	return request.WithField[CreateNetworkAssociationOpts](key, value)
}

type createNetworkAssociationOptsBuilder struct {
	base   CreateNetworkAssociationOpts
	config request.Config[CreateNetworkAssociationOpts]
}

func (b createNetworkAssociationOptsBuilder) ToNetworkAssociationCreateMap() (map[string]interface{}, error) {
	body, err := b.base.ToNetworkAssociationCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// CreateNetworkAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateNetworkAssociation(ctx context.Context, id string, opts CreateNetworkAssociationOpts, options ...CreateNetworkAssociationOption) (*NetworkAssociation, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *NetworkAssociation
		return zero0, err
	}
	_opts := createNetworkAssociationOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateNetworkAssociation(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("CreateNetworkAssociation", "bgpvpns", err)
	return value0, err
}

type CreatePortAssociationOption = request.Option[CreatePortAssociationOpts]

func WithCreatePortAssociationOptions(value CreatePortAssociationOpts) CreatePortAssociationOption {
	return request.WithOptions(value)
}
func WithCreatePortAssociationField(key string, value any) CreatePortAssociationOption {
	return request.WithField[CreatePortAssociationOpts](key, value)
}

type createPortAssociationOptsBuilder struct {
	base   CreatePortAssociationOpts
	config request.Config[CreatePortAssociationOpts]
}

func (b createPortAssociationOptsBuilder) ToPortAssociationCreateMap() (map[string]interface{}, error) {
	body, err := b.base.ToPortAssociationCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// CreatePortAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) CreatePortAssociation(ctx context.Context, id string, opts CreatePortAssociationOpts, options ...CreatePortAssociationOption) (*PortAssociation, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *PortAssociation
		return zero0, err
	}
	_opts := createPortAssociationOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreatePortAssociation(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("CreatePortAssociation", "bgpvpns", err)
	return value0, err
}

type CreateRouterAssociationOption = request.Option[CreateRouterAssociationOpts]

func WithCreateRouterAssociationOptions(value CreateRouterAssociationOpts) CreateRouterAssociationOption {
	return request.WithOptions(value)
}
func WithCreateRouterAssociationField(key string, value any) CreateRouterAssociationOption {
	return request.WithField[CreateRouterAssociationOpts](key, value)
}

type createRouterAssociationOptsBuilder struct {
	base   CreateRouterAssociationOpts
	config request.Config[CreateRouterAssociationOpts]
}

func (b createRouterAssociationOptsBuilder) ToRouterAssociationCreateMap() (map[string]interface{}, error) {
	body, err := b.base.ToRouterAssociationCreateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// CreateRouterAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateRouterAssociation(ctx context.Context, id string, opts CreateRouterAssociationOpts, options ...CreateRouterAssociationOption) (*RouterAssociation, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *RouterAssociation
		return zero0, err
	}
	_opts := createRouterAssociationOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateRouterAssociation(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("CreateRouterAssociation", "bgpvpns", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "bgpvpns", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// DeleteNetworkAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteNetworkAssociation(ctx context.Context, bgpVpnID string, id string) error {
	return request.Wrap("DeleteNetworkAssociation", "bgpvpns", upstream.DeleteNetworkAssociation(ctx, a.client, bgpVpnID, id).ExtractErr())
}

// DeletePortAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) DeletePortAssociation(ctx context.Context, bgpVpnID string, id string) error {
	return request.Wrap("DeletePortAssociation", "bgpvpns", upstream.DeletePortAssociation(ctx, a.client, bgpVpnID, id).ExtractErr())
}

// DeleteRouterAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteRouterAssociation(ctx context.Context, bgpVpnID string, id string) error {
	return request.Wrap("DeleteRouterAssociation", "bgpvpns", upstream.DeleteRouterAssociation(ctx, a.client, bgpVpnID, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*BGPVPN, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "bgpvpns", err)
	return value0, err
}

// GetNetworkAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) GetNetworkAssociation(ctx context.Context, bgpVpnID string, id string) (*NetworkAssociation, error) {
	result := upstream.GetNetworkAssociation(ctx, a.client, bgpVpnID, id)
	value0, err := result.Extract()
	err = request.Wrap("GetNetworkAssociation", "bgpvpns", err)
	return value0, err
}

// GetPortAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) GetPortAssociation(ctx context.Context, bgpVpnID string, id string) (*PortAssociation, error) {
	result := upstream.GetPortAssociation(ctx, a.client, bgpVpnID, id)
	value0, err := result.Extract()
	err = request.Wrap("GetPortAssociation", "bgpvpns", err)
	return value0, err
}

// GetRouterAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) GetRouterAssociation(ctx context.Context, bgpVpnID string, id string) (*RouterAssociation, error) {
	result := upstream.GetRouterAssociation(ctx, a.client, bgpVpnID, id)
	value0, err := result.Extract()
	err = request.Wrap("GetRouterAssociation", "bgpvpns", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToBGPVPNListQuery() (string, error) {
	query, err := b.base.ToBGPVPNListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*BGPVPN, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*BGPVPN, error) bool) { var zero *BGPVPN; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]BGPVPN, error) {
		values, err := upstream.ExtractBGPVPNs(page)
		return []BGPVPN(values), err
	})
}

type ListNetworkAssociationsOption = request.Option[ListNetworkAssociationsOpts]

func WithListNetworkAssociationsOptions(value ListNetworkAssociationsOpts) ListNetworkAssociationsOption {
	return request.WithOptions(value)
}
func WithListNetworkAssociationsQuery(key, value string) ListNetworkAssociationsOption {
	return request.WithQuery[ListNetworkAssociationsOpts](key, value)
}

type listNetworkAssociationsOptsBuilder struct {
	base   ListNetworkAssociationsOpts
	config request.Config[ListNetworkAssociationsOpts]
}

func (b listNetworkAssociationsOptsBuilder) ToNetworkAssociationsListQuery() (string, error) {
	query, err := b.base.ToNetworkAssociationsListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// ListNetworkAssociations invokes the upstream API with library-owned builders and result handling.
func (a *API) ListNetworkAssociations(ctx context.Context, id string, options ...ListNetworkAssociationsOption) iter.Seq2[*NetworkAssociation, error] {
	var opts ListNetworkAssociationsOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*NetworkAssociation, error) bool) { var zero *NetworkAssociation; yield(zero, err) }
	}
	_opts := listNetworkAssociationsOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListNetworkAssociations(a.client, id, _opts), func(page pagination.Page) ([]NetworkAssociation, error) {
		values, err := upstream.ExtractNetworkAssociations(page)
		return []NetworkAssociation(values), err
	})
}

type ListPortAssociationsOption = request.Option[ListPortAssociationsOpts]

func WithListPortAssociationsOptions(value ListPortAssociationsOpts) ListPortAssociationsOption {
	return request.WithOptions(value)
}
func WithListPortAssociationsQuery(key, value string) ListPortAssociationsOption {
	return request.WithQuery[ListPortAssociationsOpts](key, value)
}

type listPortAssociationsOptsBuilder struct {
	base   ListPortAssociationsOpts
	config request.Config[ListPortAssociationsOpts]
}

func (b listPortAssociationsOptsBuilder) ToPortAssociationsListQuery() (string, error) {
	query, err := b.base.ToPortAssociationsListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// ListPortAssociations invokes the upstream API with library-owned builders and result handling.
func (a *API) ListPortAssociations(ctx context.Context, id string, options ...ListPortAssociationsOption) iter.Seq2[*PortAssociation, error] {
	var opts ListPortAssociationsOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*PortAssociation, error) bool) { var zero *PortAssociation; yield(zero, err) }
	}
	_opts := listPortAssociationsOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListPortAssociations(a.client, id, _opts), func(page pagination.Page) ([]PortAssociation, error) {
		values, err := upstream.ExtractPortAssociations(page)
		return []PortAssociation(values), err
	})
}

type ListRouterAssociationsOption = request.Option[ListRouterAssociationsOpts]

func WithListRouterAssociationsOptions(value ListRouterAssociationsOpts) ListRouterAssociationsOption {
	return request.WithOptions(value)
}
func WithListRouterAssociationsQuery(key, value string) ListRouterAssociationsOption {
	return request.WithQuery[ListRouterAssociationsOpts](key, value)
}

type listRouterAssociationsOptsBuilder struct {
	base   ListRouterAssociationsOpts
	config request.Config[ListRouterAssociationsOpts]
}

func (b listRouterAssociationsOptsBuilder) ToRouterAssociationsListQuery() (string, error) {
	query, err := b.base.ToRouterAssociationsListQuery()
	if err != nil {
		return "", err
	}
	return request.ExtendQuery(query, b.config.Query)
}

// ListRouterAssociations invokes the upstream API with library-owned builders and result handling.
func (a *API) ListRouterAssociations(ctx context.Context, id string, options ...ListRouterAssociationsOption) iter.Seq2[*RouterAssociation, error] {
	var opts ListRouterAssociationsOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		return func(yield func(*RouterAssociation, error) bool) { var zero *RouterAssociation; yield(zero, err) }
	}
	_opts := listRouterAssociationsOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListRouterAssociations(a.client, id, _opts), func(page pagination.Page) ([]RouterAssociation, error) {
		values, err := upstream.ExtractRouterAssociations(page)
		return []RouterAssociation(values), err
	})
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToBGPVPNUpdateMap() (map[string]any, error) {
	body, err := b.base.ToBGPVPNUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, id string, opts UpdateOpts, options ...UpdateOption) (*BGPVPN, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *BGPVPN
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "bgpvpns", err)
	return value0, err
}

type UpdatePortAssociationOption = request.Option[UpdatePortAssociationOpts]

func WithUpdatePortAssociationOptions(value UpdatePortAssociationOpts) UpdatePortAssociationOption {
	return request.WithOptions(value)
}
func WithUpdatePortAssociationField(key string, value any) UpdatePortAssociationOption {
	return request.WithField[UpdatePortAssociationOpts](key, value)
}

type updatePortAssociationOptsBuilder struct {
	base   UpdatePortAssociationOpts
	config request.Config[UpdatePortAssociationOpts]
}

func (b updatePortAssociationOptsBuilder) ToPortAssociationUpdateMap() (map[string]interface{}, error) {
	body, err := b.base.ToPortAssociationUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// UpdatePortAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) UpdatePortAssociation(ctx context.Context, bgpVpnID string, id string, opts UpdatePortAssociationOpts, options ...UpdatePortAssociationOption) (*PortAssociation, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *PortAssociation
		return zero0, err
	}
	_opts := updatePortAssociationOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.UpdatePortAssociation(ctx, a.client, bgpVpnID, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("UpdatePortAssociation", "bgpvpns", err)
	return value0, err
}

type UpdateRouterAssociationOption = request.Option[UpdateRouterAssociationOpts]

func WithUpdateRouterAssociationOptions(value UpdateRouterAssociationOpts) UpdateRouterAssociationOption {
	return request.WithOptions(value)
}
func WithUpdateRouterAssociationField(key string, value any) UpdateRouterAssociationOption {
	return request.WithField[UpdateRouterAssociationOpts](key, value)
}

type updateRouterAssociationOptsBuilder struct {
	base   UpdateRouterAssociationOpts
	config request.Config[UpdateRouterAssociationOpts]
}

func (b updateRouterAssociationOptsBuilder) ToRouterAssociationUpdateMap() (map[string]interface{}, error) {
	body, err := b.base.ToRouterAssociationUpdateMap()
	if err != nil {
		return nil, err
	}
	return request.MergeFieldsFor(body, b.config.Fields, b.base)
}

// UpdateRouterAssociation invokes the upstream API with library-owned builders and result handling.
func (a *API) UpdateRouterAssociation(ctx context.Context, bgpVpnID string, id string, opts UpdateRouterAssociationOpts, options ...UpdateRouterAssociationOption) (*RouterAssociation, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *RouterAssociation
		return zero0, err
	}
	_opts := updateRouterAssociationOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.UpdateRouterAssociation(ctx, a.client, bgpVpnID, id, _opts)
	value0, err := result.Extract()
	err = request.Wrap("UpdateRouterAssociation", "bgpvpns", err)
	return value0, err
}
