// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package usages

import (
	context "context"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/placement/v1/usages"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type ConsumerTypeUsage = upstream.ConsumerTypeUsage
type GetOpts = upstream.GetOpts
type GetResult = upstream.GetResult
type Usages = upstream.Usages
type UsagesPre138 = upstream.UsagesPre138
type GetOption = request.Option[GetOpts]

func WithGetOptions(value GetOpts) GetOption   { return request.WithOptions(value) }
func WithGetQuery(key, value string) GetOption { return request.WithQuery[GetOpts](key, value) }

type getOptsBuilder struct {
	base   GetOpts
	config request.Config[GetOpts]
}

func (b getOptsBuilder) ToUsagesGetQuery() (string, error) {
	value0, err := b.base.ToUsagesGetQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, options ...GetOption) (*Usages, error) {
	var opts GetOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Get", "usages", err)
		var zero0 *Usages
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("Get", "usages", err)
		var zero0 *Usages
		return zero0, err
	}
	_opts := getOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Get(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Get", "usages", err)
	return value0, err
}
