// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package pools

import (
	context "context"
	fmt "fmt"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/pools"
	nativefind "gophercloudsdk/internal/nativefind"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	strings "strings"
)

// MemberScope fixes the parent of its resources, sharing the SDK's lookup and wait policies.
type MemberScope struct {
	*resource.Collection[Member]
	api      *API
	parentID string
}

// Members resolves the parent once; explicit IDs require no lookup request.
func (a *API) Members(ctx context.Context, parent resource.Ref) (*MemberScope, error) {
	id, err := a.Resources.ResolveID(ctx, parent)
	if err != nil {
		return nil, err
	}
	scope := &MemberScope{api: a, parentID: id}
	scope.Collection = scope.newResources()
	return scope, nil
}
func (s *MemberScope) newResources() *resource.Collection[Member] {
	return resource.NewCollection(resource.Adapter[Member]{
		Kind:         "pools",
		IdentityFind: true,
		GetIdentityQuery: func(ctx context.Context, id string, q url.Values) (*Member, error) {
			var result upstream.GetMemberResult
			result.Header, result.Err = nativefind.Get(ctx, s.api.RawClient(), []string{"lbaas", "pools", s.parentID, "members", id}, q, []int{200}, &result.Body)
			return result.Extract()
		},
		Get: func(ctx context.Context, id string) (*Member, error) {
			return s.api.GetMember(ctx, s.parentID, string(id))
		},
		ID:        func(v *Member) string { return fmt.Sprint(v.ID) },
		Name:      func(v *Member) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Status:    func(v *Member) string { return fmt.Sprint(v.ProvisioningStatus) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return s.api.DeleteMember(ctx, s.parentID, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Member, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := []ListMembersOption{func(config *request.Config[ListMembersOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return s.api.listMembersWithControl(ctx, s.parentID, control, options...)
		}})
}

// FindIdentity tries an ID request before exact ID/name fallback within this collection.
func (s *MemberScope) FindIdentity(ctx context.Context, identity string, options ...resource.IdentityFindOption) (*Member, error) {
	return s.Collection.FindIdentity(ctx, identity, options...)
}

// Create applies CreateMember within the fixed parent.
func (s *MemberScope) Create(ctx context.Context, opts CreateMemberOpts, options ...CreateMemberOption) (*Member, error) {
	return s.api.CreateMember(ctx, s.parentID, opts, options...)
}

// Update applies UpdateMember within the fixed parent.
func (s *MemberScope) Update(ctx context.Context, ref resource.Ref, opts UpdateMemberOpts, options ...UpdateMemberOption) (*Member, error) {
	id, err := s.Collection.ResolveID(ctx, ref)
	if err != nil {
		var zero0 *Member
		return zero0, err
	}
	return s.api.UpdateMember(ctx, s.parentID, id, opts, options...)
}
