// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package projects

import (
	context "context"
	fmt "fmt"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/projects"
	nativefind "gophercloudsdk/internal/nativefind"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Project] {
	return resource.NewCollection(resource.Adapter[Project]{
		Kind:         "projects",
		IdentityFind: true,
		GetIdentityQuery: func(ctx context.Context, id string, q url.Values) (*Project, error) {
			var result upstream.GetResult
			result.Header, result.Err = nativefind.Get(ctx, a.RawClient(), []string{"projects", id}, q, []int{200}, &result.Body)
			return result.Extract()
		},
		Get:       func(ctx context.Context, id string) (*Project, error) { return a.Get(ctx, string(id)) },
		ID:        func(v *Project) string { return fmt.Sprint(v.ID) },
		Name:      func(v *Project) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Delete:    func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Project, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Project, error) {
	return a.Resources.Find(ctx, ref, options...)
}

// FindIdentity tries an ID request before exact ID/name fallback within this collection.
func (a *API) FindIdentity(ctx context.Context, identity string, options ...resource.IdentityFindOption) (*Project, error) {
	return a.Resources.FindIdentity(ctx, identity, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Project, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Project, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
