// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package stackresources

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/orchestration/v1/stackresources"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type FindResult = upstream.FindResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type MarkUnhealthyOpts = upstream.MarkUnhealthyOpts
type MarkUnhealthyResult = upstream.MarkUnhealthyResult
type MetadataResult = upstream.MetadataResult
type Resource = upstream.Resource
type ResourcePage = upstream.ResourcePage
type ResourceTypePage = upstream.ResourceTypePage
type ResourceTypes = upstream.ResourceTypes
type SchemaResult = upstream.SchemaResult
type TemplateResult = upstream.TemplateResult
type TypeSchema = upstream.TypeSchema

// Find invokes the upstream API with library-owned builders and result handling.
func (a *API) Find(ctx context.Context, stackName string) ([]Resource, error) {
	result := upstream.Find(ctx, a.client, stackName)
	value0, err := result.Extract()
	err = request.Wrap("Find", "stackresources", err)
	return value0, err
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, stackName string, stackID string, resourceName string) (*Resource, error) {
	result := upstream.Get(ctx, a.client, stackName, stackID, resourceName)
	value0, err := result.Extract()
	err = request.Wrap("Get", "stackresources", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToStackResourceListQuery() (string, error) {
	value0, err := b.base.ToStackResourceListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, stackName string, stackID string, options ...ListOption) iter.Seq2[*Resource, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "stackresources", err)
		return func(yield func(*Resource, error) bool) { var zero *Resource; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "stackresources", err)
		return func(yield func(*Resource, error) bool) { var zero *Resource; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.List(a.client, stackName, stackID, _opts), func(page pagination.Page) ([]Resource, error) {
		values, err := upstream.ExtractResources(page)
		return []Resource(values), err
	})
}

// ListTypes invokes the upstream API with library-owned builders and result handling.
func (a *API) ListTypes(ctx context.Context) iter.Seq2[*string, error] {
	return resource.Stream(ctx, upstream.ListTypes(a.client), func(page pagination.Page) ([]string, error) {
		values, err := upstream.ExtractResourceTypes(page)
		return []string(values), err
	})
}

type MarkUnhealthyOption = request.Option[MarkUnhealthyOpts]

func WithMarkUnhealthyOptions(value MarkUnhealthyOpts) MarkUnhealthyOption {
	return request.WithOptions(value)
}
func WithMarkUnhealthyField(key string, value any) MarkUnhealthyOption {
	return request.WithField[MarkUnhealthyOpts](key, value)
}

type markUnhealthyOptsBuilder struct {
	base   MarkUnhealthyOpts
	config request.Config[MarkUnhealthyOpts]
}

func (b markUnhealthyOptsBuilder) ToMarkUnhealthyMap() (map[string]any, error) {
	value0, err := b.base.ToMarkUnhealthyMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// MarkUnhealthy invokes the upstream API with library-owned builders and result handling.
func (a *API) MarkUnhealthy(ctx context.Context, stackName string, stackID string, resourceName string, opts MarkUnhealthyOpts, options ...MarkUnhealthyOption) error {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("MarkUnhealthy", "stackresources", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("MarkUnhealthy", "stackresources", err)
		return err
	}
	_opts := markUnhealthyOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("MarkUnhealthy", "stackresources", upstream.MarkUnhealthy(ctx, a.client, stackName, stackID, resourceName, _opts).ExtractErr())
}

// Metadata invokes the upstream API with library-owned builders and result handling.
func (a *API) Metadata(ctx context.Context, stackName string, stackID string, resourceName string) (map[string]string, error) {
	result := upstream.Metadata(ctx, a.client, stackName, stackID, resourceName)
	value0, err := result.Extract()
	err = request.Wrap("Metadata", "stackresources", err)
	return value0, err
}

// Schema invokes the upstream API with library-owned builders and result handling.
func (a *API) Schema(ctx context.Context, resourceType string) (*TypeSchema, error) {
	result := upstream.Schema(ctx, a.client, resourceType)
	value0, err := result.Extract()
	err = request.Wrap("Schema", "stackresources", err)
	return value0, err
}

// Template invokes the upstream API with library-owned builders and result handling.
func (a *API) Template(ctx context.Context, resourceType string) ([]byte, error) {
	result := upstream.Template(ctx, a.client, resourceType)
	value0, err := result.Extract()
	err = request.Wrap("Template", "stackresources", err)
	return value0, err
}
