// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package containers

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/keymanager/v1/containers"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[Container]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

const CertificateContainer = upstream.CertificateContainer

type Consumer = upstream.Consumer
type ConsumerPage = upstream.ConsumerPage
type ConsumerRef = upstream.ConsumerRef
type Container = upstream.Container
type ContainerPage = upstream.ContainerPage
type ContainerType = upstream.ContainerType
type CreateConsumerOpts = upstream.CreateConsumerOpts
type CreateConsumerResult = upstream.CreateConsumerResult
type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type CreateSecretRefResult = upstream.CreateSecretRefResult
type DeleteConsumerOpts = upstream.DeleteConsumerOpts
type DeleteConsumerResult = upstream.DeleteConsumerResult
type DeleteResult = upstream.DeleteResult
type DeleteSecretRefResult = upstream.DeleteSecretRefResult

const GenericContainer = upstream.GenericContainer

type GetResult = upstream.GetResult
type ListConsumersOpts = upstream.ListConsumersOpts
type ListOpts = upstream.ListOpts

const RSAContainer = upstream.RSAContainer

type SecretRef = upstream.SecretRef
type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToContainerCreateMap() (map[string]any, error) {
	value0, err := b.base.ToContainerCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*Container, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "containers", err)
	return value0, err
}

type CreateConsumerOption = request.Option[CreateConsumerOpts]

func WithCreateConsumerOptions(value CreateConsumerOpts) CreateConsumerOption {
	return request.WithOptions(value)
}
func WithCreateConsumerField(key string, value any) CreateConsumerOption {
	return request.WithField[CreateConsumerOpts](key, value)
}

type createConsumerOptsBuilder struct {
	base   CreateConsumerOpts
	config request.Config[CreateConsumerOpts]
}

func (b createConsumerOptsBuilder) ToContainerConsumerCreateMap() (map[string]any, error) {
	value0, err := b.base.ToContainerConsumerCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// CreateConsumer invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateConsumer(ctx context.Context, containerID string, opts CreateConsumerOpts, options ...CreateConsumerOption) (*Container, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateConsumer", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("CreateConsumer", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	_opts := createConsumerOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateConsumer(ctx, a.client, containerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("CreateConsumer", "containers", err)
	return value0, err
}

type CreateSecretRefOption = request.Option[SecretRef]

func WithCreateSecretRefOptions(value SecretRef) CreateSecretRefOption {
	return request.WithOptions(value)
}
func WithCreateSecretRefField(key string, value any) CreateSecretRefOption {
	return request.WithField[SecretRef](key, value)
}

type createSecretRefOptsBuilder struct {
	base   SecretRef
	config request.Config[SecretRef]
}

func (b createSecretRefOptsBuilder) ToContainerSecretRefMap() (map[string]any, error) {
	value0, err := b.base.ToContainerSecretRefMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// CreateSecretRef invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateSecretRef(ctx context.Context, containerID string, opts SecretRef, options ...CreateSecretRefOption) (*Container, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateSecretRef", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("CreateSecretRef", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	_opts := createSecretRefOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateSecretRef(ctx, a.client, containerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("CreateSecretRef", "containers", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "containers", upstream.Delete(ctx, a.client, id).ExtractErr())
}

type DeleteConsumerOption = request.Option[DeleteConsumerOpts]

func WithDeleteConsumerOptions(value DeleteConsumerOpts) DeleteConsumerOption {
	return request.WithOptions(value)
}
func WithDeleteConsumerField(key string, value any) DeleteConsumerOption {
	return request.WithField[DeleteConsumerOpts](key, value)
}

type deleteConsumerOptsBuilder struct {
	base   DeleteConsumerOpts
	config request.Config[DeleteConsumerOpts]
}

func (b deleteConsumerOptsBuilder) ToContainerConsumerDeleteMap() (map[string]any, error) {
	value0, err := b.base.ToContainerConsumerDeleteMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// DeleteConsumer invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteConsumer(ctx context.Context, containerID string, options ...DeleteConsumerOption) (*Container, error) {
	var opts DeleteConsumerOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("DeleteConsumer", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("DeleteConsumer", "containers", err)
		var zero0 *Container
		return zero0, err
	}
	_opts := deleteConsumerOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.DeleteConsumer(ctx, a.client, containerID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("DeleteConsumer", "containers", err)
	return value0, err
}

type DeleteSecretRefOption = request.Option[SecretRef]

func WithDeleteSecretRefOptions(value SecretRef) DeleteSecretRefOption {
	return request.WithOptions(value)
}
func WithDeleteSecretRefField(key string, value any) DeleteSecretRefOption {
	return request.WithField[SecretRef](key, value)
}

type deleteSecretRefOptsBuilder struct {
	base   SecretRef
	config request.Config[SecretRef]
}

func (b deleteSecretRefOptsBuilder) ToContainerSecretRefMap() (map[string]any, error) {
	value0, err := b.base.ToContainerSecretRefMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// DeleteSecretRef invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteSecretRef(ctx context.Context, containerID string, options ...DeleteSecretRefOption) error {
	var opts SecretRef
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("DeleteSecretRef", "containers", err)
		return err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("DeleteSecretRef", "containers", err)
		return err
	}
	_opts := deleteSecretRefOptsBuilder{base: cfg.Options, config: cfg}
	return request.Wrap("DeleteSecretRef", "containers", upstream.DeleteSecretRef(ctx, a.client, containerID, _opts).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*Container, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "containers", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToContainerListQuery() (string, error) {
	value0, err := b.base.ToContainerListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*Container, error] {
	return a.listWithControl(ctx, resource.ListControl{}, options...)
}

func (a *API) listWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*Container, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "containers", err)
		return func(yield func(*Container, error) bool) { var zero *Container; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "containers", err)
		return func(yield func(*Container, error) bool) { var zero *Container; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.StreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Container, error) {
		values, err := upstream.ExtractContainers(page)
		return []Container(values), err
	}, control)
}

type ListConsumersOption = request.Option[ListOpts]

func WithListConsumersOptions(value ListOpts) ListConsumersOption { return request.WithOptions(value) }
func WithListConsumersQuery(key, value string) ListConsumersOption {
	return request.WithQuery[ListOpts](key, value)
}

type listConsumersOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listConsumersOptsBuilder) ToContainerListConsumersQuery() (string, error) {
	value0, err := b.base.ToContainerListConsumersQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// ListConsumers invokes the upstream API with library-owned builders and result handling.
func (a *API) ListConsumers(ctx context.Context, containerID string, options ...ListConsumersOption) iter.Seq2[*Consumer, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ListConsumers", "containers", err)
		return func(yield func(*Consumer, error) bool) { var zero *Consumer; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("ListConsumers", "containers", err)
		return func(yield func(*Consumer, error) bool) { var zero *Consumer; yield(zero, err) }
	}
	_opts := listConsumersOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListConsumers(a.client, containerID, _opts), func(page pagination.Page) ([]Consumer, error) {
		values, err := upstream.ExtractConsumers(page)
		return []Consumer(values), err
	})
}
