// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package containers

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/keymanager/v1/containers"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	path "path"
	strings "strings"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Container] {
	return resource.NewCollection(resource.Adapter[Container]{
		Kind:             "containers",
		BodyFilterFields: map[string]string{"consumers": "consumers", "container_id": "container_id", "container_ref": "container_ref", "created_at": "created_at", "id": "id", "name": "name", "secret_refs": "secret_refs", "status": "status", "type": "type", "updated_at": "updated_at"},
		BodyFilterRecordValue: func(record *resource.BodyRecord[Container], key string) (json.RawMessage, error) {
			return containerBodyFilterValue(record, key)
		},
		IterateBodyControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*resource.BodyRecord[Container], error] {
			q = maps.Clone(q)
			q.Del("status")
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listBodyWithControl(ctx, control, options...)
		},
		FilterDescriptor: &resource.FilterDescriptor{Query: map[string]string{"limit": "limit", "marker": "marker"}, Body: map[string]string{"consumers": "consumers", "container_id": "container_id", "container_ref": "container_ref", "created_at": "created_at", "id": "id", "name": "name", "secret_refs": "secret_refs", "status": "status", "type": "type", "updated_at": "updated_at"}, Reserved: []string{"allow_unknown_params", "base_path", "headers", "jmespath_filters", "max_items", "microversion", "paginated", "resource_type", "session"}},
		Get:              func(ctx context.Context, id string) (*Container, error) { return a.Get(ctx, string(id)) },
		ID: func(v *Container) string {
			parsed, err := url.Parse(v.ContainerRef)
			if err != nil {
				return ""
			}
			return path.Base(parsed.Path)
		},
		Name:      func(v *Container) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Status:    func(v *Container) string { return fmt.Sprint(v.Status) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return a.deleteOwned(ctx, id) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Container, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) listBodyWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*resource.BodyRecord[Container], error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err == nil {
		err = request.ValidateCapabilities(cfg, false, true, false)
	}
	if err != nil {
		err = request.Wrap("List", "containers", err)
		return func(yield func(*resource.BodyRecord[Container], error) bool) { yield(nil, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.BodyStreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]Container, error) {
		values, err := upstream.ExtractContainers(page)
		return []Container(values), err
	}, "containers", control)
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Container, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Container, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.removeOwned(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Container, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
