// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package containers

import (
	context "context"
	fmt "fmt"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
	path "path"
	strings "strings"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Container] {
	return resource.NewCollection(resource.Adapter[Container]{
		Kind: "containers",
		Get:  func(ctx context.Context, id string) (*Container, error) { return a.Get(ctx, string(id)) },
		ID: func(v *Container) string {
			parsed, err := url.Parse(v.ContainerRef)
			if err != nil {
				return ""
			}
			return path.Base(parsed.Path)
		},
		Name:      func(v *Container) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Status:    func(v *Container) string { return fmt.Sprint(v.Status) },
		Failed: func(status string) bool {
			status = strings.ToLower(status)
			return strings.HasPrefix(status, "error") || strings.HasSuffix(status, "fail") || strings.HasSuffix(status, "failed") || status == "killed"
		},
		Delete: func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		Iterate: func(ctx context.Context, q url.Values) iter.Seq2[*Container, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := make([]ListOption, 0, len(q))
			for key, values := range q {
				for _, value := range values {
					options = append(options, WithListQuery(key, value))
				}
			}
			return a.List(ctx, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Container, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Container, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Container, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
