// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package quotasets

import (
	context "context"
	request "github.com/JSYoo5B/go-openstacksdk/request"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/compute/v2/quotasets"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type DeleteResult = upstream.DeleteResult
type GetDetailResult = upstream.GetDetailResult
type GetResult = upstream.GetResult
type QuotaDetail = upstream.QuotaDetail
type QuotaDetailSet = upstream.QuotaDetailSet
type QuotaSet = upstream.QuotaSet
type QuotaSetPage = upstream.QuotaSetPage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, tenantID string) (*QuotaSet, error) {
	result := upstream.Delete(ctx, a.client, tenantID)
	value0, err := result.Extract()
	err = request.Wrap("Delete", "quotasets", err)
	return value0, err
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, tenantID string) (*QuotaSet, error) {
	result := upstream.Get(ctx, a.client, tenantID)
	value0, err := result.Extract()
	err = request.Wrap("Get", "quotasets", err)
	return value0, err
}

// GetDetail invokes the upstream API with library-owned builders and result handling.
func (a *API) GetDetail(ctx context.Context, tenantID string) (QuotaDetailSet, error) {
	result := upstream.GetDetail(ctx, a.client, tenantID)
	value0, err := result.Extract()
	err = request.Wrap("GetDetail", "quotasets", err)
	return value0, err
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base   UpdateOpts
	config request.Config[UpdateOpts]
}

func (b updateOptsBuilder) ToComputeQuotaUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToComputeQuotaUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, tenantID string, opts UpdateOpts, options ...UpdateOption) (*QuotaSet, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "quotasets", err)
		var zero0 *QuotaSet
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "quotasets", err)
		var zero0 *QuotaSet
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Update(ctx, a.client, tenantID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "quotasets", err)
	return value0, err
}
