// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package subnetpools

import (
	context "context"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/subnetpools"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
)

// API owns typed operations and their shared resource policies.
type API struct {
	client    *gophercloud.ServiceClient
	Resources *resource.Collection[SubnetPool]
}

func New(client *gophercloud.ServiceClient) *API {
	a := &API{client: client}
	a.Resources = a.newResources()
	return a
}
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateOpts = upstream.CreateOpts
type CreateResult = upstream.CreateResult
type DeleteResult = upstream.DeleteResult
type GetResult = upstream.GetResult
type ListOpts = upstream.ListOpts
type PrefixesOpsOpts = upstream.PrefixesOpsOpts
type PrefixesOpsResult = upstream.PrefixesOpsResult
type SubnetPool = upstream.SubnetPool
type SubnetPoolPage = upstream.SubnetPoolPage
type UpdateOpts = upstream.UpdateOpts
type UpdateResult = upstream.UpdateResult
type AddPrefixesOption = request.Option[PrefixesOpsOpts]

func WithAddPrefixesOptions(value PrefixesOpsOpts) AddPrefixesOption {
	return request.WithOptions(value)
}
func WithAddPrefixesField(key string, value any) AddPrefixesOption {
	return request.WithField[PrefixesOpsOpts](key, value)
}

type addPrefixesOptsBuilder struct {
	base   PrefixesOpsOpts
	config request.Config[PrefixesOpsOpts]
}

func (b addPrefixesOptsBuilder) ToSubnetPoolPrefixesOpsMap() (map[string]any, error) {
	value0, err := b.base.ToSubnetPoolPrefixesOpsMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// AddPrefixes invokes the upstream API with library-owned builders and result handling.
func (a *API) AddPrefixes(ctx context.Context, subnetPoolID string, opts PrefixesOpsOpts, options ...AddPrefixesOption) ([]string, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("AddPrefixes", "subnetpools", err)
		var zero0 []string
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("AddPrefixes", "subnetpools", err)
		var zero0 []string
		return zero0, err
	}
	_opts := addPrefixesOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.AddPrefixes(ctx, a.client, subnetPoolID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("AddPrefixes", "subnetpools", err)
	return value0, err
}

type CreateOption = request.Option[CreateOpts]

func WithCreateOptions(value CreateOpts) CreateOption { return request.WithOptions(value) }
func WithCreateField(key string, value any) CreateOption {
	return request.WithField[CreateOpts](key, value)
}

type createOptsBuilder struct {
	base   CreateOpts
	config request.Config[CreateOpts]
}

func (b createOptsBuilder) ToSubnetPoolCreateMap() (map[string]any, error) {
	value0, err := b.base.ToSubnetPoolCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Create invokes the upstream API with library-owned builders and result handling.
func (a *API) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*SubnetPool, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Create", "subnetpools", err)
		var zero0 *SubnetPool
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Create", "subnetpools", err)
		var zero0 *SubnetPool
		return zero0, err
	}
	_opts := createOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Create(ctx, a.client, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Create", "subnetpools", err)
	return value0, err
}

// Delete invokes the upstream API with library-owned builders and result handling.
func (a *API) Delete(ctx context.Context, id string) error {
	return request.Wrap("Delete", "subnetpools", upstream.Delete(ctx, a.client, id).ExtractErr())
}

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, id string) (*SubnetPool, error) {
	result := upstream.Get(ctx, a.client, id)
	value0, err := result.Extract()
	err = request.Wrap("Get", "subnetpools", err)
	return value0, err
}

type ListOption = request.Option[ListOpts]

func WithListOptions(value ListOpts) ListOption  { return request.WithOptions(value) }
func WithListQuery(key, value string) ListOption { return request.WithQuery[ListOpts](key, value) }

type listOptsBuilder struct {
	base   ListOpts
	config request.Config[ListOpts]
}

func (b listOptsBuilder) ToSubnetPoolListQuery() (string, error) {
	value0, err := b.base.ToSubnetPoolListQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context, options ...ListOption) iter.Seq2[*SubnetPool, error] {
	return a.listWithControl(ctx, resource.ListControl{}, options...)
}

func (a *API) listWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*SubnetPool, error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("List", "subnetpools", err)
		return func(yield func(*SubnetPool, error) bool) { var zero *SubnetPool; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("List", "subnetpools", err)
		return func(yield func(*SubnetPool, error) bool) { var zero *SubnetPool; yield(zero, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.StreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]SubnetPool, error) {
		values, err := upstream.ExtractSubnetPools(page)
		return []SubnetPool(values), err
	}, control)
}

type RemovePrefixesOption = request.Option[PrefixesOpsOpts]

func WithRemovePrefixesOptions(value PrefixesOpsOpts) RemovePrefixesOption {
	return request.WithOptions(value)
}
func WithRemovePrefixesField(key string, value any) RemovePrefixesOption {
	return request.WithField[PrefixesOpsOpts](key, value)
}

type removePrefixesOptsBuilder struct {
	base   PrefixesOpsOpts
	config request.Config[PrefixesOpsOpts]
}

func (b removePrefixesOptsBuilder) ToSubnetPoolPrefixesOpsMap() (map[string]any, error) {
	value0, err := b.base.ToSubnetPoolPrefixesOpsMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// RemovePrefixes invokes the upstream API with library-owned builders and result handling.
func (a *API) RemovePrefixes(ctx context.Context, subnetPoolID string, opts PrefixesOpsOpts, options ...RemovePrefixesOption) ([]string, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("RemovePrefixes", "subnetpools", err)
		var zero0 []string
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("RemovePrefixes", "subnetpools", err)
		var zero0 []string
		return zero0, err
	}
	_opts := removePrefixesOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.RemovePrefixes(ctx, a.client, subnetPoolID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("RemovePrefixes", "subnetpools", err)
	return value0, err
}

type UpdateOption = request.Option[UpdateOpts]

func WithUpdateOptions(value UpdateOpts) UpdateOption { return request.WithOptions(value) }
func WithUpdateField(key string, value any) UpdateOption {
	return request.WithField[UpdateOpts](key, value)
}

type updateOptsBuilder struct {
	base           UpdateOpts
	config         request.Config[UpdateOpts]
	RevisionNumber *int "json:\"-\" h:\"If-Match\""
}

func (b updateOptsBuilder) ToSubnetPoolUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToSubnetPoolUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// Update invokes the upstream API with library-owned builders and result handling.
func (a *API) Update(ctx context.Context, subnetPoolID string, opts UpdateOpts, options ...UpdateOption) (*SubnetPool, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("Update", "subnetpools", err)
		var zero0 *SubnetPool
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("Update", "subnetpools", err)
		var zero0 *SubnetPool
		return zero0, err
	}
	_opts := updateOptsBuilder{base: cfg.Options, config: cfg, RevisionNumber: cfg.Options.RevisionNumber}
	result := upstream.Update(ctx, a.client, subnetPoolID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Update", "subnetpools", err)
	return value0, err
}
