// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package subnetpools

import (
	context "context"
	json "encoding/json"
	fmt "fmt"
	nativefind "github.com/JSYoo5B/gophercloudsdk/internal/nativefind"
	request "github.com/JSYoo5B/gophercloudsdk/request"
	resource "github.com/JSYoo5B/gophercloudsdk/resource"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/subnetpools"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[SubnetPool] {
	return resource.NewCollection(resource.Adapter[SubnetPool]{
		Kind:             "subnetpools",
		BodyFilterFields: map[string]string{"created_at": "created_at", "default_prefixlen": "default_prefixlen", "default_prefix_length": "default_prefixlen", "default_quota": "default_quota", "id": "id", "max_prefixlen": "max_prefixlen", "maximum_prefix_length": "max_prefixlen", "min_prefixlen": "min_prefixlen", "minimum_prefix_length": "min_prefixlen", "prefixes": "prefixes", "revision_number": "revision_number", "tenant_id": "tenant_id", "updated_at": "updated_at"},
		BodyFilterRecordValue: func(record *resource.BodyRecord[SubnetPool], key string) (json.RawMessage, error) {
			return subnetPoolBodyFilterValue(record, key)
		},
		IterateBodyControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*resource.BodyRecord[SubnetPool], error] {
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listBodyWithControl(ctx, control, options...)
		},
		FilterDescriptor: &resource.FilterDescriptor{Query: map[string]string{"address_scope_id": "address_scope_id", "any_tags": "tags-any", "description": "description", "fields": "fields", "ip_version": "ip_version", "is_default": "is_default", "is_shared": "shared", "limit": "limit", "marker": "marker", "name": "name", "not_any_tags": "not-tags-any", "not_tags": "not-tags", "project_id": "project_id", "sort_dir": "sort_dir", "sort_key": "sort_key", "tags": "tags"}, Body: map[string]string{"created_at": "created_at", "default_prefix_length": "default_prefixlen", "default_quota": "default_quota", "id": "id", "maximum_prefix_length": "max_prefixlen", "minimum_prefix_length": "min_prefixlen", "prefixes": "prefixes", "revision_number": "revision_number", "tenant_id": "tenant_id", "updated_at": "updated_at"}, Reserved: []string{"allow_unknown_params", "base_path", "headers", "jmespath_filters", "max_items", "microversion", "paginated", "resource_type", "session"}},
		IdentityFind:     true,
		GetIdentityQuery: func(ctx context.Context, id string, q url.Values) (*SubnetPool, error) {
			var result upstream.GetResult
			result.Header, result.Err = nativefind.Get(ctx, a.RawClient(), []string{"subnetpools", id}, q, []int{200}, &result.Body)
			return result.Extract()
		},
		Get:       func(ctx context.Context, id string) (*SubnetPool, error) { return a.Get(ctx, string(id)) },
		ID:        func(v *SubnetPool) string { return fmt.Sprint(v.ID) },
		Name:      func(v *SubnetPool) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Delete:    func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*SubnetPool, error] {
			q = maps.Clone(q)
			options := []ListOption{func(config *request.Config[ListOpts]) error {
				config.Query = make(url.Values, len(q))
				for key, values := range q {
					config.Query[key] = append([]string(nil), values...)
				}
				return nil
			}}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) listBodyWithControl(ctx context.Context, control resource.ListControl, options ...ListOption) iter.Seq2[*resource.BodyRecord[SubnetPool], error] {
	var opts ListOpts
	cfg, err := request.Apply(opts, options...)
	if err == nil {
		err = request.ValidateCapabilities(cfg, false, true, false)
	}
	if err != nil {
		err = request.Wrap("List", "subnetpools", err)
		return func(yield func(*resource.BodyRecord[SubnetPool], error) bool) { yield(nil, err) }
	}
	_opts := listOptsBuilder{base: cfg.Options, config: cfg}
	return resource.BodyStreamWithControl(ctx, upstream.List(a.client, _opts), func(page pagination.Page) ([]SubnetPool, error) {
		values, err := upstream.ExtractSubnetPools(page)
		return []SubnetPool(values), err
	}, "subnetpools", control)
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*SubnetPool, error) {
	return a.Resources.Find(ctx, ref, options...)
}

// FindIdentity tries an ID request before exact ID/name fallback within this collection.
func (a *API) FindIdentity(ctx context.Context, identity string, options ...resource.IdentityFindOption) (*SubnetPool, error) {
	return a.Resources.FindIdentity(ctx, identity, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*SubnetPool, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*SubnetPool, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
