// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package swauth

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/objectstorage/v1/swauth"
	request "gophercloudsdk/request"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type AuthOpts = upstream.AuthOpts
type AuthResult = upstream.AuthResult
type GetAuthResult = upstream.GetAuthResult
type AuthOption = request.Option[AuthOpts]

func WithAuthOptions(value AuthOpts) AuthOption { return request.WithOptions(value) }

type authOptsBuilder struct {
	base   AuthOpts
	config request.Config[AuthOpts]
}

func (b authOptsBuilder) ToAuthOptsMap() (map[string]string, error) {
	return b.base.ToAuthOptsMap()
}

// Auth invokes the upstream API with library-owned builders and result handling.
func (a *API) Auth(ctx context.Context, opts AuthOpts, options ...AuthOption) (*AuthResult, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		var zero0 *AuthResult
		return zero0, err
	}
	_opts := authOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.Auth(ctx, a.client.ProviderClient, _opts)
	value0, err := result.Extract()
	err = request.Wrap("Auth", "swauth", err)
	return value0, err
}

type NewObjectStorageV1Option = request.Option[AuthOpts]

func WithNewObjectStorageV1Options(value AuthOpts) NewObjectStorageV1Option {
	return request.WithOptions(value)
}

// NewObjectStorageV1 invokes the upstream API with library-owned builders and result handling.
func (a *API) NewObjectStorageV1(ctx context.Context, authOpts AuthOpts, options ...NewObjectStorageV1Option) (*gophercloud.ServiceClient, error) {
	cfg, err := request.Apply(authOpts, options...)
	if err != nil {
		var zero0 *gophercloud.ServiceClient
		return zero0, err
	}
	return upstream.NewObjectStorageV1(ctx, a.client.ProviderClient, cfg.Options)
}
