package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var pythonServiceNames = map[string]string{
	"baremetalintrospection": "baremetal_introspection", "blockstorage": "block_storage",
	"containerinfra": "container_infrastructure_management", "db": "database",
	"keymanager": "key_manager", "loadbalancer": "load_balancer", "messaging": "message",
	"objectstorage": "object_store", "sharedfilesystems": "shared_file_system",
}

var exampleResources = map[string]string{
	"baremetal": "nodes", "blockstorage": "volumes", "compute": "servers", "containerinfra": "clusters", "db": "instances",
	"dns": "zones", "identity": "users", "image": "images", "keymanager": "secrets", "loadbalancer": "loadbalancers",
	"network": "networks", "placement": "resourceproviders", "reservation": "leases", "sharedfilesystems": "shares", "workflow": "workflows",
}

// Versioned reference pages are derived from the same API and resource inventory
// as the code, keeping registry fields and common-policy coverage reviewable.
func (g *generator) writeServiceREADME(key string, spec serviceSpec, paths []string) error {
	parts := strings.Split(key, "/")
	python := pythonServiceNames[parts[0]]
	if python == "" {
		python = parts[0]
	}
	method := spec.name + strings.ToUpper(parts[1][:1]) + parts[1][1:]
	var out strings.Builder
	fmt.Fprintf(&out, "# %s %s\n\n<!-- Generated by sdkgen; edit internal/cmd/sdkgen/service_docs.go. -->\n\n", spec.name, parts[1])
	fmt.Fprintf(&out, "Gophercloud v2.15.0의 %s API를 하나의 인증된 서비스 객체에서 사용합니다. 인증, region, endpoint interface와 TLS 설정은 Connection이 관리합니다.\n\n", key)
	pythonAccess := "`conn." + python + "`"
	if parts[0] == "metric" {
		pythonAccess = "직접 대응하는 서비스 없음 (Aetos)"
	}
	fmt.Fprintf(&out, "| 작업 | openstacksdk | Go |\n|---|---|---|\n| 서비스 접근 | %s | `conn.%s(ctx)` |\n| 선택 인자·기본값 | keyword arguments | concrete options와 작업별 `With...Options` |\n| 확장 입력 | `**attrs`, `**query` | 가능한 연산의 `With...Field/Query/Header` |\n| 결과 | Resource 또는 generator | typed 값과 error 또는 `iter.Seq2` |\n\n", pythonAccess, method)
	out.WriteString("전체 API 호출 지원과 openstacksdk의 리소스 객체·복합 작업 지원은 별도로 추적합니다. Python 입력 별칭을 자동으로 Go 필드에 적용하지 않습니다. 응답 모델은 Gophercloud 타입이며, 수정한 응답이 자동 저장되지는 않습니다.\n\n")
	if parts[0] == "metric" {
		out.WriteString("이 버전은 Aetos의 Prometheus API입니다. Python openstacksdk의 Gnocchi metric 서비스와 기능이 같지 않습니다.\n\n")
	}
	switch key {
	case "identity/v2":
		out.WriteString("`Tokens.Create/Get`은 SDK의 `Authentication`을 반환합니다. `Token`, `User`, `Catalog`를 한 번에 해석하고 `Header`와 추가 응답 필드를 포함한 JSON `Body`도 보존합니다. [인증 응답 사용법](tokens/README.md)을 참고합니다.\n\n")
	case "compute/v2":
		out.WriteString("`Servers.GetPassword`는 기본적으로 암호화된 문자열을 반환합니다. RSA 복호화는 `servers.WithGetPasswordPrivateKey(key)`로 선택합니다. [암호 조회 사용법](servers/README.md)을 참고합니다.\n\n")
	}
	var example *collectionRecord
	for i := range g.collections {
		record := &g.collections[i]
		if record.Model != "" && record.Scope == "" && strings.HasPrefix(record.Package, "gophercloudsdk/"+key+"/") {
			example = record
			if strings.TrimPrefix(record.Package, "gophercloudsdk/"+key+"/") == exampleResources[parts[0]] {
				break
			}
		}
	}
	out.WriteString("## Go 사용\n\n```go\n")
	fmt.Fprintf(&out, "// context.Context ctx, *gophercloudsdk.Connection conn을 사용하는 함수 안에서\nservice, err := conn.%s(ctx)\nif err != nil { return err }\n", method)
	if example != nil {
		field := registryField(strings.TrimPrefix(example.Package, "gophercloudsdk/"+key+"/"))
		fmt.Fprintf(&out, "for value, err := range service.%s.Resources.List(ctx) {\n    if err != nil { return err }\n    fmt.Println(value)\n}\n", field)
		if example.Find {
			fmt.Fprintf(&out, "value, err := service.%s.Find(ctx, resource.Name(\"example\"))\nif err != nil { return err }\n_ = value\n", field)
		}
	} else {
		if parts[0] == "metric" {
			out.WriteString("data, err := service.Metrics.Query(ctx, metrics.QueryOpts{Query: \"up\"})\nif err != nil { return err }\nfmt.Println(data)\n")
		} else if err := g.writeListExample(&out, key, paths); err != nil {
			return err
		}
	}
	out.WriteString("```\n\n예제의 `fmt`는 표준 라이브러리, `resource`는 `gophercloudsdk/resource`입니다. Find는 기본적으로 미존재를 오류로 처리합니다. `resource.WithIgnoreMissing()`을 추가하면 `nil, nil`을 반환합니다. Delete의 기본값은 미존재 무시입니다.\n\n")
	if parts[0] == "metric" {
		out.WriteString("`metrics`는 `gophercloudsdk/metric/v1/metrics`입니다.\n\n")
	}
	out.WriteString("## 리소스와 공통 정책\n\n| 서비스 필드 | API 패키지 | 공통 Collection |\n|---|---|---|\n")
	for _, path := range paths {
		var policies []string
		for _, record := range g.collections {
			if record.Package != "gophercloudsdk/"+key+"/"+path || record.Model == "" {
				continue
			}
			label := "Resources"
			if record.Scope != "" {
				label = record.Scope + "(ctx, parent)"
			}
			features := []string{"ID 조회", "목록"}
			if record.Find {
				features = append(features, "이름 조회")
			}
			if record.Delete {
				features = append(features, "삭제·삭제 대기")
			}
			if record.Wait {
				features = append(features, "상태 대기")
			}
			policies = append(policies, fmt.Sprintf("`%s`: %s", label, strings.Join(features, ", ")))
		}
		policy := strings.Join(policies, "; ")
		if policy == "" {
			policy = "API 연산 제공; 공통 Collection 미적용"
		}
		fmt.Fprintf(&out, "| `%s` | [%s](%s/api_generated.go) | %s |\n", registryField(path), path, path, policy)
	}
	out.WriteString("\n공통 Collection은 정확한 이름 검색, 중복 이름 오류, 페이지 순회, context 취소와 HTTP 오류 보존을 적용합니다. 상태가 없는 리소스의 Wait는 `ErrUnsupported`를 반환합니다.\n\n")
	out.WriteString("## 변경 요청\n\n리소스 API의 Create/Update에 concrete options를 전달합니다. 기본 필드는 typed options로 지정하고 추가 필드는 `With...Field`로 지정합니다. query와 header도 해당 연산이 제공하는 `With...` 함수를 사용합니다. 기본 필드·헤더 덮어쓰기와 지원되지 않는 확장 방식은 요청 전에 거부합니다. 요청 builder interface는 SDK가 구현합니다.\n\n")
	out.WriteString("부모가 필요한 연산은 [범위 객체](../../docs/scoped-resources.md)를 사용합니다. 범위 객체가 제공하는 Create/Update에도 같은 concrete options를 사용합니다. 응답 변경 추적이나 Python cloud의 모든 복합 작업은 이 API 참조 페이지의 지원 범위를 뜻하지 않습니다.\n\n")
	out.WriteString("전체 비교 기준은 [openstacksdk 목록](../../api/openstacksdk/README.md), Go API 호출은 [전체 API 설명](../../api/README.md), 실행·검증은 [프로젝트 README](../../README.md)를 참고합니다.\n")
	return os.WriteFile(filepath.Join(g.root, key, "README.md"), []byte(out.String()), 0644)
}

// Where no common Collection exists yet, show a real typed list operation.
func (g *generator) writeListExample(out *strings.Builder, key string, paths []string) error {
	for _, path := range paths {
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(g.root, key, path, "api_generated.go"), nil, 0)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || !strings.HasPrefix(fn.Name.Name, "List") {
				continue
			}
			params := fn.Type.Params.List
			if len(params) != 1 {
				if len(params) != 2 {
					continue
				}
				if _, ok := params[1].Type.(*ast.Ellipsis); !ok {
					continue
				}
			}
			fmt.Fprintf(out, "for value, err := range service.%s.%s(ctx) {\n    if err != nil { return err }\n    fmt.Println(value)\n}\n", registryField(path), fn.Name.Name)
			return nil
		}
	}
	out.WriteString("// 아래 리소스 표에서 필요한 연산과 concrete options를 선택합니다.\nfmt.Println(service.RawClient().Endpoint)\n")
	return nil
}
