package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var pythonServiceNames = map[string]string{
	"baremetalintrospection": "baremetal_introspection", "blockstorage": "block_storage",
	"containerinfra": "container_infrastructure_management", "db": "database",
	"keymanager": "key_manager", "loadbalancer": "load_balancer", "messaging": "message",
	"objectstorage": "object_store", "sharedfilesystems": "shared_file_system",
	"instanceha": "instance_ha",
}

var exampleResources = map[string]string{
	"baremetal": "nodes", "blockstorage": "volumes", "compute": "servers", "containerinfra": "clusters", "db": "instances",
	"dns": "zones", "identity": "users", "image": "images", "keymanager": "secrets", "loadbalancer": "loadbalancers",
	"network": "networks", "placement": "resourceproviders", "reservation": "leases", "sharedfilesystems": "shares", "workflow": "workflows",
	"instanceha": "segments", "clustering": "profiletypes",
}

// Versioned reference pages are derived from the same API and resource inventory
// as the code, keeping registry fields and common-policy coverage reviewable.
func (g *generator) writeServiceREADME(key string, spec serviceSpec, paths []string) error {
	parts := strings.Split(key, "/")
	python := pythonServiceNames[parts[0]]
	if python == "" {
		python = parts[0]
	}
	method := spec.name + strings.ToUpper(parts[1][:1]) + parts[1][1:]
	var out strings.Builder
	fmt.Fprintf(&out, "# %s %s\n\n<!-- Generated by sdkgen; edit internal/cmd/sdkgen/service_docs.go. -->\n\n", spec.name, parts[1])
	sdkOwnedService := parts[0] == "clustering" || parts[0] == "instanceha"
	if sdkOwnedService {
		fmt.Fprintf(&out, "%s API는 pinned Gophercloud에 없어 SDK가 직접 구현합니다. pinned openstacksdk와 공식 API 계약을 기준으로 구현한 아래 리소스를 하나의 인증된 서비스 객체에서 사용합니다. 인증, region, endpoint interface와 TLS 설정은 Connection이 관리합니다.\n\n", key)
	} else {
		fmt.Fprintf(&out, "Gophercloud v2.15.0의 %s API를 하나의 인증된 서비스 객체에서 사용합니다. 인증, region, endpoint interface와 TLS 설정은 Connection이 관리합니다.\n\n", key)
	}
	pythonAccess := "`conn." + python + "`"
	if parts[0] == "metric" {
		pythonAccess = "직접 대응하는 서비스 없음 (Aetos)"
	}
	fmt.Fprintf(&out, "| 작업 | openstacksdk | Go |\n|---|---|---|\n| 서비스 접근 | %s | `conn.%s(ctx)` |\n| 선택 인자·기본값 | keyword arguments | concrete options와 작업별 `With...Options` |\n| 확장 입력 | `**attrs`, `**query` | 가능한 연산의 `With...Field/Query/Header` |\n| 결과 | Resource 또는 generator | typed 값과 error 또는 `iter.Seq2` |\n\n", pythonAccess, method)
	out.WriteString("전체 API 호출 지원과 openstacksdk의 리소스 객체·복합 작업 지원은 별도로 추적합니다. Python 입력 별칭을 자동으로 Go 필드에 적용하지 않습니다. ")
	if sdkOwnedService {
		out.WriteString("응답은 SDK의 typed 모델이며 원문 필드·HTTP 헤더·상태 코드를 함께 보존합니다. Python의 permissive flat/empty 응답 fallback과 달리 각 endpoint의 명시한 object envelope를 검증합니다. ")
	} else {
		out.WriteString("기본 응답 모델은 Gophercloud 타입을 사용하며 SDK가 추가한 모델은 서비스별로 설명합니다. ")
	}
	out.WriteString("수정한 응답이 자동 저장되지는 않습니다.\n\n")
	if parts[0] == "metric" {
		out.WriteString("이 버전은 Aetos의 Prometheus API입니다. Python openstacksdk의 Gnocchi metric 서비스와 기능이 같지 않습니다.\n\n")
	}
	identityFindAccess := map[string]string{
		"compute/v2":      "`Servers/Flavors.FindIdentity(ctx, identity, options...)`",
		"blockstorage/v3": "`Volumes.FindIdentity(ctx, identity, options...)`",
		"network/v2":      "`Networks/Subnets/Ports/Routers/SecurityGroups/SubnetPools/Trunks/QoSPolicies/SecurityAddressGroups.FindIdentity(ctx, identity, options...)`",
		"identity/v3":     "`Projects/Users/Groups/Domains/Roles.FindIdentity(ctx, identity, options...)`",
		"image/v2":        "`Images.FindIdentity(ctx, identity, options...)`",
		"dns/v2":          "`RecordSets.InZone(ctx, parent)`가 반환한 scope의 `FindIdentity`",
		"loadbalancer/v2": "`Pools.Members(ctx, parent)`가 반환한 scope의 `FindIdentity`",
	}
	if access, ok := identityFindAccess[key]; ok {
		fmt.Fprintf(&out, "%s는 이름·ID 문자열을 SDK가 자동 조회합니다. 기본 GET400·403·404 뒤 목록 fallback과 정확한 ID/이름·중복 검사, `nil, nil` 미존재 기본값을 제공하며 `resource.WithIdentityFindIgnoreMissing(false)`로 strict를 선택합니다. `WithIdentityFindQuery`의 caller 필터는 GET과 fallback 목록 모두에 보존하고 자동 이름 hint는 목록에만 추가합니다. query와 fallback은 공통 concrete 옵션으로 제어합니다. [Python/Go 자동 조회 비교](../../docs/finding-identities.md)에 이 binding의 사용법·고정 부모·domain 필터·경로 정책을 설명합니다.\n\n", access)
	}
	if key == "compute/v2" || key == "blockstorage/v3" {
		out.WriteString("서버·볼륨 자동 조회는 `resource.WithIdentityFindDetails(false)`로 fallback summary 목록을, `resource.WithIdentityFindAllProjects(true)`로 목록의 cross-project 검색을 선택합니다. 기본값은 details=true·all_projects=false이며 GET은 바꾸지 않습니다. 명시적 AllProjects와 raw all_tenants query의 충돌은 요청 전에 거부합니다.\n\n")
	}
	if key == "compute/v2" {
		out.WriteString("Flavor 자동 조회는 이름 hint를 서버에 보내지 않고 `/flavors/detail` 전체를 검사하며, caller가 지정하지 않은 `is_public`은 목록에만 `None`으로 설정합니다. 기본 extra specs 추가 조회는 하지 않습니다. `resource.WithIdentityFindExtraSpecs(true)`를 지정하면 단일 결과의 ExtraSpecs가 비어 있을 때만 반환된 ID의 `/os-extra_specs`를 조회합니다. 후속 GET에는 caller query를 전달하지 않으며 실패를 미존재로 숨기지 않습니다. 이 옵션은 Flavor만 지원하고 summary/all-projects 목록 모드는 제공하지 않습니다.\n\n")
	}
	if key == "image/v2" {
		out.WriteString("Glance 이미지 자동 조회는 정상 목록 전체에서 찾지 못했을 때 원래 caller query에 `os_hidden=true`를 적용해 숨김 이미지를 한 번 더 검색합니다. 두 번째 목록에는 자동 이름 hint를 넣지 않으며 추가 GET도 하지 않습니다. 첫 검색의 오류·중복·취소는 즉시 반환하고, 두 목록 모두 정상적으로 비었을 때 최종 미존재 옵션을 적용합니다. Python `find_image(name_or_id, ignore_missing=True)`에 대응하며 raw wire query는 Go의 확장 옵션입니다.\n\n")
	}
	if key == "network/v2" {
		out.WriteString("`QoSPolicies.Resources`의 `rules`, `SecurityAddressGroups.Resources`의 `addresses`, `SubnetPools.Resources`의 `prefixes`, `Networks.Resources`의 `subnets`는 `resource.WithBodyFilter`/`WithBodyFilters`로 로컬에서 비교합니다. SDK가 필드 선택·JSON snapshot·배열 전체 equality를 처리하며 builder나 predicate를 구현하지 않습니다. Network의 Python 이름 `subnet_ids`도 `subnets`의 SDK 별칭으로 받으며 bulk에서 두 이름을 함께 지정하면 HTTP 전에 거부합니다. 상위 `network.Service.Networks`에도 같은 필터가 연결됩니다. nil/빈 배열과 raw cap 이후 비교를 구분하고 raw wire query는 자동 분류하지 않습니다. 이 옵션은 ordinary `Resources.List/All`만 받으며 native typed List·FindIdentity와 다른 리소스는 별도입니다. [Python/Go Body 필터 비교](../../docs/listing.md#명시적인-native-body-필터)를 참고합니다.\n\n")
		out.WriteString("`Subnets.Resources`는 선언된 로컬 Body 필드 9개도 지원합니다. allocation pools·DNS nameservers·host routes·service types·timestamp·prefix length·tenant ID·revision number를 원본 페이지 행으로 비교하며 typed Subnet을 반환합니다. `prefix_length`는 `prefixlen`의 SDK 별칭이고 native 전체 페이지 디코드가 먼저 적용됩니다. [Subnet Python/Go 사용법](subnets/README.md)에 숫자 정밀도·누락/null·native decoder 경계를 설명합니다.\n\n")
		out.WriteString("`Subnets.Resources.List/All`의 `resource.WithFilter`/`WithFilters`는 Python 속성 이름을 서버 query 24개 또는 로컬 Body 9개로 자동 분류합니다. query의 wire 별칭을 포함한 30개 이름, bulk canonical 우선·최종값 검증·semantic 전체 교체/clear·JSON snapshot을 SDK가 처리합니다. raw query·명시 Body·page/name hint와 같은 target을 지정하면 HTTP 전에 오류이며, 알 수 없는 semantic 이름은 버립니다. 현재 이 분류는 Subnet에 연결되어 있고 [고정 Python AST manifest](../../api/openstacksdk/resources/network/v2/subnet.json)의 현재 소스 검증을 통과해야 생성됩니다. 전체 Resource/cache·상속 continuation/session·Proxy conflicting attrs·JMESPath 조건은 별도입니다. [Subnet 사용법](subnets/README.md)을 참고하세요.\n\n")
	}
	if key == "keymanager/v1" {
		out.WriteString("`Secrets.FindIdentity(ctx, identity, options...)`는 안전한 ID의 metadata·조건부 payload 조회를 먼저 시도하고, 기본 HTTP400·403·404 뒤에는 이름 hint를 넣은 metadata 목록 전체에서 정확한 ID 또는 이름을 찾습니다. 목록 결과에는 payload를 추가 조회하지 않습니다. `resource.WithIdentityFindIgnoreMissing(false)`와 `WithIdentityFindFallback`으로 미존재·fallback 정책을 선택합니다. raw query·details·all-projects·extra-specs 옵션은 지원하지 않습니다. 응답의 원문 id/secret_ref는 비교에만 쓰며 요청 경로로 따라가지 않습니다. [Secret 자동 조회 Python/Go 사용법](secrets/finding/README.md)에 nullable ID·중복·offset 순회·고정 서비스 설정과 Python 기본 status 처리 차이를 설명합니다. native `Secrets.Resources`는 기존 metadata collection입니다.\n\n")
		out.WriteString("`Secrets.Fetch(ctx, resource.ID(secretID))`는 metadata GET 뒤 선택한 content type이 있을 때만 원래 ID의 payload를 조회합니다. 기본 선택은 metadata의 `content_types.default`이며 `WithFetchContentType`으로 우선 지정하거나 `WithFetchPayload(false)`로 metadata만 조회합니다. 정확한 `text/plain`만 UTF-8 텍스트로 제공하고 나머지는 원본 bytes로 반환합니다. 두 HTTP 응답의 Body·header·status와 요청 ID를 구분하며 후속 payload 실패에도 이미 받은 metadata를 반환합니다. native `Secrets.Get`과 `GetPayload`는 각각 별도의 metadata와 payload 호출입니다. [Secret Python/Go 사용법](secrets/README.md)에 content type·고정 경로·옵션·오류 및 seeded Python Resource와의 차이를 설명합니다.\n\n")
		out.WriteString("Barbican의 native API와 함께 SDK가 직접 구현한 `SecretStores`와 `Quotas`를 제공합니다. `SecretStores.List/All`, `GetGlobalDefault`, `GetPreferred`는 목록과 두 고정 selector의 조회이며 자동 fallback·CRUD·상태 대기를 추가하지 않습니다. `Quotas.Get`은 현재 인증된 프로젝트의 effective quota이고 `Quotas.InProject(ctx, resource.ID(projectID))`는 고정 프로젝트의 Get·Update·Delete입니다. Update는 설정 교체 PUT204이고 삭제는 override 초기화 DELETE204이며 둘 다 자동 재조회하지 않습니다. 반환 acknowledgement는 실제 빈 응답·header·status이며 Python의 seeded Resource와 구분합니다. [SecretStore Python/Go 사용법](secretstores/README.md)과 [Quota Python/Go 사용법](quotas/README.md)에 marker·nullable 응답·정수 입력·기본값 및 남은 Resource/cache 계약을 설명합니다.\n\n")
		out.WriteString("`SecretConsumers.InSecret(ctx, resource.ID(secretID))`는 고정 secret의 consumer association 생성·삭제와 목록을 제공합니다. association은 service·resource_type·resource_id로 식별하며 별도 consumer ID를 만들지 않습니다. 생성·삭제는 실제 HTTP200 secret 응답을 반환하고 목록은 advertised offset next를 따릅니다. [SecretConsumer Python/Go 사용법](secretconsumers/README.md)에 세 proxy 연산·삭제 404 기본값·고정 부모·응답과 Python의 seeded Resource 차이를 설명합니다.\n\n")
	}
	if key == "messaging/v2" {
		out.WriteString("`Subscriptions.InQueue(ctx, queueName)`는 caller가 지정한 queue 이름을 추가 조회 없이 고정합니다. scope의 Create·Get·List/All은 SDK 소유 Subscription 모델을 반환하고 Delete는 error만 반환합니다. 생성은 POST201 응답의 선택적인 subscription_id와 실제 원문을 보존합니다. Location은 collection URL일 수 있어 item ID로 해석하거나 따라가지 않습니다. 연결의 안정적인 Client-ID를 사용하며 목록은 Python MessageResource의 행 수 limit·마지막 ID marker 방식으로 순회합니다. [Subscription Python/Go 사용법](subscriptions/README.md)에 호출별 project header·TTL 생략·소비 제어·삭제 404 기본값과 남은 Resource/cache 계약을 설명합니다.\n\n")
	}
	switch key {
	case "instanceha/v1":
		out.WriteString("Masakari는 `instance-ha` service type을 사용합니다. catalog의 `/v1/{project}`와 reverse-proxy prefix를 보존합니다. route ID는 UUID이며 별도 데이터베이스 ID는 원문으로 보존합니다. `Segments`의 `enabled` 요청은 numeric microversion 1.2 이상, `VMoves.InNotification(ctx, ref)`는 1.3 이상을 요구합니다. [Segments](segments/README.md), [고정 Segment의 Hosts](hosts/README.md), [Notifications](notifications/README.md), [고정 Notification의 VMoves](vmoves/README.md)에서 15개 실제 리소스 연산과 [대기 정책](waiting/README.md)의 두 proxy wait 대응을 확인합니다. 네 fetch 가능한 리소스의 WaitForStatus/WaitForDelete는 무제한·ERROR 실패·2초 간격 상태 대기와 120초 삭제 대기를 제공합니다. Host·VMove는 고정 부모 범위를 유지하고 VMove GET은 1.3 이상을 재검사합니다. 전체 17개 직접 선언 연산에 대응하는 API를 제공하며 marker fallback·nullable 입력·Resource/cache의 전체 계약은 추가 비교가 필요합니다.\n\n")
	case "clustering/v1":
		out.WriteString("`Profiles`, `Policies`, `Clusters`, `Nodes`, `Receivers`의 `FindIdentity(ctx, identity, options...)`는 이름·UUID·짧은 ID 문자열을 GET-first로 찾고 GET400/403/404 뒤 literal 이름 query와 모든 advertised 페이지의 정확한 ID/이름·중복 검사를 처리합니다. 기본 미존재는 `nil, nil`이며 `WithFindIgnoreMissing(false)`로 strict, `WithFindFallback`으로 404-only·GET-only를 선택합니다. 호출별 `WithFindHeader`·`WithFindMicroversion`은 두 단계에 동일하게 적용합니다. 기존 explicit ID/Name Find는 유지합니다. [Python/Go 자동 조회 비교](finding/README.md)에 다섯 facade 사용 예제·오류·canonical 식별자·옵션 소유권을 설명합니다.\n\n")
		out.WriteString("Senlin은 `clustering` service type을 사용합니다. 버전 없는 catalog endpoint에는 `/v1`을 추가하고 이미 있는 버전과 prefix는 보존합니다. `BuildInfo.Get(ctx)`는 singleton이며 타입 catalog의 route ID는 정확한 이름입니다. `Profiles`와 `Policies`는 생성·조회·목록·객체 PATCH 갱신·삭제·이름 검색과 numeric microversion 1.2 이상의 Validate를 제공합니다. `Clusters`와 `Nodes`도 concrete 생성·조회·목록·갱신·삭제·이름 검색을 제공하며, 비동기 202 요청의 action 참조를 보존합니다. `Receivers`는 webhook/message의 동기 CRUD·목록·이름 검색을 제공하고, 목록의 UserID는 wire `user`와 numeric microversion 1.4 이상을 사용합니다. cluster profile_only는 1.6 이상, node tainted는 1.13 이상을 요구합니다. optional 입력은 생략/null/false/zero를 구분하고 로컬 Body 필터는 서버 query로 보내지 않습니다. `ProfileTypes.Operations(ctx, name)`은 1.4 이상, `Services.List(ctx)`는 1.7 이상을 요구합니다. [Profiles](profiles/README.md), [Policies](policies/README.md), [Clusters](clusters/README.md), [Nodes](nodes/README.md), [Receivers](receivers/README.md), [BuildInfo](buildinfo/README.md), [ProfileTypes](profiletypes/README.md), [PolicyTypes](policytypes/README.md), [Actions](actions/README.md), [Events](events/README.md), [Services](services/README.md)와 [ClusterPolicies](clusterpolicies/README.md), [ClusterAttributes](clusterattributes/README.md)에서 69개 직접 선언 연산에 대응하는 API를 확인합니다. cluster scale/resize/membership/check/recover/operation과 policy attach/detach/update, node check/recover/operation은 accepted action을 반환하고, Actions.Update/Cancel은 1.12 이상의 취소 요청과 원문 응답을 제공합니다. Nodes.Adopt/AdoptPreview는 1.7 이상의 flat JSON 요청과 HTTP 200 응답을 제공합니다. cluster ReplaceNodes는 1.3, RemoveNodes의 destroy_after_deletion은 1.4, cluster/node operation은 1.4, recover.check는 1.6, cluster recover.check_capacity는 1.7 이상을 요구합니다. 고정 ClusterPolicy scope를 포함한 10개 fetch 가능한 리소스의 `WaitForStatus`와 `WaitForDelete`는 [Senlin 대기 정책](waiting/README.md)을 제공합니다. 상태 대기의 기본값은 무제한·ERROR 실패·2초 간격이고 삭제 대기는 120초입니다. caller context와 뒤의 wait 옵션이 기본값을 제어하며, 공통 Resources.Wait의 5분 정책과 구별합니다. [변경 추적](tracking/README.md)의 Profiles/Policies와 [비동기 변경 추적](tracking/async/README.md)의 Clusters/Nodes는 SDK 소유 Track·Load·Edit·Commit·Refresh로 dirty 필드만 PATCH하고 부분 응답을 병합합니다. Cluster/Node는 202의 Operation·Body·Header를 독립 snapshot하며 clean은 접수 revision만 뜻합니다. Cluster profile_only의 명시 null은 `WithUpdateProfileOnlyNull()`로 보존하고 bool/null 모두 1.6 gate를 검사합니다. [Update 경로 scope](scoping/README.md)의 `Clusters/Nodes.AtBasePath(path)`는 literal collection을 고정한 Update·Load·Track과 후속 Commit·Refresh를 제공하며 원래 service/actions 경로와 client를 유지합니다. [Receiver 변경 추적](tracking/receivers/README.md)은 동기 PATCH 200·dirty-only Commit·raw 응답 분리·고정 Refresh와 `Receivers.AtBasePath(path)` scope를 제공합니다. Receiver Action은 명령 이름이며 Location/Channel을 action으로 변환하지 않습니다. ClusterPolicies는 binding ID와 policy route ID를 구별하고 고정 부모의 읽기만 제공합니다. ClusterAttributes는 1.2 이상의 고정 cluster·JSONPath 범위에서 raw node 값을 수집합니다. [Cluster metadata](clusters/metadata/README.md)는 실제 cluster GET과 비동기 PATCH를 사용해 조회·병합·키 삭제를 제공합니다. 별도 metadata endpoint를 만들지 않으며 Previous/Requested와 accepted Operation을 구분합니다. metadata 전체 교체의 동시 변경 한계와 다른 Resource/cache/list 계약은 추가 비교가 필요합니다.\n\n")
		out.WriteString("11개 typed 목록과 대응 Resources의 [Senlin 목록 제어](listing/README.md)는 `WithListMaxItems`/`WithListPaginated` 및 `resource.WithMaxItems`/`resource.WithPaginated`를 제공합니다. MaxItems는 로컬 필터 이전의 raw 행 소비량을 제한하고 0은 무제한이며, Paginated=false는 첫 응답만 소비합니다. 명시 wire limit은 보존하고 cap에 도달하면 다음 행과 continuation을 처리하지 않습니다. ClusterPolicies는 cap을 로컬에만 적용하고 초기 limit/marker를 거부합니다. 나머지 10개 목록은 명시 limit이 없으면 cap을 limit hint로 보내며 type catalog와 Services의 hint 지원은 deployment가 판정합니다. 빈 페이지에서는 next link가 있어도 끝냅니다. 이 소비 제어의 구현과 전체 list 선언의 완료 판정은 별개이며 per-call base_path, JMESPath와 리소스별 Body/query/fallback 차이는 추가 비교 범위입니다.\n\n")
		out.WriteString("11개 typed List/All은 패키지별 `WithListFilter(key, value)`로 pinned known Body 필드를 로컬에서 비교합니다. JSON snapshot·필드 alias·정확한 숫자·재귀 object subset을 SDK가 처리하며 builder interface는 필요하지 않습니다. concrete 옵션은 서버 query를 선택하고 WithListFilter는 raw cap·ID 검증 뒤의 로컬 비교를 선택합니다. Go 모델의 추가 필드나 URI 속성을 자동으로 필터에 포함하지 않고 raw Body 키를 WithListQuery로 보내는 것을 거부합니다. 공통 Resources에는 Name/Status 옵션을 유지하며 임의 Body 필터를 추가하지 않습니다. [Body 필터와 Python 차이](listing/README.md#명시적인-raw-body-필터)를 참고합니다.\n\n")
		out.WriteString("11개 typed `List/All`에는 `WithListHeader(key, value)`와 `WithListMicroversion(\"1.7\")`로 호출별 헤더·숫자 버전을 선택합니다. 명시 옵션은 공유 client를 수정하지 않고 모든 페이지에 유지하며 인증은 공유 provider의 최신 token을 사용합니다. 서비스별 버전 조건은 호출 선택을 기준으로 재검사하고 인증/version/transport header를 직접 덮어쓰는 것은 거부합니다. `headers`, `microversion`, `base_path` 등 로컬 제어 key는 확장 query로 보낼 수 없습니다. 공통 Resources와 부모 해석·다른 Get/Wait는 이 typed 옵션을 받지 않습니다. [목록 호출 옵션과 Python 비교](listing/README.md#목록-호출별-헤더와-버전)에서 기본값과 소유권 차이를 확인합니다.\n\n")
	case "baremetal/v1":
		out.WriteString("`Nodes.GetVirtualMedia`는 SDK의 `VirtualMedia` 모델에 연결한 이미지, 삽입 상태, 매체 종류를 반환합니다. [virtual media 조회 사용법](nodes/README.md)을 참고합니다.\n\n")
		out.WriteString("`Conductors.Resources`는 `Conductor.Hostname`을 ID와 이름으로 사용합니다. `resource.ID(\"conductor-01\")`는 직접 조회하고 `resource.Name(\"conductor-01\")`는 전체 목록에서 정확히 찾습니다. `Drivers.Resources`의 ID와 이름은 `Driver.Name`입니다. 두 리소스는 조회·목록·이름 검색만 제공하며 삭제와 상태 대기는 `ErrUnsupported`입니다. [conductor](conductors/README.md), [driver](drivers/README.md) 사용법을 참고합니다.\n\n")
		out.WriteString("Conductor endpoint는 microversion 1.49 이상을 요구합니다. 연결에 `sdk.WithMicroversion(sdk.BareMetal, \"1.49\")` 또는 `sdk.WithMicroversionRange(sdk.BareMetal, \"1.49\", \"latest\")`를 지정합니다. SDK는 이 연산을 호출한다고 연결 버전을 자동으로 올리지 않습니다. [Conductor 버전 요구와 API 근거](conductors/README.md)를 참고합니다.\n\n")
	case "baremetalintrospection/v1":
		out.WriteString("`Introspection.Resources`는 node와 같은 UUID로 조회하고 목록을 순회합니다. 이름·Status·Delete는 가정하지 않습니다. `Introspection.WaitUntilFinished(ctx, ref, waitOptions...)`는 `Finished`를 기다리고 실제 `Error`를 `IntrospectionFailureError`에 보존합니다. `StartIntrospection`은 SDK 소유 helper로 pinned native 함수의 query 누락을 보정해 `ManageBoot`의 nil/false/true와 확장 query를 전달합니다. [시작·조회·완료 대기 사용법](introspection/README.md)을 참고합니다.\n\n")
	case "identity/v2":
		out.WriteString("`Tokens.Create/Get`은 SDK의 `Authentication`을 반환합니다. `Token`, `User`, `Catalog`를 한 번에 해석하고 `Header`와 추가 응답 필드를 포함한 JSON `Body`도 보존합니다. [인증 응답 사용법](tokens/README.md)을 참고합니다.\n\n")
	case "compute/v2":
		out.WriteString("`conn.ProjectQuotas(ctx, project)`와 `CurrentProjectQuotas(ctx)`는 Nova quota를 고정된 프로젝트 singleton으로 제공합니다. `scope.InUser(ctx, user)`는 project+user quota를 고정합니다. nil/zero/-1 limit과 명시적 force, 별도 Defaults와 사용자 query·redirect·retry 계약은 [프로젝트 quota 사용법](quotasets/README.md)에 설명합니다.\n\n")
		out.WriteString("`Limits.Fetch(ctx)`는 현재 프로젝트의 읽기 전용 limits 응답을 보존하고 `conn.ProjectLimits(ctx, project)`는 프로젝트 query를 고정합니다. reserved 0/1, legacy rate와 raw HTTP 응답의 의미는 [limits 사용법](limits/README.md)을 참고합니다.\n\n")
		out.WriteString("`Servers.GetPassword`는 기본적으로 암호화된 문자열을 반환합니다. RSA 복호화는 `servers.WithGetPasswordPrivateKey(key)`로 선택합니다. [암호 조회 사용법](servers/README.md)을 참고합니다.\n\n")
		out.WriteString("`Tags.InServer(ctx, serverRef)`는 서버 이름/ID를 한 번 해석한 뒤 Add/Check/List/Replace/Remove/RemoveAll을 제공합니다. tag set은 Collection이 아니며 실제 선택 microversion 2.26 이상을 요구합니다. [태그의 빈 목록·404 정책과 Python 대응](tags/README.md)을 참고합니다.\n\n")
		out.WriteString("`InstanceActions.InServer(ctx, serverRef)`는 requestID로 상세를 조회하고 이력을 페이지 순회합니다. SDK의 `ActionResource`는 목록과 상세를 구분하고 추가 event 정보·원본 JSON·헤더를 보존합니다. [이력 조회와 버전·권한 조건](instanceactions/README.md)을 참고합니다.\n\n")
	case "blockstorage/v3":
		out.WriteString("`conn.BlockStorageProjectQuotas(ctx, project)`와 `CurrentBlockStorageProjectQuotas(ctx)`는 Cinder quota를 고정된 프로젝트 singleton으로 제공합니다. 별도 defaults·usage 조회와 볼륨 타입 quota, DELETE 200·명시적 force 계약은 [프로젝트 quota 사용법](quotasets/README.md)을 참고합니다.\n\n")
		out.WriteString("`Limits.Fetch(ctx)`는 현재 프로젝트의 읽기 전용 limits 응답을 보존하고 `conn.BlockStorageProjectLimits(ctx, project)`는 프로젝트 query를 고정합니다. 프로젝트 필터는 실제 요청 버전 3.39 이상이 필요하며 [limits 사용법](limits/README.md)에 버전·typed/raw 응답을 설명합니다.\n\n")
	case "network/v2":
		out.WriteString("`conn.NetworkProjectQuotas(ctx, project)`와 `CurrentNetworkProjectQuotas(ctx)`는 Neutron quota를 고정된 프로젝트 singleton으로 제공합니다. Get/Defaults/Detail/Update/Delete와 check_limit, 별도 ListProjects/AllProjects 목록·로컬 소비 옵션은 [프로젝트 quota 사용법](extensions/quotas/README.md)을 참고합니다.\n\n")
	case "loadbalancer/v2":
		out.WriteString("`conn.LoadBalancerProjectQuotas(ctx, project)`와 `CurrentLoadBalancerProjectQuotas(ctx)`는 Octavia quota의 프로젝트를 고정합니다. Get/Update/Reset, 전역 Defaults와 별도 ListProjects/AllProjects, 공식 lbaas 경로와 native URL의 차이는 [quota 사용법](quotas/README.md)을 참고합니다.\n\n")
	case "sharedfilesystems/v2":
		out.WriteString("`conn.SharedFileSystemProjectQuotas(ctx, project)`와 `CurrentSharedFileSystemProjectQuotas(ctx)`는 Manila quota의 프로젝트를 고정합니다. Get/Defaults/Detail/Update/Reset과 microversion별 경로는 [quota 사용법](quotasets/README.md)을 참고합니다. 이 quota API는 pinned Gophercloud에 없어 SDK가 직접 구현합니다.\n\n")
		out.WriteString("`service.QuotaClassSets.InClass(ctx, \"default\")`는 class 이름을 고정해 Get/Update를 제공합니다. 프로젝트 해석이나 List/Reset은 없으며 [quota class 사용법](quotaclasssets/README.md)에 Python 대응과 typed limit·확장 입력을 설명합니다.\n\n")
		out.WriteString("`ShareAccessRules.InShare(ctx, share)`의 typed scope 목록은 `WithListMaxItems(n)`과 `WithListPaginated(false)`로 소비량을 제어합니다. 현대 access endpoint는 한 collection을 반환하므로 next link를 따르거나 cap을 wire limit으로 보내지 않습니다. 숫자 2.45 이상과 실제 Manila service type/version header를 재검사하며 canonical lowercase 응답 ID·부모를 보호합니다. [access rule 사용법과 Python 비교](shareaccessrules/README.md)에서 Allow/Deny·대기·응답 증거와 차이를 확인합니다.\n\n")
	case "dns/v2":
		out.WriteString("`conn.DNSProjectQuotas(ctx, project)`와 `CurrentDNSProjectQuotas(ctx)`는 Designate quota의 프로젝트를 고정합니다. Get/PATCH Update/DELETE Reset과 sudo-project·all-projects header는 [quota 사용법](quotas/README.md)을 참고합니다. 별도 defaults endpoint나 프로젝트 quota 목록은 제공하지 않습니다.\n\n")
	case "containerinfra/v1":
		out.WriteString("`conn.ContainerInfraProjectQuotas(ctx, project)`와 `CurrentContainerInfraProjectQuotas(ctx)`로 프로젝트를 고정한 뒤 `ForResource(quotas.Cluster)`로 quota를 선택합니다. Get/Create/PATCH Update/DELETE와 explicit hard limit, API.List/All의 페이지 순회·all_tenants 보존, Python에 quota 선언이 없는 차이는 [quota 사용법](quotas/README.md)을 참고합니다.\n\n")
	case "db/v1":
		out.WriteString("`Databases.InInstance(ctx, instanceRef)`와 `Users.InInstance(ctx, instanceRef)`는 instance를 한 번 고정합니다. pinned SDK가 자식별 fetch를 노출하지 않아 Get/Find는 같은 instance의 목록에서 정확한 이름을 검색합니다. 단일 Create와 CreateBatch는 배열 요청을 전송하며 비동기 응답에 객체가 없으므로 error를 반환합니다. [데이터베이스](databases/README.md), [사용자](users/README.md)의 식별자·삭제·지원 제약을 참고합니다.\n\n")
	case "objectstorage/v1":
		out.WriteString("Python의 `conn.object_store.containers()`와 `objects(container)`에 대응하는 Go 목록은 `Containers.List`와 `Objects.List`입니다. 이름만 반환하지 않고 `Container`의 `Name/Count/Bytes`, `Object`의 `Name/Bytes/ContentType/Hash/LastModified` 등 typed 정보를 반환합니다. delimiter로 얻는 항목은 `Object.Subdir`에 보존합니다.\n\n")
		out.WriteString("`Containers.Resources`와 `Objects.InContainer(ctx, parent)`는 공통 리소스 정책을 제공합니다. HEAD로 조회하면 SDK의 `ContainerResource/ObjectResource`가 typed 정보와 사용자 metadata, 전체 헤더를 함께 보관합니다. [Swift 리소스 사용법](objects/README.md)을 참고합니다.\n\n")
	}
	var example *collectionRecord
	for i := range g.collections {
		record := &g.collections[i]
		if record.Model != "" && record.Kind != "service_info" && record.Scope == "" && strings.HasPrefix(record.Package, "gophercloudsdk/"+key+"/") {
			example = record
			if strings.TrimPrefix(record.Package, "gophercloudsdk/"+key+"/") == exampleResources[parts[0]] {
				break
			}
		}
	}
	out.WriteString("## Go 사용\n\n```go\n")
	fmt.Fprintf(&out, "// context.Context ctx, *gophercloudsdk.Connection conn을 사용하는 함수 안에서\nservice, err := conn.%s(ctx)\nif err != nil { return err }\n", method)
	if example != nil {
		field := registryField(strings.TrimPrefix(example.Package, "gophercloudsdk/"+key+"/"))
		accessor := "service." + field + ".Resources"
		finder := "service." + field
		if example.Source == "sdk_owned" {
			finder = accessor
		}
		if example.Kind == "compound_identity" {
			accessor += "()"
			finder = accessor
		}
		fmt.Fprintf(&out, "for value, err := range %s.List(ctx) {\n    if err != nil { return err }\n    fmt.Println(value)\n}\n", accessor)
		if example.Find {
			fmt.Fprintf(&out, "value, err := %s.Find(ctx, resource.Name(\"example\"))\nif err != nil { return err }\n_ = value\n", finder)
		}
	} else {
		if parts[0] == "metric" {
			out.WriteString("data, err := service.Metrics.Query(ctx, metrics.QueryOpts{Query: \"up\"})\nif err != nil { return err }\nfmt.Println(data)\n")
		} else if err := g.writeListExample(&out, key, paths); err != nil {
			return err
		}
	}
	out.WriteString("```\n\n예제의 `fmt`는 표준 라이브러리, `resource`는 `gophercloudsdk/resource`입니다. Find는 기본적으로 미존재를 오류로 처리합니다. `resource.WithIgnoreMissing()`을 추가하면 `nil, nil`을 반환합니다. Delete의 기본값은 미존재 무시입니다.\n\n")
	if parts[0] == "metric" {
		out.WriteString("`metrics`는 `gophercloudsdk/metric/v1/metrics`입니다.\n\n")
	}
	out.WriteString("## 리소스와 공통 정책\n\n| 서비스 필드 | API 패키지 | 공통 정책·범위 |\n|---|---|---|\n")
	for _, path := range paths {
		var policies []string
		apiFile := "api_generated.go"
		for _, record := range g.collections {
			if record.Package != "gophercloudsdk/"+key+"/"+path || record.Model == "" {
				continue
			}
			if record.Source == "sdk_owned" {
				apiFile = "api.go"
			}
			label := "Resources"
			if record.Scope != "" {
				label = record.Scope + "(ctx, parent)"
			}
			if record.Kind == "string_set" {
				policies = append(policies, fmt.Sprintf("`%s`: 문자열 집합 조회·추가·확인·교체·삭제; Collection/상태 대기 없음", label))
				continue
			}
			if record.Kind == "service_info" {
				policies = append(policies, "`Get(ctx)`: 서비스 build 정보 singleton; ID·목록·변경·상태 대기 없음")
				continue
			}
			if record.Kind == "store_defaults" {
				policies = append(policies, "`List/All`, `GetGlobalDefault`, `GetPreferred`: 목록·두 고정 조회; Resources·CRUD·Find·Wait 없음")
				continue
			}
			if record.Kind == "effective_project_quota" {
				policies = append(policies, "`Get(ctx)`: 인증된 프로젝트 effective quota; `InProject(ctx, ID)`: Get·교체 Update·override Delete, 목록·Find·Wait 없음")
				continue
			}
			if record.Kind == "secret_consumer" {
				policies = append(policies, "`InSecret(ctx, ref)`: association Create·Delete와 offset List/All; 실제 secret 응답, consumer ID·Resources·Find·Wait 없음")
				continue
			}
			if record.Kind == "queue_subscription" {
				policies = append(policies, "`InQueue(ctx, queueName)`: 고정 이름의 Create·Get·List/All·Delete; Resources·Find·Wait·Update 없음")
				continue
			}
			if record.Kind == "list_only" {
				policies = append(policies, "`List/All`: 목록만 제공; 단건 조회·변경·상태 대기 없음")
				continue
			}
			if record.Kind == "scoped_list_only" {
				policies = append(policies, "`InCluster(ctx, parent, path)`: 고정 cluster·JSONPath의 List/All; raw node 값 보존, 단건 조회·변경·상태 대기 없음")
				continue
			}
			if record.Kind == "policy_binding" {
				policies = append(policies, "`InCluster(ctx, parent)`: 고정 cluster의 policy 조회·목록·이름 검색; 별도 binding ID 보존, 변경 없음, 기본 status 없음")
				continue
			}
			if record.Kind == "async_resource" {
				policies = append(policies, "`Resources`: ID 조회, 목록, 이름 조회, 상태 대기; `API.Delete`: 비동기 action Submission 반환, Collection.Delete는 미지원")
				continue
			}
			if record.Kind == "singleton" {
				operations := "Get·Defaults·Detail·Update·Reset"
				if strings.HasSuffix(record.Package, "/blockstorage/v3/quotasets") {
					operations = "Get·Defaults·Usage·Update·Reset"
				} else if strings.HasSuffix(record.Package, "/network/v2/extensions/quotas") {
					operations = "Get·Defaults·Detail·Update·Delete"
				} else if strings.HasSuffix(record.Package, "/loadbalancer/v2/quotas") {
					operations = "Get·Update·Reset; Defaults는 전역 조회"
				} else if strings.HasSuffix(record.Package, "/dns/v2/quotas") {
					operations = "Get·Update·Reset"
				}
				policies = append(policies, fmt.Sprintf("`%s`: 고정 프로젝트의 %s; List/Find/Wait 없음", label, operations))
				continue
			}
			if record.Kind == "named_singleton" {
				policies = append(policies, "`InClass(ctx, className)`: 고정 이름의 Get·Update; 프로젝트 해석·List·Reset·Wait 없음")
				continue
			}
			if record.Kind == "project_limits" {
				policies = append(policies, "`Fetch(ctx)` / `InProject(ctx, parent).Get(ctx)`: 현재/고정 프로젝트의 읽기 전용 singleton; List·Find·Wait·변경 없음")
				continue
			}
			if record.Kind == "project_resource_quota" {
				policies = append(policies, "`InProject(ctx, parent).ForResource(name)`: 고정 프로젝트+resource의 Get·Create·Update·Delete; `API.List/All`: quota 페이지 목록; 이름 Find·Wait 없음")
				continue
			}
			if record.Kind == "compound_identity" {
				label = "Resources() / InStack(ctx, ref) / ForStack(identity)"
			}
			if record.Kind == "event_log" {
				policies = append(policies, "`InStack(ctx, ref) / ForStack(identity)`: stack/resource별 이벤트 목록·resource_name+eventID 단건 조회; 이름 Find·변경·대기 없음")
				continue
			}
			if record.Kind == "compound_child" {
				policies = append(policies, "`InStack(ctx, ref) / ForStack(identity)`: resource_name 조회·목록·이름 해석·metadata·health·대기; nested 실제 owner 검증")
				continue
			}
			features := []string{"ID 조회", "목록"}
			if record.Find {
				features = append(features, "이름 조회")
			}
			if record.Delete {
				features = append(features, "삭제·삭제 대기")
			}
			if record.Wait {
				features = append(features, "상태 대기")
			}
			policies = append(policies, fmt.Sprintf("`%s`: %s", label, strings.Join(features, ", ")))
		}
		policy := strings.Join(policies, "; ")
		if policy == "" {
			policy = "API 연산 제공; 공통 Collection 미적용"
		}
		fmt.Fprintf(&out, "| `%s` | [%s](%s/%s) | %s |\n", registryField(path), path, path, apiFile, policy)
	}
	out.WriteString("\n공통 Collection은 정확한 이름 검색, 중복 이름 오류, 페이지 순회, context 취소와 HTTP 오류 보존을 적용합니다. 상태가 없는 리소스의 Wait는 `ErrUnsupported`를 반환합니다.\n\n")
	for _, record := range g.collections {
		if record.Source != "" || record.Model == "" || record.Kind != "" || !strings.HasPrefix(record.Package, "gophercloudsdk/"+key+"/") {
			continue
		}
		out.WriteString("native pager에 연결된 `Resources.List/All`과 부모 scope의 `List/All`은 `resource.WithMaxItems(n)`과 `resource.WithPaginated(false)`로 raw 행 소비량과 첫 페이지를 제어합니다. cap은 로컬 name/status 및 Trove 사용자 host 필터 전에 적용합니다. 0은 무제한이며 음수는 lazy 순회 시 HTTP 전에 오류입니다. native 경로는 cap을 wire limit hint로 보내지 않고 명시 페이지 크기·query·header를 보존합니다. 페이지 전체 extraction 때문에 cap 뒤 malformed 행도 오류를 낼 수 있습니다. 기존 native typed `List`의 작업별 옵션은 유지하며, 공통 소비 옵션은 Collection/scope에 전달합니다. [서비스별 Python/Go 목록 비교](../../docs/listing.md)에서 실제 binding과 continuation 정책을 확인합니다.\n\n")
		break
	}
	out.WriteString("## 변경 요청\n\n리소스 API의 Create/Update에 concrete options를 전달합니다. 기본 필드는 typed options로 지정하고 추가 필드는 `With...Field`로 지정합니다. query와 header도 해당 연산이 제공하는 `With...` 함수를 사용합니다. 기본 필드·헤더 덮어쓰기와 지원되지 않는 확장 방식은 요청 전에 거부합니다. 요청 builder interface는 SDK가 구현합니다.\n\n")
	out.WriteString("부모가 필요한 연산은 [범위 객체](../../docs/scoped-resources.md)를 사용합니다. 범위 객체가 제공하는 Create/Update에도 같은 concrete options를 사용합니다. 응답 변경 추적이나 Python cloud의 모든 복합 작업은 이 API 참조 페이지의 지원 범위를 뜻하지 않습니다.\n\n")
	out.WriteString("전체 비교 기준은 [openstacksdk 목록](../../api/openstacksdk/README.md), Go API 호출은 [전체 API 설명](../../api/README.md), 실행·검증은 [프로젝트 README](../../README.md)를 참고합니다.\n")
	return os.WriteFile(filepath.Join(g.root, key, "README.md"), []byte(out.String()), 0644)
}

// Where no common Collection exists yet, show a real typed list operation.
func (g *generator) writeListExample(out *strings.Builder, key string, paths []string) error {
	for _, path := range paths {
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(g.root, key, path, "api_generated.go"), nil, 0)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || !strings.HasPrefix(fn.Name.Name, "List") {
				continue
			}
			params := fn.Type.Params.List
			if len(params) != 1 {
				if len(params) != 2 {
					continue
				}
				if _, ok := params[1].Type.(*ast.Ellipsis); !ok {
					continue
				}
			}
			fmt.Fprintf(out, "for value, err := range service.%s.%s(ctx) {\n    if err != nil { return err }\n    fmt.Println(value)\n}\n", registryField(path), fn.Name.Name)
			return nil
		}
	}
	out.WriteString("// 아래 리소스 표에서 필요한 연산과 concrete options를 선택합니다.\nfmt.Println(service.RawClient().Endpoint)\n")
	return nil
}
