package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var pythonServiceNames = map[string]string{
	"baremetalintrospection": "baremetal_introspection", "blockstorage": "block_storage",
	"containerinfra": "container_infrastructure_management", "db": "database",
	"keymanager": "key_manager", "loadbalancer": "load_balancer", "messaging": "message",
	"objectstorage": "object_store", "sharedfilesystems": "shared_file_system",
	"instanceha": "instance_ha",
}

var exampleResources = map[string]string{
	"baremetal": "nodes", "blockstorage": "volumes", "compute": "servers", "containerinfra": "clusters", "db": "instances",
	"dns": "zones", "identity": "users", "image": "images", "keymanager": "secrets", "loadbalancer": "loadbalancers",
	"network": "networks", "placement": "resourceproviders", "reservation": "leases", "sharedfilesystems": "shares", "workflow": "workflows",
	"instanceha": "segments", "clustering": "profiletypes",
}

// Versioned reference pages are derived from the same API and resource inventory
// as the code, keeping registry fields and common-policy coverage reviewable.
func (g *generator) writeServiceREADME(key string, spec serviceSpec, paths []string) error {
	parts := strings.Split(key, "/")
	python := pythonServiceNames[parts[0]]
	if python == "" {
		python = parts[0]
	}
	method := spec.name + strings.ToUpper(parts[1][:1]) + parts[1][1:]
	var out strings.Builder
	fmt.Fprintf(&out, "# %s %s\n\n<!-- Generated by sdkgen; edit internal/cmd/sdkgen/service_docs.go. -->\n\n", spec.name, parts[1])
	sdkOwnedService := parts[0] == "clustering" || parts[0] == "instanceha"
	if sdkOwnedService {
		fmt.Fprintf(&out, "%s API는 pinned Gophercloud에 없어 SDK가 직접 구현합니다. pinned openstacksdk와 공식 API 계약을 기준으로 구현한 아래 리소스를 하나의 인증된 서비스 객체에서 사용합니다. 인증, region, endpoint interface와 TLS 설정은 Connection이 관리합니다.\n\n", key)
	} else {
		fmt.Fprintf(&out, "Gophercloud v2.15.0의 %s API를 하나의 인증된 서비스 객체에서 사용합니다. 인증, region, endpoint interface와 TLS 설정은 Connection이 관리합니다.\n\n", key)
	}
	pythonAccess := "`conn." + python + "`"
	if parts[0] == "metric" {
		pythonAccess = "직접 대응하는 서비스 없음 (Aetos)"
	}
	fmt.Fprintf(&out, "| 작업 | openstacksdk | Go |\n|---|---|---|\n| 서비스 접근 | %s | `conn.%s(ctx)` |\n| 선택 인자·기본값 | keyword arguments | concrete options와 작업별 `With...Options` |\n| 확장 입력 | `**attrs`, `**query` | 가능한 연산의 `With...Field/Query/Header` |\n| 결과 | Resource 또는 generator | typed 값과 error 또는 `iter.Seq2` |\n\n", pythonAccess, method)
	out.WriteString("전체 API 호출 지원과 openstacksdk의 리소스 객체·복합 작업 지원은 별도로 추적합니다. Python 입력 별칭을 자동으로 Go 필드에 적용하지 않습니다. ")
	if sdkOwnedService {
		out.WriteString("응답은 SDK의 typed 모델이며 원문 필드·HTTP 헤더·상태 코드를 함께 보존합니다. Python의 permissive flat/empty 응답 fallback과 달리 각 endpoint의 명시한 object envelope를 검증합니다. ")
	} else {
		out.WriteString("기본 응답 모델은 Gophercloud 타입을 사용하며 SDK가 추가한 모델은 서비스별로 설명합니다. ")
	}
	out.WriteString("수정한 응답이 자동 저장되지는 않습니다.\n\n")
	if parts[0] == "metric" {
		out.WriteString("이 버전은 Aetos의 Prometheus API입니다. Python openstacksdk의 Gnocchi metric 서비스와 기능이 같지 않습니다.\n\n")
	}
	switch key {
	case "instanceha/v1":
		out.WriteString("Masakari는 `instance-ha` service type을 사용합니다. catalog의 `/v1/{project}`와 reverse-proxy prefix를 보존합니다. route ID는 UUID이며 별도 데이터베이스 ID는 원문으로 보존합니다. `Segments`의 `enabled` 요청은 numeric microversion 1.2 이상, `VMoves.InNotification(ctx, ref)`는 1.3 이상을 요구합니다. [Segments](segments/README.md), [고정 Segment의 Hosts](hosts/README.md), [Notifications](notifications/README.md), [고정 Notification의 VMoves](vmoves/README.md)에서 15개 실제 리소스 연산·Python 대응을 확인합니다. marker fallback·nullable 입력·Resource/cache와 proxy wait의 전체 계약은 추가 비교가 필요합니다.\n\n")
	case "clustering/v1":
		out.WriteString("Senlin은 `clustering` service type을 사용합니다. 버전 없는 catalog endpoint에는 `/v1`을 추가하고 이미 있는 버전과 prefix는 보존합니다. `BuildInfo.Get(ctx)`는 singleton이며 타입 catalog의 route ID는 정확한 이름입니다. `Profiles`와 `Policies`는 생성·조회·목록·객체 PATCH 갱신·삭제·이름 검색과 numeric microversion 1.2 이상의 Validate를 제공합니다. `Clusters`와 `Nodes`도 concrete 생성·조회·목록·갱신·삭제·이름 검색을 제공하며, 비동기 202 요청의 action 참조를 보존합니다. cluster profile_only는 1.6 이상, node tainted는 1.13 이상을 요구합니다. optional 입력은 생략/null/false/zero를 구분하고 로컬 Body 필터는 서버 query로 보내지 않습니다. `ProfileTypes.Operations(ctx, name)`은 1.4 이상, `Services.List(ctx)`는 1.7 이상을 요구합니다. [Profiles](profiles/README.md), [Policies](policies/README.md), [Clusters](clusters/README.md), [Nodes](nodes/README.md), [BuildInfo](buildinfo/README.md), [ProfileTypes](profiletypes/README.md), [PolicyTypes](policytypes/README.md), [Actions](actions/README.md), [Events](events/README.md), [Services](services/README.md)에서 47개 직접 선언 연산에 대응하는 API를 확인합니다. cluster scale/resize/membership과 node check/recover/operation은 accepted action을 반환하고, Actions.Update/Cancel은 1.12 이상의 취소 요청과 원문 응답을 제공합니다. cluster ReplaceNodes는 1.3, RemoveNodes의 destroy_after_deletion은 1.4, node operation은 1.4, recover.check는 1.6 이상을 요구합니다. node adopt·cluster metadata/policy 및 추가 명령·proxy wait와 Resource/cache/dirty state의 전체 계약은 아직 pending입니다.\n\n")
	case "baremetal/v1":
		out.WriteString("`Nodes.GetVirtualMedia`는 SDK의 `VirtualMedia` 모델에 연결한 이미지, 삽입 상태, 매체 종류를 반환합니다. [virtual media 조회 사용법](nodes/README.md)을 참고합니다.\n\n")
		out.WriteString("`Conductors.Resources`는 `Conductor.Hostname`을 ID와 이름으로 사용합니다. `resource.ID(\"conductor-01\")`는 직접 조회하고 `resource.Name(\"conductor-01\")`는 전체 목록에서 정확히 찾습니다. `Drivers.Resources`의 ID와 이름은 `Driver.Name`입니다. 두 리소스는 조회·목록·이름 검색만 제공하며 삭제와 상태 대기는 `ErrUnsupported`입니다. [conductor](conductors/README.md), [driver](drivers/README.md) 사용법을 참고합니다.\n\n")
		out.WriteString("Conductor endpoint는 microversion 1.49 이상을 요구합니다. 연결에 `sdk.WithMicroversion(sdk.BareMetal, \"1.49\")` 또는 `sdk.WithMicroversionRange(sdk.BareMetal, \"1.49\", \"latest\")`를 지정합니다. SDK는 이 연산을 호출한다고 연결 버전을 자동으로 올리지 않습니다. [Conductor 버전 요구와 API 근거](conductors/README.md)를 참고합니다.\n\n")
	case "baremetalintrospection/v1":
		out.WriteString("`Introspection.Resources`는 node와 같은 UUID로 조회하고 목록을 순회합니다. 이름·Status·Delete는 가정하지 않습니다. `Introspection.WaitUntilFinished(ctx, ref, waitOptions...)`는 `Finished`를 기다리고 실제 `Error`를 `IntrospectionFailureError`에 보존합니다. `StartIntrospection`은 SDK 소유 helper로 pinned native 함수의 query 누락을 보정해 `ManageBoot`의 nil/false/true와 확장 query를 전달합니다. [시작·조회·완료 대기 사용법](introspection/README.md)을 참고합니다.\n\n")
	case "identity/v2":
		out.WriteString("`Tokens.Create/Get`은 SDK의 `Authentication`을 반환합니다. `Token`, `User`, `Catalog`를 한 번에 해석하고 `Header`와 추가 응답 필드를 포함한 JSON `Body`도 보존합니다. [인증 응답 사용법](tokens/README.md)을 참고합니다.\n\n")
	case "compute/v2":
		out.WriteString("`conn.ProjectQuotas(ctx, project)`와 `CurrentProjectQuotas(ctx)`는 Nova quota를 고정된 프로젝트 singleton으로 제공합니다. `scope.InUser(ctx, user)`는 project+user quota를 고정합니다. nil/zero/-1 limit과 명시적 force, 별도 Defaults와 사용자 query·redirect·retry 계약은 [프로젝트 quota 사용법](quotasets/README.md)에 설명합니다.\n\n")
		out.WriteString("`Limits.Fetch(ctx)`는 현재 프로젝트의 읽기 전용 limits 응답을 보존하고 `conn.ProjectLimits(ctx, project)`는 프로젝트 query를 고정합니다. reserved 0/1, legacy rate와 raw HTTP 응답의 의미는 [limits 사용법](limits/README.md)을 참고합니다.\n\n")
		out.WriteString("`Servers.GetPassword`는 기본적으로 암호화된 문자열을 반환합니다. RSA 복호화는 `servers.WithGetPasswordPrivateKey(key)`로 선택합니다. [암호 조회 사용법](servers/README.md)을 참고합니다.\n\n")
		out.WriteString("`Tags.InServer(ctx, serverRef)`는 서버 이름/ID를 한 번 해석한 뒤 Add/Check/List/Replace/Remove/RemoveAll을 제공합니다. tag set은 Collection이 아니며 실제 선택 microversion 2.26 이상을 요구합니다. [태그의 빈 목록·404 정책과 Python 대응](tags/README.md)을 참고합니다.\n\n")
		out.WriteString("`InstanceActions.InServer(ctx, serverRef)`는 requestID로 상세를 조회하고 이력을 페이지 순회합니다. SDK의 `ActionResource`는 목록과 상세를 구분하고 추가 event 정보·원본 JSON·헤더를 보존합니다. [이력 조회와 버전·권한 조건](instanceactions/README.md)을 참고합니다.\n\n")
	case "blockstorage/v3":
		out.WriteString("`conn.BlockStorageProjectQuotas(ctx, project)`와 `CurrentBlockStorageProjectQuotas(ctx)`는 Cinder quota를 고정된 프로젝트 singleton으로 제공합니다. 별도 defaults·usage 조회와 볼륨 타입 quota, DELETE 200·명시적 force 계약은 [프로젝트 quota 사용법](quotasets/README.md)을 참고합니다.\n\n")
		out.WriteString("`Limits.Fetch(ctx)`는 현재 프로젝트의 읽기 전용 limits 응답을 보존하고 `conn.BlockStorageProjectLimits(ctx, project)`는 프로젝트 query를 고정합니다. 프로젝트 필터는 실제 요청 버전 3.39 이상이 필요하며 [limits 사용법](limits/README.md)에 버전·typed/raw 응답을 설명합니다.\n\n")
	case "network/v2":
		out.WriteString("`conn.NetworkProjectQuotas(ctx, project)`와 `CurrentNetworkProjectQuotas(ctx)`는 Neutron quota를 고정된 프로젝트 singleton으로 제공합니다. Get/Defaults/Detail/Update/Delete와 check_limit, 별도 ListProjects/AllProjects 목록·로컬 소비 옵션은 [프로젝트 quota 사용법](extensions/quotas/README.md)을 참고합니다.\n\n")
	case "loadbalancer/v2":
		out.WriteString("`conn.LoadBalancerProjectQuotas(ctx, project)`와 `CurrentLoadBalancerProjectQuotas(ctx)`는 Octavia quota의 프로젝트를 고정합니다. Get/Update/Reset, 전역 Defaults와 별도 ListProjects/AllProjects, 공식 lbaas 경로와 native URL의 차이는 [quota 사용법](quotas/README.md)을 참고합니다.\n\n")
	case "sharedfilesystems/v2":
		out.WriteString("`conn.SharedFileSystemProjectQuotas(ctx, project)`와 `CurrentSharedFileSystemProjectQuotas(ctx)`는 Manila quota의 프로젝트를 고정합니다. Get/Defaults/Detail/Update/Reset과 microversion별 경로는 [quota 사용법](quotasets/README.md)을 참고합니다. 이 quota API는 pinned Gophercloud에 없어 SDK가 직접 구현합니다.\n\n")
		out.WriteString("`service.QuotaClassSets.InClass(ctx, \"default\")`는 class 이름을 고정해 Get/Update를 제공합니다. 프로젝트 해석이나 List/Reset은 없으며 [quota class 사용법](quotaclasssets/README.md)에 Python 대응과 typed limit·확장 입력을 설명합니다.\n\n")
	case "dns/v2":
		out.WriteString("`conn.DNSProjectQuotas(ctx, project)`와 `CurrentDNSProjectQuotas(ctx)`는 Designate quota의 프로젝트를 고정합니다. Get/PATCH Update/DELETE Reset과 sudo-project·all-projects header는 [quota 사용법](quotas/README.md)을 참고합니다. 별도 defaults endpoint나 프로젝트 quota 목록은 제공하지 않습니다.\n\n")
	case "containerinfra/v1":
		out.WriteString("`conn.ContainerInfraProjectQuotas(ctx, project)`와 `CurrentContainerInfraProjectQuotas(ctx)`로 프로젝트를 고정한 뒤 `ForResource(quotas.Cluster)`로 quota를 선택합니다. Get/Create/PATCH Update/DELETE와 explicit hard limit, API.List/All의 페이지 순회·all_tenants 보존, Python에 quota 선언이 없는 차이는 [quota 사용법](quotas/README.md)을 참고합니다.\n\n")
	case "db/v1":
		out.WriteString("`Databases.InInstance(ctx, instanceRef)`와 `Users.InInstance(ctx, instanceRef)`는 instance를 한 번 고정합니다. pinned SDK가 자식별 fetch를 노출하지 않아 Get/Find는 같은 instance의 목록에서 정확한 이름을 검색합니다. 단일 Create와 CreateBatch는 배열 요청을 전송하며 비동기 응답에 객체가 없으므로 error를 반환합니다. [데이터베이스](databases/README.md), [사용자](users/README.md)의 식별자·삭제·지원 제약을 참고합니다.\n\n")
	case "objectstorage/v1":
		out.WriteString("Python의 `conn.object_store.containers()`와 `objects(container)`에 대응하는 Go 목록은 `Containers.List`와 `Objects.List`입니다. 이름만 반환하지 않고 `Container`의 `Name/Count/Bytes`, `Object`의 `Name/Bytes/ContentType/Hash/LastModified` 등 typed 정보를 반환합니다. delimiter로 얻는 항목은 `Object.Subdir`에 보존합니다.\n\n")
		out.WriteString("`Containers.Resources`와 `Objects.InContainer(ctx, parent)`는 공통 리소스 정책을 제공합니다. HEAD로 조회하면 SDK의 `ContainerResource/ObjectResource`가 typed 정보와 사용자 metadata, 전체 헤더를 함께 보관합니다. [Swift 리소스 사용법](objects/README.md)을 참고합니다.\n\n")
	}
	var example *collectionRecord
	for i := range g.collections {
		record := &g.collections[i]
		if record.Model != "" && record.Kind != "service_info" && record.Scope == "" && strings.HasPrefix(record.Package, "gophercloudsdk/"+key+"/") {
			example = record
			if strings.TrimPrefix(record.Package, "gophercloudsdk/"+key+"/") == exampleResources[parts[0]] {
				break
			}
		}
	}
	out.WriteString("## Go 사용\n\n```go\n")
	fmt.Fprintf(&out, "// context.Context ctx, *gophercloudsdk.Connection conn을 사용하는 함수 안에서\nservice, err := conn.%s(ctx)\nif err != nil { return err }\n", method)
	if example != nil {
		field := registryField(strings.TrimPrefix(example.Package, "gophercloudsdk/"+key+"/"))
		accessor := "service." + field + ".Resources"
		finder := "service." + field
		if example.Source == "sdk_owned" {
			finder = accessor
		}
		if example.Kind == "compound_identity" {
			accessor += "()"
			finder = accessor
		}
		fmt.Fprintf(&out, "for value, err := range %s.List(ctx) {\n    if err != nil { return err }\n    fmt.Println(value)\n}\n", accessor)
		if example.Find {
			fmt.Fprintf(&out, "value, err := %s.Find(ctx, resource.Name(\"example\"))\nif err != nil { return err }\n_ = value\n", finder)
		}
	} else {
		if parts[0] == "metric" {
			out.WriteString("data, err := service.Metrics.Query(ctx, metrics.QueryOpts{Query: \"up\"})\nif err != nil { return err }\nfmt.Println(data)\n")
		} else if err := g.writeListExample(&out, key, paths); err != nil {
			return err
		}
	}
	out.WriteString("```\n\n예제의 `fmt`는 표준 라이브러리, `resource`는 `gophercloudsdk/resource`입니다. Find는 기본적으로 미존재를 오류로 처리합니다. `resource.WithIgnoreMissing()`을 추가하면 `nil, nil`을 반환합니다. Delete의 기본값은 미존재 무시입니다.\n\n")
	if parts[0] == "metric" {
		out.WriteString("`metrics`는 `gophercloudsdk/metric/v1/metrics`입니다.\n\n")
	}
	out.WriteString("## 리소스와 공통 정책\n\n| 서비스 필드 | API 패키지 | 공통 정책·범위 |\n|---|---|---|\n")
	for _, path := range paths {
		var policies []string
		apiFile := "api_generated.go"
		for _, record := range g.collections {
			if record.Package != "gophercloudsdk/"+key+"/"+path || record.Model == "" {
				continue
			}
			if record.Source == "sdk_owned" {
				apiFile = "api.go"
			}
			label := "Resources"
			if record.Scope != "" {
				label = record.Scope + "(ctx, parent)"
			}
			if record.Kind == "string_set" {
				policies = append(policies, fmt.Sprintf("`%s`: 문자열 집합 조회·추가·확인·교체·삭제; Collection/상태 대기 없음", label))
				continue
			}
			if record.Kind == "service_info" {
				policies = append(policies, "`Get(ctx)`: 서비스 build 정보 singleton; ID·목록·변경·상태 대기 없음")
				continue
			}
			if record.Kind == "list_only" {
				policies = append(policies, "`List/All`: 목록만 제공; 단건 조회·변경·상태 대기 없음")
				continue
			}
			if record.Kind == "async_resource" {
				policies = append(policies, "`Resources`: ID 조회, 목록, 이름 조회, 상태 대기; `API.Delete`: 비동기 action Submission 반환, Collection.Delete는 미지원")
				continue
			}
			if record.Kind == "singleton" {
				operations := "Get·Defaults·Detail·Update·Reset"
				if strings.HasSuffix(record.Package, "/blockstorage/v3/quotasets") {
					operations = "Get·Defaults·Usage·Update·Reset"
				} else if strings.HasSuffix(record.Package, "/network/v2/extensions/quotas") {
					operations = "Get·Defaults·Detail·Update·Delete"
				} else if strings.HasSuffix(record.Package, "/loadbalancer/v2/quotas") {
					operations = "Get·Update·Reset; Defaults는 전역 조회"
				} else if strings.HasSuffix(record.Package, "/dns/v2/quotas") {
					operations = "Get·Update·Reset"
				}
				policies = append(policies, fmt.Sprintf("`%s`: 고정 프로젝트의 %s; List/Find/Wait 없음", label, operations))
				continue
			}
			if record.Kind == "named_singleton" {
				policies = append(policies, "`InClass(ctx, className)`: 고정 이름의 Get·Update; 프로젝트 해석·List·Reset·Wait 없음")
				continue
			}
			if record.Kind == "project_limits" {
				policies = append(policies, "`Fetch(ctx)` / `InProject(ctx, parent).Get(ctx)`: 현재/고정 프로젝트의 읽기 전용 singleton; List·Find·Wait·변경 없음")
				continue
			}
			if record.Kind == "project_resource_quota" {
				policies = append(policies, "`InProject(ctx, parent).ForResource(name)`: 고정 프로젝트+resource의 Get·Create·Update·Delete; `API.List/All`: quota 페이지 목록; 이름 Find·Wait 없음")
				continue
			}
			if record.Kind == "compound_identity" {
				label = "Resources() / InStack(ctx, ref) / ForStack(identity)"
			}
			if record.Kind == "event_log" {
				policies = append(policies, "`InStack(ctx, ref) / ForStack(identity)`: stack/resource별 이벤트 목록·resource_name+eventID 단건 조회; 이름 Find·변경·대기 없음")
				continue
			}
			if record.Kind == "compound_child" {
				policies = append(policies, "`InStack(ctx, ref) / ForStack(identity)`: resource_name 조회·목록·이름 해석·metadata·health·대기; nested 실제 owner 검증")
				continue
			}
			features := []string{"ID 조회", "목록"}
			if record.Find {
				features = append(features, "이름 조회")
			}
			if record.Delete {
				features = append(features, "삭제·삭제 대기")
			}
			if record.Wait {
				features = append(features, "상태 대기")
			}
			policies = append(policies, fmt.Sprintf("`%s`: %s", label, strings.Join(features, ", ")))
		}
		policy := strings.Join(policies, "; ")
		if policy == "" {
			policy = "API 연산 제공; 공통 Collection 미적용"
		}
		fmt.Fprintf(&out, "| `%s` | [%s](%s/%s) | %s |\n", registryField(path), path, path, apiFile, policy)
	}
	out.WriteString("\n공통 Collection은 정확한 이름 검색, 중복 이름 오류, 페이지 순회, context 취소와 HTTP 오류 보존을 적용합니다. 상태가 없는 리소스의 Wait는 `ErrUnsupported`를 반환합니다.\n\n")
	out.WriteString("## 변경 요청\n\n리소스 API의 Create/Update에 concrete options를 전달합니다. 기본 필드는 typed options로 지정하고 추가 필드는 `With...Field`로 지정합니다. query와 header도 해당 연산이 제공하는 `With...` 함수를 사용합니다. 기본 필드·헤더 덮어쓰기와 지원되지 않는 확장 방식은 요청 전에 거부합니다. 요청 builder interface는 SDK가 구현합니다.\n\n")
	out.WriteString("부모가 필요한 연산은 [범위 객체](../../docs/scoped-resources.md)를 사용합니다. 범위 객체가 제공하는 Create/Update에도 같은 concrete options를 사용합니다. 응답 변경 추적이나 Python cloud의 모든 복합 작업은 이 API 참조 페이지의 지원 범위를 뜻하지 않습니다.\n\n")
	out.WriteString("전체 비교 기준은 [openstacksdk 목록](../../api/openstacksdk/README.md), Go API 호출은 [전체 API 설명](../../api/README.md), 실행·검증은 [프로젝트 README](../../README.md)를 참고합니다.\n")
	return os.WriteFile(filepath.Join(g.root, key, "README.md"), []byte(out.String()), 0644)
}

// Where no common Collection exists yet, show a real typed list operation.
func (g *generator) writeListExample(out *strings.Builder, key string, paths []string) error {
	for _, path := range paths {
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(g.root, key, path, "api_generated.go"), nil, 0)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || !strings.HasPrefix(fn.Name.Name, "List") {
				continue
			}
			params := fn.Type.Params.List
			if len(params) != 1 {
				if len(params) != 2 {
					continue
				}
				if _, ok := params[1].Type.(*ast.Ellipsis); !ok {
					continue
				}
			}
			fmt.Fprintf(out, "for value, err := range service.%s.%s(ctx) {\n    if err != nil { return err }\n    fmt.Println(value)\n}\n", registryField(path), fn.Name.Name)
			return nil
		}
	}
	out.WriteString("// 아래 리소스 표에서 필요한 연산과 concrete options를 선택합니다.\nfmt.Println(service.RawClient().Endpoint)\n")
	return nil
}
