// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package apiversions

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/baremetal/apiversions"
	request "gophercloudsdk/request"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type APIVersion = upstream.APIVersion
type APIVersions = upstream.APIVersions
type GetResult = upstream.GetResult
type ListResult = upstream.ListResult

// Get invokes the upstream API with library-owned builders and result handling.
func (a *API) Get(ctx context.Context, v string) (*APIVersion, error) {
	result := upstream.Get(ctx, a.client, v)
	value0, err := result.Extract()
	err = request.Wrap("Get", "apiversions", err)
	return value0, err
}

// List invokes the upstream API with library-owned builders and result handling.
func (a *API) List(ctx context.Context) (*APIVersions, error) {
	result := upstream.List(ctx, a.client)
	value0, err := result.Extract()
	err = request.Wrap("List", "apiversions", err)
	return value0, err
}
