// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package volumeattach

import (
	context "context"
	fmt "fmt"
	servers "github.com/JSYoo5B/go-openstacksdk/compute/v2/servers"
	resource "github.com/JSYoo5B/go-openstacksdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
)

// VolumeAttachmentScope fixes the parent of its resources, sharing the SDK's lookup and wait policies.
type VolumeAttachmentScope struct {
	*resource.Collection[VolumeAttachment]
	api      *API
	parentID string
}

// InServer resolves the parent once; explicit IDs require no lookup request.
func (a *API) InServer(ctx context.Context, parent resource.Ref) (*VolumeAttachmentScope, error) {
	id, err := servers.New(a.client).Resources.ResolveID(ctx, parent)
	if err != nil {
		return nil, err
	}
	scope := &VolumeAttachmentScope{api: a, parentID: id}
	scope.Collection = scope.newResources()
	return scope, nil
}
func (s *VolumeAttachmentScope) newResources() *resource.Collection[VolumeAttachment] {
	return resource.NewCollection(resource.Adapter[VolumeAttachment]{
		Kind: "volumeattach",
		Get: func(ctx context.Context, id string) (*VolumeAttachment, error) {
			return s.api.Get(ctx, s.parentID, string(id))
		},
		ID:     func(v *VolumeAttachment) string { return fmt.Sprint(v.VolumeID) },
		Delete: func(ctx context.Context, id string) error { return s.api.Delete(ctx, s.parentID, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*VolumeAttachment, error] {
			q = maps.Clone(q)
			q.Del("status")
			if len(q) != 0 {
				return func(yield func(*VolumeAttachment, error) bool) { yield(nil, resource.ErrUnsupported) }
			}
			return s.api.listWithControl(ctx, s.parentID, control)
		}})
}

// Create applies Create within the fixed parent.
func (s *VolumeAttachmentScope) Create(ctx context.Context, opts CreateOpts, options ...CreateOption) (*VolumeAttachment, error) {
	return s.api.Create(ctx, s.parentID, opts, options...)
}
