// Code generated by sdkgen; DO NOT EDIT.
package v1

import (
	resource0 "github.com/JSYoo5B/go-openstacksdk/instanceha/v1/hosts"
	resource1 "github.com/JSYoo5B/go-openstacksdk/instanceha/v1/notifications"
	resource2 "github.com/JSYoo5B/go-openstacksdk/instanceha/v1/segments"
	resource3 "github.com/JSYoo5B/go-openstacksdk/instanceha/v1/vmoves"
	gophercloud "github.com/gophercloud/gophercloud/v2"
)

// Service shares one authenticated client across its resource APIs.
type Service struct {
	client        *gophercloud.ServiceClient
	Hosts         *resource0.API
	Notifications *resource1.API
	Segments      *resource2.API
	VMoves        *resource3.API
}

func New(client *gophercloud.ServiceClient) *Service {
	return &Service{client: client,
		Hosts:         resource0.New(client),
		Notifications: resource1.New(client),
		Segments:      resource2.New(client),
		VMoves:        resource3.New(client),
	}
}
func (s *Service) RawClient() *gophercloud.ServiceClient { return s.client }
