// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package federation

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/federation"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CreateMappingOpts = upstream.CreateMappingOpts
type CreateMappingResult = upstream.CreateMappingResult
type DeleteMappingResult = upstream.DeleteMappingResult
type Domain = upstream.Domain
type GetMappingResult = upstream.GetMappingResult
type Group = upstream.Group
type Mapping = upstream.Mapping
type MappingRule = upstream.MappingRule
type MappingsPage = upstream.MappingsPage
type RuleLocal = upstream.RuleLocal
type RuleProject = upstream.RuleProject
type RuleProjectRole = upstream.RuleProjectRole
type RuleRemote = upstream.RuleRemote
type RuleUser = upstream.RuleUser
type UpdateMappingOpts = upstream.UpdateMappingOpts
type UpdateMappingResult = upstream.UpdateMappingResult
type UserType = upstream.UserType

const UserTypeEphemeral = upstream.UserTypeEphemeral
const UserTypeLocal = upstream.UserTypeLocal

type CreateMappingOption = request.Option[CreateMappingOpts]

func WithCreateMappingOptions(value CreateMappingOpts) CreateMappingOption {
	return request.WithOptions(value)
}
func WithCreateMappingField(key string, value any) CreateMappingOption {
	return request.WithField[CreateMappingOpts](key, value)
}

type createMappingOptsBuilder struct {
	base   CreateMappingOpts
	config request.Config[CreateMappingOpts]
}

func (b createMappingOptsBuilder) ToMappingCreateMap() (map[string]any, error) {
	value0, err := b.base.ToMappingCreateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// CreateMapping invokes the upstream API with library-owned builders and result handling.
func (a *API) CreateMapping(ctx context.Context, mappingID string, opts CreateMappingOpts, options ...CreateMappingOption) (*Mapping, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CreateMapping", "federation", err)
		var zero0 *Mapping
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("CreateMapping", "federation", err)
		var zero0 *Mapping
		return zero0, err
	}
	_opts := createMappingOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.CreateMapping(ctx, a.client, mappingID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("CreateMapping", "federation", err)
	return value0, err
}

// DeleteMapping invokes the upstream API with library-owned builders and result handling.
func (a *API) DeleteMapping(ctx context.Context, mappingID string) error {
	return request.Wrap("DeleteMapping", "federation", upstream.DeleteMapping(ctx, a.client, mappingID).ExtractErr())
}

// GetMapping invokes the upstream API with library-owned builders and result handling.
func (a *API) GetMapping(ctx context.Context, mappingID string) (*Mapping, error) {
	result := upstream.GetMapping(ctx, a.client, mappingID)
	value0, err := result.Extract()
	err = request.Wrap("GetMapping", "federation", err)
	return value0, err
}

// ListMappings invokes the upstream API with library-owned builders and result handling.
func (a *API) ListMappings(ctx context.Context) iter.Seq2[*Mapping, error] {
	return resource.Stream(ctx, upstream.ListMappings(a.client), func(page pagination.Page) ([]Mapping, error) {
		values, err := upstream.ExtractMappings(page)
		return []Mapping(values), err
	})
}

type UpdateMappingOption = request.Option[UpdateMappingOpts]

func WithUpdateMappingOptions(value UpdateMappingOpts) UpdateMappingOption {
	return request.WithOptions(value)
}
func WithUpdateMappingField(key string, value any) UpdateMappingOption {
	return request.WithField[UpdateMappingOpts](key, value)
}

type updateMappingOptsBuilder struct {
	base   UpdateMappingOpts
	config request.Config[UpdateMappingOpts]
}

func (b updateMappingOptsBuilder) ToMappingUpdateMap() (map[string]any, error) {
	value0, err := b.base.ToMappingUpdateMap()
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	value0, err = request.MergeFieldsFor(value0, b.config.Fields, b.base)
	if err != nil {
		var zero0 map[string]any
		return zero0, err
	}
	return value0, nil
}

// UpdateMapping invokes the upstream API with library-owned builders and result handling.
func (a *API) UpdateMapping(ctx context.Context, mappingID string, opts UpdateMappingOpts, options ...UpdateMappingOption) (*Mapping, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("UpdateMapping", "federation", err)
		var zero0 *Mapping
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, true, false, false); err != nil {
		err = request.Wrap("UpdateMapping", "federation", err)
		var zero0 *Mapping
		return zero0, err
	}
	_opts := updateMappingOptsBuilder{base: cfg.Options, config: cfg}
	result := upstream.UpdateMapping(ctx, a.client, mappingID, _opts)
	value0, err := result.Extract()
	err = request.Wrap("UpdateMapping", "federation", err)
	return value0, err
}
