// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package roles

import (
	context "context"
	fmt "fmt"
	resource "gophercloudsdk/resource"
	iter "iter"
	maps "maps"
	url "net/url"
)

// Resources applies the SDK's shared lookup, missing-resource and wait policies.
func (a *API) newResources() *resource.Collection[Role] {
	return resource.NewCollection(resource.Adapter[Role]{
		Kind:      "roles",
		Get:       func(ctx context.Context, id string) (*Role, error) { return a.Get(ctx, string(id)) },
		ID:        func(v *Role) string { return fmt.Sprint(v.ID) },
		Name:      func(v *Role) string { return fmt.Sprint(v.Name) },
		NameQuery: func(name string) string { return name },
		Delete:    func(ctx context.Context, id string) error { return a.Delete(ctx, string(id)) },
		IterateControlled: func(ctx context.Context, q url.Values, control resource.ListControl) iter.Seq2[*Role, error] {
			q = maps.Clone(q)
			q.Del("status")
			options := make([]ListOption, 0, len(q))
			for key, values := range q {
				for _, value := range values {
					options = append(options, WithListQuery(key, value))
				}
			}
			return a.listWithControl(ctx, control, options...)
		}})
}
func (a *API) Find(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) (*Role, error) {
	return a.Resources.Find(ctx, ref, options...)
}
func (a *API) All(ctx context.Context, options ...resource.ListOption) ([]*Role, error) {
	return a.Resources.All(ctx, options...)
}
func (a *API) Remove(ctx context.Context, ref resource.Ref, options ...resource.LookupOption) error {
	return a.Resources.Delete(ctx, ref, options...)
}
func (a *API) WaitFor(ctx context.Context, ref resource.Ref, status string, options ...resource.WaitOption) (*Role, error) {
	return a.Resources.Wait(ctx, ref, status, options...)
}
func (a *API) WaitForDeletion(ctx context.Context, ref resource.Ref, options ...resource.WaitOption) error {
	return a.Resources.WaitDeleted(ctx, ref, options...)
}
