// Code generated by sdkgen from Gophercloud v2.15.0; DO NOT EDIT.
package drivers

import (
	context "context"
	gophercloud "github.com/gophercloud/gophercloud/v2"
	upstream "github.com/gophercloud/gophercloud/v2/openstack/baremetal/v1/drivers"
	pagination "github.com/gophercloud/gophercloud/v2/pagination"
	request "gophercloudsdk/request"
	resource "gophercloudsdk/resource"
	iter "iter"
)

// API owns the client and provides concrete inputs, optional extensions and normalized results.
type API struct{ client *gophercloud.ServiceClient }

func New(client *gophercloud.ServiceClient) *API     { return &API{client: client} }
func (a *API) RawClient() *gophercloud.ServiceClient { return a.client }

type CallVendorPassthruResult = upstream.CallVendorPassthruResult
type DiskProperties = upstream.DiskProperties
type Driver = upstream.Driver
type DriverPage = upstream.DriverPage
type DriverProperties = upstream.DriverProperties
type GetDiskPropertiesResult = upstream.GetDiskPropertiesResult
type GetDriverResult = upstream.GetDriverResult
type GetPropertiesResult = upstream.GetPropertiesResult
type ListDriversOpts = upstream.ListDriversOpts
type ListVendorPassthruMethodsResult = upstream.ListVendorPassthruMethodsResult
type VendorPassthruCallOpts = upstream.VendorPassthruCallOpts
type VendorPassthruMethod = upstream.VendorPassthruMethod
type CallVendorPassthruOption = request.Option[VendorPassthruCallOpts]

func WithCallVendorPassthruOptions(value VendorPassthruCallOpts) CallVendorPassthruOption {
	return request.WithOptions(value)
}

// CallVendorPassthru invokes the upstream API with library-owned builders and result handling.
func (a *API) CallVendorPassthru(ctx context.Context, driverName string, httpMethod string, opts VendorPassthruCallOpts, options ...CallVendorPassthruOption) (map[string]any, error) {
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("CallVendorPassthru", "drivers", err)
		var zero0 map[string]any
		return zero0, err
	}
	if err = request.ValidateCapabilities(cfg, false, false, false); err != nil {
		err = request.Wrap("CallVendorPassthru", "drivers", err)
		var zero0 map[string]any
		return zero0, err
	}
	result := upstream.CallVendorPassthru(ctx, a.client, driverName, httpMethod, cfg.Options)
	value0, err := result.Extract()
	err = request.Wrap("CallVendorPassthru", "drivers", err)
	return value0, err
}

// GetDriverDetails invokes the upstream API with library-owned builders and result handling.
func (a *API) GetDriverDetails(ctx context.Context, driverName string) (*Driver, error) {
	result := upstream.GetDriverDetails(ctx, a.client, driverName)
	value0, err := result.Extract()
	err = request.Wrap("GetDriverDetails", "drivers", err)
	return value0, err
}

// GetDriverDiskProperties invokes the upstream API with library-owned builders and result handling.
func (a *API) GetDriverDiskProperties(ctx context.Context, driverName string) (*DiskProperties, error) {
	result := upstream.GetDriverDiskProperties(ctx, a.client, driverName)
	value0, err := result.Extract()
	err = request.Wrap("GetDriverDiskProperties", "drivers", err)
	return value0, err
}

// GetDriverProperties invokes the upstream API with library-owned builders and result handling.
func (a *API) GetDriverProperties(ctx context.Context, driverName string) (*DriverProperties, error) {
	result := upstream.GetDriverProperties(ctx, a.client, driverName)
	value0, err := result.Extract()
	err = request.Wrap("GetDriverProperties", "drivers", err)
	return value0, err
}

type ListDriversOption = request.Option[ListDriversOpts]

func WithListDriversOptions(value ListDriversOpts) ListDriversOption {
	return request.WithOptions(value)
}
func WithListDriversQuery(key, value string) ListDriversOption {
	return request.WithQuery[ListDriversOpts](key, value)
}

type listDriversOptsBuilder struct {
	base   ListDriversOpts
	config request.Config[ListDriversOpts]
}

func (b listDriversOptsBuilder) ToListDriversOptsQuery() (string, error) {
	value0, err := b.base.ToListDriversOptsQuery()
	if err != nil {
		var zero0 string
		return zero0, err
	}
	value0, err = request.ExtendQuery(value0, b.config.Query)
	if err != nil {
		var zero0 string
		return zero0, err
	}
	return value0, nil
}

// ListDrivers invokes the upstream API with library-owned builders and result handling.
func (a *API) ListDrivers(ctx context.Context, options ...ListDriversOption) iter.Seq2[*Driver, error] {
	var opts ListDriversOpts
	cfg, err := request.Apply(opts, options...)
	if err != nil {
		err = request.Wrap("ListDrivers", "drivers", err)
		return func(yield func(*Driver, error) bool) { var zero *Driver; yield(zero, err) }
	}
	if err = request.ValidateCapabilities(cfg, false, true, false); err != nil {
		err = request.Wrap("ListDrivers", "drivers", err)
		return func(yield func(*Driver, error) bool) { var zero *Driver; yield(zero, err) }
	}
	_opts := listDriversOptsBuilder{base: cfg.Options, config: cfg}
	return resource.Stream(ctx, upstream.ListDrivers(a.client, _opts), func(page pagination.Page) ([]Driver, error) {
		values, err := upstream.ExtractDrivers(page)
		return []Driver(values), err
	})
}

// ListVendorPassthruMethods invokes the upstream API with library-owned builders and result handling.
func (a *API) ListVendorPassthruMethods(ctx context.Context, driverName string) (map[string]VendorPassthruMethod, error) {
	result := upstream.ListVendorPassthruMethods(ctx, a.client, driverName)
	value0, err := result.Extract()
	err = request.Wrap("ListVendorPassthruMethods", "drivers", err)
	return value0, err
}
